import { formatInTimeZone } from 'date-fns-tz';
import { toEventSchema } from '../src';

function formatDate(date, tz = 'Europe/Paris') {
  return formatInTimeZone(date, tz, "yyyy-MM-dd'T'HH:mm:ssXXX");
}

describe('toEventSchema', () => {
  it('offline event returns valid schema', () => {
    expect(
      toEventSchema(
        {
          longDescription: {
            fr: "Information des acteurs locaux sur les supports de diffusion en matière d'information et de promotion de la santé.\nPrésentation d'outils pédagogiques ludique disponibles en prêt.\nAccompagnement et conseils pour la mise en place de projets.",
          },
          country: {
            de: 'Frankreich (Metropolitan)',
            code: 'FR',
            oc: 'França (Metropolitana)',
            en: 'France (Metropolitan)',
            it: 'Francia (continente)',
            fr: 'France (Métropole)',
            es: 'Francia (Metropolitana)',
          },
          featured: false,
          private: 0,
          keywords: {
            fr: [
              'réseaux',
              'écrans',
              'santé',
              'outils',
              'information',
              'prévention',
            ],
          },
          accessibility: {
            ii: false,
            hi: false,
            vi: false,
            pi: false,
            mi: true,
          },
          dateRange: {
            ar: 'الخميس ٢٣ فبراير, 09:00',
            de: 'Donnerstag 23 Februar, 09:00',
            en: 'Thursday 23 February, 09:00',
            it: 'Giovedì 23 febbraio, 09:00',
            fr: 'Jeudi 23 février, 09h00',
            es: 'Jueves 23 febrero, 09:00',
          },
          timezone: 'Europe/Paris',
          imageCredits: null,
          originAgenda: {
            image: 'agenda7058537.jpg',
            uid: 7058537,
            title: 'Société Châtellerault',
          },
          description: {
            fr: "Découverte d'outils d'information et de prévention sur les réseaux et les écrans.",
          },
          title: {
            fr: 'Permanence IREPS sur les écrans et les réseaux',
          },
          onlineAccessLink: null,
          createdAt: '2022-08-08T12:59:26.000Z',
          uid: 69271537,
          draft: 0,
          timings: [
            {
              begin: '2023-02-23T09:00:00+01:00',
              end: '2023-02-23T12:00:00+01:00',
            },
          ],
          links: [],
          state: 2,
          slug: 'permanence-ireps-sur-les-ecrans-et-les-reseaux',
          updatedAt: '2022-08-08T12:59:42.000Z',
          addMethod: 'aggregation',
          image: {
            filename: 'c3e0a7f7ec504f04839927e8375c0159.base.image.jpg',
            size: {
              width: 700,
              height: 989,
            },
            variants: [
              {
                filename: 'c3e0a7f7ec504f04839927e8375c0159.full.image.jpg',
                size: {
                  width: 1755,
                  height: 2480,
                },
                type: 'full',
              },
              {
                filename: 'c3e0a7f7ec504f04839927e8375c0159.thumb.image.jpg',
                size: {
                  width: 200,
                  height: 200,
                },
                type: 'thumbnail',
              },
            ],
            base: 'https://02034510ef5d488190e4cf17d19a788b.s3.pub1.infomaniak.cloud/dev/',
          },
          attendanceMode: 1,
          particularites: [14],
          sourceAgendas: [
            {
              image: 'agenda7058537.jpg',
              private: 0,
              indexed: 1,
              locationSetUid: null,
              official: 1,
              description:
                'Retrouvez tous les événements de la thématique Société sur Châtellerault',
              title: 'Société Châtellerault',
              url: 'https://www.ville-chatellerault.fr/',
              _agg: 'eyJ1aWQiOjcwNTg1MzcsInRpdGxlIjoiU29jacOpdMOpIENow6J0ZWxsZXJhdWx0IiwiaW1hZ2UiOiJhZ2VuZGE3MDU4NTM3LmpwZyJ9',
              uid: 7058537,
              createdAt: '2018-04-24T08:21:20.000Z',
              officializedAt: '2019-04-11T14:10:05.000Z',
              slug: 'societe-chatellerault',
              updatedAt: '2022-12-20T10:00:25.000Z',
            },
          ],
          creatorUid: 92289656,
          equipement: 6,
          'thematique-social-societe': 35,
          registration: [
            {
              type: 'phone',
              value: '05 49 23 70 00',
            },
            {
              type: 'email',
              value: 'le4@grand-chatellerault.fr',
            },
          ],
          location: {
            disqualifiedDuplicates: null,
            access: {},
            city: 'Châtellerault',
            timezone: 'Europe/Paris',
            postalCode: '86100',
            latitude: 46.809767,
            imageCredits: null,
            description: {},
            setUid: null,
            uid: 27572659,
            createdAt: '2018-09-07T14:04:57.000Z',
            duplicateCandidates: [],
            countryCode: 'FR',
            adminLevel5: null,
            links: [],
            state: 1,
            extId: null,
            department: 'Vienne',
            slug: 'le-4-chatellerault',
            email: null,
            longitude: 0.542259,
            updatedAt: '2021-07-16T17:38:52.000Z',
            image: null,
            website: null,
            address: '4 rue Aimé Rasseteau Châtellerault',
            adminLevel3: null,
            agendaUid: 7058537,
            adminLevel1: 'Nouvelle-Aquitaine',
            adminLevel2: 'Vienne',
            mergedIn: null,
            _agg: 'eyJ1aWQiOjI3NTcyNjU5LCJuYW1lIjoiTGUgNCBDaMOidGVsbGVyYXVsdCJ9',
            tags: null,
            insee: '86066',
            phone: null,
            district: null,
            name: 'Le 4 Châtellerault',
            region: 'Nouvelle-Aquitaine',
          },
          ownerUid: 92289656,
          conditions: {
            fr: 'Entrée libre, gratuit',
          },
          age: {
            min: null,
            max: null,
          },
          status: 1,
          lastTiming: {
            begin: '2023-02-23T09:00:00+01:00',
            end: '2023-02-23T12:00:00+01:00',
          },
          nextTiming: {
            begin: '2023-02-23T09:00:00+01:00',
            end: '2023-02-23T12:00:00+01:00',
          },
        },
        {
          formatDate,
          url: 'https://openagenda.com/events/permanence-ireps-sur-les-ecrans-et-les-reseaux',
        },
      ),
    ).toEqual({
      '@context': 'https://schema.org',
      '@type': 'Event',
      '@id':
        'https://openagenda.com/events/permanence-ireps-sur-les-ecrans-et-les-reseaux',
      name: 'Permanence IREPS sur les écrans et les réseaux',
      description:
        "Découverte d'outils d'information et de prévention sur les réseaux et les écrans.",
      url: 'https://openagenda.com/events/permanence-ireps-sur-les-ecrans-et-les-reseaux',
      image:
        'https://02034510ef5d488190e4cf17d19a788b.s3.pub1.infomaniak.cloud/dev/c3e0a7f7ec504f04839927e8375c0159.base.image.jpg',
      startDate: '2023-02-23T09:00:00+01:00',
      endDate: '2023-02-23T12:00:00+01:00',
      eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
      eventStatus: 'https://schema.org/EventScheduled',
      location: {
        '@type': 'Place',
        name: 'Le 4 Châtellerault',
        address: {
          '@type': 'PostalAddress',
          streetAddress: '4 rue Aimé Rasseteau Châtellerault',
          addressLocality: 'Châtellerault',
          addressRegion: 'Nouvelle-Aquitaine',
          postalCode: '86100',
          addressCountry: 'FR',
        },
        geo: {
          '@type': 'GeoCoordinates',
          latitude: 46.809767,
          longitude: 0.542259,
        },
      },
    });
  });

  it('online event returns valid schema', () => {
    expect(
      toEventSchema(
        {
          longDescription: {},
          featured: false,
          private: 0,
          keywords: {},
          accessibility: {
            ii: false,
            hi: false,
            vi: false,
            pi: false,
            mi: false,
          },
          dateRange: {
            ar: '١٣ مارس - ٢٦ نوفمبر ٢٠٢١',
            de: '13 März - 26 November 2021',
            en: '13 March - 26 November 2021',
            fr: '13 mars - 26 novembre 2021',
            es: '13 marzo - 26 noviembre 2021',
          },
          timezone: 'Europe/Paris',
          originAgenda: {
            image: 'agenda39293149.jpg?__ts=1652705335470',
            uid: 39293149,
            title: 'Test Evénements en ligne',
          },
          description: {
            fr: 'test',
          },
          title: {
            fr: 'Un événement en ligne',
          },
          onlineAccessLink: 'https://oa.com',
          createdAt: '2021-03-08T13:47:45.000Z',
          uid: 64825695,
          draft: 0,
          timings: [
            {
              begin: '2021-03-13T10:00:00+01:00',
              end: '2021-03-13T13:30:00+01:00',
            },
            {
              begin: '2021-05-15T06:30:00+02:00',
              end: '2021-05-15T10:30:00+02:00',
            },
            {
              begin: '2021-11-13T08:00:00+01:00',
              end: '2021-11-13T12:00:00+01:00',
            },
            {
              begin: '2021-11-26T04:30:00+01:00',
              end: '2021-11-26T11:00:00+01:00',
            },
          ],
          member: {
            uid: 75052324,
            role: 2,
            phone: null,
            organization: null,
            name: null,
            position: null,
            email: null,
            _agg: 'eyJ1aWQiOjc1MDUyMzI0LCJuYW1lIjpudWxsfQ==',
          },
          links: [],
          state: 2,
          slug: 'un-evenement-en-ligne',
          updatedAt: '2021-10-04T15:22:43.000Z',
          addMethod: 'contribution',
          image: null,
          attendanceMode: 2,
          sourceAgendas: [],
          creatorUid: 75052324,
          registration: [
            {
              type: 'link',
              value: 'https://registration.com',
            },
          ],
          ownerUid: 75052324,
          conditions: {},
          age: {},
          status: 6,
          lastTiming: {
            begin: '2021-11-26T04:30:00+01:00',
            end: '2021-11-26T11:00:00+01:00',
          },
          nextTiming: null,
        },
        {
          formatDate,
          url: 'https://openagenda.com/events/un-evenement-en-ligne',
        },
      ),
    ).toEqual({
      '@context': 'https://schema.org',
      '@type': 'Event',
      '@id': 'https://openagenda.com/events/un-evenement-en-ligne',
      url: 'https://openagenda.com/events/un-evenement-en-ligne',
      name: 'Un événement en ligne',
      description: 'test',
      startDate: '2021-03-13T10:00:00+01:00',
      endDate: '2021-11-26T11:00:00+01:00',
      eventAttendanceMode: 'https://schema.org/OnlineEventAttendanceMode',
      eventStatus: 'https://schema.org/EventCancelled',
      offers: {
        '@type': 'Offer',
        url: 'https://registration.com',
        availability: 'https://schema.org/InStock',
      },
    });
  });

  it('mixed event returns valid schema', () => {
    expect(
      toEventSchema(
        {
          longDescription: {},
          country: {
            de: 'Frankreich (Metropolitan)',
            code: 'FR',
            oc: 'França (Metropolitana)',
            en: 'France (Metropolitan)',
            it: 'Francia (continente)',
            fr: 'France (Métropole)',
            es: 'Francia (Metropolitana)',
          },
          featured: false,
          private: 0,
          keywords: {},
          accessibility: {
            ii: false,
            hi: false,
            vi: false,
            pi: false,
            mi: false,
          },
          dateRange: {
            ar: 'الأحد ٦ يونيو ٢٠٢١, 10:00',
            de: 'Sonntag 6 Juni 2021, 10:00',
            en: 'Sunday 6 June 2021, 10:00',
            fr: 'Dimanche 6 juin 2021, 10h00',
            es: 'Domingo 6 junio 2021, 10:00',
          },
          timezone: 'Europe/Paris',
          originAgenda: {
            image: 'agenda39293149.jpg?__ts=1652705335470',
            uid: 39293149,
            title: 'Test Evénements en ligne',
          },
          description: {
            fr: 'test',
          },
          title: {
            fr: 'Un événement mixte',
          },
          onlineAccessLink: 'https://oa.com',
          createdAt: '2021-06-02T07:10:41.000Z',
          uid: 68683984,
          draft: 0,
          timings: [
            {
              begin: '2021-06-06T10:00:00+02:00',
              end: '2021-06-06T13:00:00+02:00',
            },
          ],
          member: {
            uid: 75052324,
            role: 2,
            phone: null,
            organization: null,
            name: null,
            position: null,
            email: null,
            _agg: 'eyJ1aWQiOjc1MDUyMzI0LCJuYW1lIjpudWxsfQ==',
          },
          links: [],
          state: 2,
          slug: 'un-evenement-mixte',
          updatedAt: '2021-06-02T07:10:41.000Z',
          addMethod: 'contribution',
          image: null,
          attendanceMode: 3,
          sourceAgendas: [],
          creatorUid: 75052324,
          registration: [],
          location: {
            disqualifiedDuplicates: null,
            access: {},
            city: null,
            timezone: 'Europe/Paris',
            postalCode: '49480',
            latitude: 47.498993,
            imageCredits: null,
            description: {},
            setUid: null,
            uid: 38652578,
            createdAt: '2021-03-08T13:46:47.000Z',
            duplicateCandidates: [],
            countryCode: 'FR',
            adminLevel5: null,
            links: [],
            state: 0,
            extId: null,
            department: 'Maine-et-Loire',
            slug: 'un-lieu_6830036',
            email: null,
            longitude: -0.49041,
            updatedAt: '2021-07-17T01:15:25.000Z',
            image: null,
            website: null,
            address: 'Lieu',
            adminLevel3: null,
            agendaUid: 39293149,
            adminLevel1: 'Pays de la Loire',
            adminLevel2: 'Maine-et-Loire',
            mergedIn: null,
            _agg: 'eyJ1aWQiOjM4NjUyNTc4LCJuYW1lIjoiVW4gbGlldSJ9',
            tags: null,
            insee: '18093',
            phone: null,
            district: "Saint-Sylvain-d'Anjou",
            name: 'Un lieu',
            region: 'Pays de la Loire',
          },
          ownerUid: 75052324,
          conditions: {},
          age: {},
          status: 1,
          lastTiming: {
            begin: '2021-06-06T10:00:00+02:00',
            end: '2021-06-06T13:00:00+02:00',
          },
          nextTiming: null,
        },
        {
          formatDate,
          url: 'https://openagenda.com/events/un-evenement-mixte',
        },
      ),
    ).toEqual({
      '@context': 'https://schema.org',
      '@type': 'Event',
      '@id': 'https://openagenda.com/events/un-evenement-mixte',
      url: 'https://openagenda.com/events/un-evenement-mixte',
      name: 'Un événement mixte',
      description: 'test',
      startDate: '2021-06-06T10:00:00+02:00',
      endDate: '2021-06-06T13:00:00+02:00',
      eventAttendanceMode: 'https://schema.org/MixedEventAttendanceMode',
      eventStatus: 'https://schema.org/EventScheduled',
      location: {
        '@type': 'Place',
        name: 'Un lieu',
        address: {
          '@type': 'PostalAddress',
          streetAddress: 'Lieu',
          addressLocality: null,
          addressRegion: 'Pays de la Loire',
          postalCode: '49480',
          addressCountry: 'FR',
        },
        geo: {
          '@type': 'GeoCoordinates',
          latitude: 47.498993,
          longitude: -0.49041,
        },
      },
    });
  });
});
