'use strict';

module.exports = {
  adminTabs: [{
    section: 'manage',
    key: 'events',
    label: 'Events',
    access: 'moderator',
    uri: 'agendaAdminShow'
  }, {
    section: 'manage',
    key: 'members',
    label: 'Members',
    uri: 'agendaAdminMembers',
    access: 'moderator'
  }, {
    section: 'manage',
    key: 'locations',
    label: 'Locations',
    uri: 'agendaAdminLocations',
    access: 'moderator'
  }, {
    section: 'manage',
    key: 'sources',
    label: 'Sources',
    res: '/:slug/admin/sources',
    access: 'administrator',
    requiredCred: 'aggregator',
    call: {
      subject: 'aggregator'
    }
  }, {
    section: 'manage',
    key: 'inbox',
    label: 'Inbox',
    uri: 'agendaAdminInbox',
    access: 'moderator'
  }, {
    section: 'manage',
    key: 'activities',
    label: 'Activities',
    uri: 'agendaAdminActivityApps',
    access: 'moderator'
  }, {
    section: 'export',
    key: 'facebook',
    label: 'Facebook',
    access: 'administrator',
    uri: 'facebookShow'
  }, {
    section: 'export',
    key: 'web',
    label: 'Web Integration',
    access: 'administrator',
    uri: 'agendaAdminWeb'
  }, {
    section: 'export',
    key: 'indesign',
    label: 'Indesign - Xml',
    uri: 'agendaAdminIndesign',
    access: 'administrator',
    requiredCred: 'indesign'
  }, {
    section: 'settings',
    key: 'settings_profile',
    label: 'Profile',
    access: 'administrator',
    uri: 'agendaSettingsEditApp',
    suffix: '/profile'
  }, {
    section: 'settings',
    key: 'settings_contribution',
    label: 'Contribution',
    access: 'administrator',
    uri: 'agendaSettingsEditApp',
    suffix: '/contribution'
  }, {
    section: 'settings',
    key: 'settings_advanced',
    label: 'Advanced',
    access: 'administrator',
    uri: 'agendaSettingsEditApp',
    suffix: '/advanced'
  }]
};
