"use strict";

module.exports = {
  "myAgendas": {
    "fr": "Mes agendas",
    "en": "My agendas",
    "de": "Meine Agendas",
    "br": "Ma deiziataerioù",
    "es": "Mis agendas",
    "it": "Le mie agende",
    "io": "crwdns14900:0crwdne14900:0",
    "oc": "Mas agendas",
    "nl": "Mijn Agenda's"
  },
  "createAgenda": {
    "fr": "Créer un agenda",
    "en": "Create an agenda",
    "de": "Veranstaltungskalender erstellen",
    "br": "Krouiñ un deiziataer",
    "es": "Crear una agenda",
    "it": "Creare un'agenda",
    "io": "crwdns14902:0crwdne14902:0",
    "oc": "Crear una agenda",
    "nl": "Een agenda aanmaken"
  },
  "editMember": {
    "fr": "Voir ma fiche contact",
    "en": "See my contact info",
    "it": "Vedere le mie informazioni di contatto",
    "io": "crwdns16468:0crwdne16468:0",
    "oc": "Véser ma ficha de contacte",
    "es": "Ver mi información de contacto",
    "nl": "Mijn contactgegevens bekijken",
    "br": "Gwelet ma fichadenn darempred"
  },
  "editMemberInformation": {
    "fr": "Les administrateurs de l'agenda requierent certaines informations additionnelles pour leur permettre de vous contacter en cas de besoin.",
    "en": "Administrators of this agenda require some additional information to allow them to contact you in case of need",
    "it": "Gli amministratori di questa agenda hanno bisogno di alcune informazioni aggiuntive per poterla contattare in caso di necessità",
    "io": "crwdns16470:0crwdne16470:0",
    "oc": "Los administrators de l'agenda an mestièr d'informacions suplementàrias per vos poder contactar al besonh",
    "es": "Los administradores de esta agenda requieren información adicional para ponerse en contacto contigo en caso de que lo necesiten",
    "nl": "De beheerders van de agenda hebben bepaalde aanvullende informatie nodig om contact met u op te kunnen nemen indien nodig",
    "br": "Merourien an deiziataer o deus ezhomm eus titouroù ouzhpenn evit gallout mont e darempred ganeoc'h ma vez ezhomm"
  },
  "otherActions": {
    "fr": "Autres actions",
    "en": "Other actions",
    "it": "Altre azioni",
    "io": "crwdns16472:0crwdne16472:0",
    "oc": "Autras accions",
    "es": "Otras acciones",
    "nl": "Andere acties",
    "br": "Oberoù"
  },
  "removeMember": {
    "fr": "Me retirer de l'agenda",
    "en": "Remove myself from the agenda",
    "it": "Lasciare l'agenda",
    "io": "crwdns16474:0crwdne16474:0",
    "oc": "Me tirar de l'agenda",
    "es": "Eliminarme de la agenda",
    "nl": "Mezelf uit de agenda verwijderen",
    "br": "En em dennañ eus an deiziataer"
  },
  "removeMemberInformation": {
    "fr": "Si vous vous retirez de l'agenda, vous cesserez d'être notifié de son activité et ne pourrez plus en éditer les événements ni d'en ajouter de nouveaux. L'agenda n'apparaitra plus dans votre page d'accueil.",
    "en": "If you remove yourself from the agenda, you will stop receiving notifications and will no longer be able to edit your events nor add new events. The agenda will stop appearing in your home screen.",
    "it": "Se ti rimuovi dall'agenda, smetterai di ricevere notifiche e non potrai più modificare i tuoi eventi né aggiungere nuovi eventi. L'agenda smetterà di apparire nella tua schermata iniziale.",
    "oc": "Se vos tiratz de l'agenda, recebretz pas mai las notificacions e poiretz pas pus modificar vòstres eveniments o n'apondre de novèls. L'agenda s'aficharà pas pus sus vòstre ecran d'acuèlh.",
    "io": "crwdns16476:0crwdne16476:0",
    "es": "Si te sales de la agenda, dejarás de recibir notificaciones y ya no podrás editar tus eventos ni añadir otros nuevos. La agenda dejará de aparecer en tu pantalla de inicio.",
    "nl": "Als u zich uit de agenda verwijdert, ontvangt u geen meldingen meer en kunt u geen evenementen meer bewerken of nieuwe toevoegen. De agenda verschijnt niet meer op uw startpagina.",
    "br": "Ma tilammat ac'hanoc'h eus an deiziataer, ne resevot ket kemennoù ken ha ne c'hallot ket kemmañ ho tegouezhioù na ouzhpennañ reoù nevez ken. Ne zeuio ket an deiziataer war ho pajenn degemer ken."
  },
  "searchAgenda": {
    "fr": "Rechercher un agenda",
    "en": "Search an agenda",
    "de": "Veranstaltungskalender suchen",
    "br": "Klask un deiziataer",
    "es": "Buscar una agenda",
    "it": "Cerca un'agenda",
    "io": "crwdns14904:0crwdne14904:0",
    "oc": "Cercar una agenda",
    "nl": "Een agenda zoeken"
  },
  "myEvents": {
    "fr": "Mes événements",
    "en": "My events",
    "de": "Meine Veranstaltungen",
    "br": "Ma darvoudoù",
    "es": "Mis eventos",
    "it": "I miei eventi",
    "io": "crwdns14906:0crwdne14906:0",
    "oc": "Mos eveniments",
    "nl": "Mijn evenementen"
  },
  "messages": {
    "fr": "Messages",
    "en": "Messages",
    "de": "Nachrichten",
    "br": "Kemennadennoù",
    "es": "Mensajes",
    "it": "Messaggi",
    "io": "crwdns14908:0crwdne14908:0",
    "oc": "Messatges",
    "nl": "Berichten"
  },
  "notifications": {
    "fr": "Notifications",
    "en": "Notifications",
    "de": "Benachrichtigungen",
    "br": "Kemennoù",
    "es": "Notificaciones",
    "it": "Notifiche",
    "io": "crwdns14910:0crwdne14910:0",
    "oc": "Notificacions",
    "nl": "Meldingen"
  },
  "addAnEvent": {
    "fr": "Ajouter un événement",
    "en": "Add an event",
    "de": "Veranstaltung hinzufügen",
    "br": "Ouzhpennañ un darvoud",
    "es": "Añadir un evento",
    "it": "Aggiungere un evento",
    "io": "crwdns14912:0crwdne14912:0",
    "oc": "Apondre un eveniment",
    "nl": "Een evenement toevoegen"
  },
  "manage": {
    "fr": "Gérer",
    "en": "Manage",
    "de": "Verwalten",
    "br": "Merañ",
    "es": "Gestionar",
    "it": "Gestire",
    "io": "crwdns14914:0crwdne14914:0",
    "oc": "Gerir",
    "nl": "Beheren"
  },
  "moderate": {
    "fr": "Modérer",
    "en": "Moderate",
    "de": "Moderieren",
    "br": "Habaskaat",
    "es": "Moderar",
    "it": "Moderato",
    "io": "crwdns14916:0crwdne14916:0",
    "oc": "Moderar",
    "nl": "Modereren"
  },
  "officialAgenda": {
    "fr": "Agenda officiel",
    "en": "Official agenda",
    "de": "Offizieller Veranstaltungskalender",
    "br": "Deiziataer ofisiel",
    "es": "Agenda oficial",
    "it": "Agenda ufficiale",
    "io": "crwdns14918:0crwdne14918:0",
    "oc": "Agenda oficiala",
    "nl": "Officiële agenda"
  },
  "welcomeTitle": {
    "fr": "Bienvenue sur votre compte OpenAgenda!",
    "en": "Welcome to your OpenAgenda account!",
    "de": "Willkommen in Ihrem OpenAgenda-Konto!",
    "br": "Degemer mat en ho kont OpenAgenda !",
    "es": "Bienvenido a su cuenta OpenAgenda!",
    "it": "Benvenuti nel suo account OpenAgenda!",
    "io": "crwdns14920:0crwdne14920:0",
    "oc": "Benvenguda sus vòstre compte OpenAgenda !",
    "nl": "Welkom bij uw OpenAgenda-account!"
  },
  "welcomeMessage": {
    "fr": "Vous pouvez rejoindre des agendas ouverts à la contribution ou créer votre propre agenda.",
    "en": "You can join agendas that are open to contribution or create your own agenda.",
    "de": "Sie können Kalendern beitreten, die für Beiträge geöffnet sind, oder Ihren eigenen Kalender erstellen.",
    "br": "Gallout a rit mont e-barzh deiziataerioù digor d'ar c'henlabourat pe krouiñ ho teiziataer deoc'h-c'hwi hoc'h-unan.",
    "es": "Puedes unirte a agendas abiertas a la contribución o crear tu propia agenda.",
    "it": "Puoi iscriverti a calendari aperti al contributo o creare il tuo calendario.",
    "io": "crwdns14922:0crwdne14922:0",
    "oc": "Podètz rejónher d'agendas dobèrtas a contribucion o crear vòstra pròpia agenda.",
    "nl": "U kunt deelnemen aan agenda's die openstaan voor bijdragen of uw eigen agenda maken."
  },
  "openAgendasOfMoment": {
    "fr": "Les agendas du moment ouverts à la contribution :",
    "en": "The agendas of the moment open to contributions :",
    "de": "Aktuelle offene Tagebücher :",
    "br": "Deiziataerioù ar mare digor d'ar c'henlabourat :",
    "es": "Agendas actuales abiertas a la contribución:",
    "it": "Agenda aperti attuali :",
    "io": "crwdns14924:0crwdne14924:0",
    "oc": "Las agendas del moment obèrtas a contribucion :",
    "nl": "De actuele agenda's die openstaan voor bijdragen :"
  },
  "contributeToExisting": {
    "fr": "Contribuez à un agenda existant",
    "en": "Contribute to an existing agenda",
    "de": "Fügen Sie Ihre Veranstaltung einem bestehenden Kalender hinzu.",
    "br": "Labourit war un deiziataer hag a zo anezhañ dija",
    "es": "Contribuir a una agenda existente",
    "it": "Contribuire ad un'agenda esistente",
    "io": "crwdns14926:0crwdne14926:0",
    "oc": "Contribuir a una agenda existenta",
    "nl": "Draag bij aan een bestaande agenda"
  },
  "orCreateYourAgenda": {
    "fr": "Ou créez votre propre agenda",
    "en": "Contribute to an existing agenda",
    "de": "Fügen Sie Ihre Veranstaltung einem bestehenden Kalender hinzu.",
    "br": "Labourit war un deiziataer hag a zo anezhañ dija",
    "es": "Contribuir a una agenda existente",
    "it": "Contribuire ad un'agenda esistente",
    "io": "crwdns14928:0crwdne14928:0",
    "oc": "Contribuir a una agenda existenta",
    "nl": "Draag bij aan een bestaande agenda"
  },
  "noResult": {
    "fr": "Aucun résultat trouvé",
    "en": "No result found",
    "de": "Keine Ergebnisse gefunden",
    "br": "N'eus bet kavet disoc'h ebet",
    "es": "Ningún resultado encontrado",
    "it": "Nessun risultato trovato",
    "io": "crwdns14930:0crwdne14930:0",
    "oc": "Pas cap resultat trobat",
    "nl": "Geen resultaat gevonden"
  },
  "createEvent": {
    "fr": "Créer un événement",
    "en": "Create an event",
    "de": "Neue Veranstaltung erstellen",
    "br": "Krouiñ un darvoud",
    "es": "Crear un evento",
    "it": "Creare un evento",
    "io": "crwdns14932:0crwdne14932:0",
    "oc": "Crear un eveniment",
    "nl": "Evenement aanmaken"
  },
  "searchEvent": {
    "fr": "Rechercher un événement",
    "en": "Search an event",
    "de": "Eine Veranstaltungen finden",
    "br": "Klask un darvoud",
    "es": "Buscar un evento",
    "it": "Ricerca di un evento",
    "io": "crwdns14934:0crwdne14934:0",
    "oc": "Cercar un eveniment",
    "nl": "Zoek een evenement"
  },
  "selectAgenda": {
    "fr": "Sélectionner l'agenda dans lequel créer l'événement",
    "en": "Select an agenda in which to create the event",
    "de": "Wähle den Veranstaltungskalender, in dem du deine Veranstaltung eintragen möchtest.",
    "br": "Diuzañ an deiziataer da grouiñ an darvoud ennañ",
    "es": "Seleccione la agenda en el que crear un evento",
    "it": "Selezionare il agenda in cui creare l'evento",
    "io": "crwdns14936:0crwdne14936:0",
    "oc": "Causir una agenda per i crear l'eveniment",
    "nl": "Selecteer de agenda waarin u het evenement wilt aanmaken"
  },
  "privateAgenda": {
    "fr": "Agenda privé",
    "en": "Private agenda",
    "de": "Privater Veranstaltungskalender",
    "br": "Deiziataer prevez",
    "es": "Agenda privada",
    "it": "Agenda privato",
    "io": "crwdns14938:0crwdne14938:0",
    "oc": "Agenda privada",
    "nl": "Privéagenda"
  },
  "privateEvent": {
    "fr": "Événement privé",
    "en": "Private event",
    "de": "Private Veranstalltung",
    "br": "Darvoud prevez",
    "es": "Evento privado",
    "it": "Evento privato",
    "io": "crwdns14940:0crwdne14940:0",
    "oc": "Eveniment privat",
    "nl": "Privé-evenement"
  },
  "draft": {
    "fr": "Brouillon",
    "en": "Draft",
    "de": "Entwurf",
    "br": "Brouilhed",
    "es": "Borrador",
    "it": "Bozza",
    "io": "crwdns14942:0crwdne14942:0",
    "oc": "Borrolhon",
    "nl": "Concept"
  },
  "contact": {
    "fr": "Contacter",
    "en": "Contact",
    "de": "Kontakt",
    "br": "Mont e darempred",
    "es": "Contactar",
    "it": "Contattare",
    "io": "crwdns14944:0crwdne14944:0",
    "oc": "Contactar",
    "nl": "Contact opnemen"
  },
  "see": {
    "fr": "Voir",
    "en": "See",
    "de": "Sehen",
    "br": "Gwelet",
    "es": "Ver",
    "it": "Vedere",
    "io": "crwdns14946:0crwdne14946:0",
    "oc": "Veire",
    "nl": "Bekijken"
  },
  "support": {
    "fr": "Support",
    "en": "Support",
    "de": "Unterstützung",
    "br": "Skor",
    "es": "Soporte",
    "it": "Supporto",
    "io": "crwdns14948:0crwdne14948:0",
    "oc": "Supòrt",
    "nl": "Ondersteuning"
  },
  "modify": {
    "fr": "Modifier",
    "en": "Modify",
    "de": "Bearbeiten",
    "br": "Kemmañ",
    "es": "Editar",
    "it": "Modificare",
    "io": "crwdns14950:0crwdne14950:0",
    "oc": "Modificar",
    "nl": "Wijzigen"
  },
  "noTitle": {
    "fr": "Titre non défini",
    "en": "Title not defined",
    "de": "Bitte fügen Sie Ihrer Veranstaltung einen Titel hinzu.",
    "br": "N'eo ket termenet an titl",
    "es": "Título indefinido",
    "it": "Titolo non definito",
    "io": "crwdns14952:0crwdne14952:0",
    "oc": "Títol non definit",
    "nl": "Titel niet gedefinieerd"
  },
  "noLocation": {
    "fr": "Lieu non défini",
    "en": "Location not defined",
    "de": "Bitte geben Sie den Veranstaltungsort an.",
    "br": "N'eo ket termenet al lec'h",
    "es": "Lugar no especificado",
    "it": "Posizione non definita",
    "io": "crwdns14954:0crwdne14954:0",
    "oc": "Lòc non definit",
    "nl": "Locatie niet gedefinieerd"
  },
  "noEventsCreated": {
    "fr": "Vous n'avez encore créé aucun événement",
    "en": "You haven't created any event yet",
    "de": "Du hast noch keine Veranstaltung erstellt.",
    "br": "N'ho peus krouet darvoud ebet c'hoazh",
    "es": "No has creado ningún evento aún",
    "it": "Non avete ancora creato alcun evento",
    "io": "crwdns14956:0crwdne14956:0",
    "oc": "Avètz pas encara creat cap eveniment",
    "nl": "U heeft nog geen evenement aangemaakt"
  },
  "show": {
    "fr": "Afficher",
    "en": "Open",
    "de": "Ansehen",
    "es": "Ver",
    "io": "crwdns14958:0crwdne14958:0",
    "it": "Aperta",
    "oc": "Dobrir",
    "nl": "Tonen",
    "br": "Diskouez"
  },
  "seeMore": {
    "fr": "Voir plus",
    "en": "See more",
    "de": "Mehr sehen",
    "br": "Gwelet muioc'h",
    "es": "Ver más",
    "it": "Vedere di più",
    "io": "crwdns14960:0crwdne14960:0",
    "oc": "Ne véser mai",
    "nl": "Meer zien"
  }
}
