'use strict';

module.exports = {
  sendAgain: {
    en: 'The activation email is being sent again',
    fr: "Le mail d'activation est en cours de ré-envoi",
    it: "L'e-mail di attivazione viene inviata di nuovo",
    de: 'Die Aktivierungs-E-Mail wird erneut gesendet.',
    pl: 'Email aktywacyjny jest wysyłany ponownie',
    es: 'El correo electrónico de activación está siendo re-enviado',
    br: 'Emeur o kas ar postel gweredekaat adarre',
    io: 'crwdns13036:0crwdne13036:0',
    oc: "L'email d'activacion es a se tornar mandar",
  },
  sendActivateOnSigninAttempt: {
    en: 'Your account is not activated. Click on the link contained in the activation email that was just sent to you.',
    fr: 'Votre compte n\'est pas activé. Cliquez sur le lien contenu dans le mail d\'activation qui vient de vous être envoyé.',
  },
  checkEmail: {
    en: 'Check your mail for a validation link',
    fr: 'Cliquez sur le lien de validation dans votre boîte de récéption',
    it: 'Controlla la tua mail per un link di convalida',
    de: 'Überprüfe Deine Mail auf einen Validierungslink.',
    pl: 'Sprawdź swoją pocztę pod kątem linku do walidacji',
    es: 'Haga clic en el enlace de validación en su caja de bares',
    br: 'Klikit war al liamm da validañ en ho poest-lizheroù',
    io: 'crwdns13038:0crwdne13038:0',
    oc: 'Gaitatz lo ligam de validacion dins vòstres emails',
  },
  checkEmailInstruction: {
    en: 'An email is being set containing the activation link for your account to the email address indicated here below. Check your inbox to complete your account creation process.',
    fr: "Un email contenant le lien d'activation de votre compte est en cours d'envoi vers le courriel indiqué ci-dessous. Vérifiez votre boîte de réception pour terminer votre inscription.",
    it: 'A breve ti verrà inviata un e-mail contenente il link di attivazione del tuo conto. Controlla la tua casella di posta per completare il processo di creazione del tuo account.',
    de: 'Eine E-Mail mit dem Aktivierungslink für dein Konto abgesendet wurde. Überprüfe deinen Posteingang, um deinen Kontoerstellungsprozess abzuschließen.',
    pl: 'Wkrótce zostanie do Ciebie wysłana wiadomość e-mail zawierająca link aktywacyjny dla Twojego konta. Sprawdź swoją skrzynkę odbiorczą, aby zakończyć proces tworzenia konta.',
    es: 'Un correo electrónico con su cuenta de enlace de activación será enviado a usted en un momento. Compruebe su bandeja de entrada para completar su registro.',
    br: "A-benn nebeut e vo kaset deoc'h ur postel gant al liamm da weredekaat ho kont. Sellit e-barzh ho poest-degemer evit echuiñ hoc'h enskrivadur.",
    io: 'crwdns13040:0crwdne13040:0',
    oc: "Un email vos serà mandat lèu amb lo ligam d'activacion pel vòstre compte. Gaitatz dins vòstre boita per acabar lo procèssus de creacion de compte.",
  },
  didNotReceive: {
    en: "<b>Didn't receive any mail?</b><br>1. Double-check the spelling of your email.<br/>2. Check your spam folder<br/> 3. %resend% <br/> 4. write us at %support%",
    fr: "<b>Vous n'avez pas reçu de mail?</b> <br/>1. Vérifiez l'orthographe du courriel indiqué ci-dessus <br/>2. Vérifiez votre dossier de courriers indésirables ou autres dossiers similaires (dossiers d'outils de type \"Mailinblack\") <br /> 3. %resend% <br/> 4. Écrivez-nous à %support%",
    it: 'Non hai ricevuto nessuna mail? %resend% o scrivi a %support%',
    de: 'Du hast keine Mail erhalten? %resend% oder schreibe uns an %support%.',
    pl: 'Nie otrzymałeś żadnej wiadomości e-mail? %resend% lub napisz do nas na %support%',
    es: 'No se recibe un correo electrónico? %resend% o escribir en %support%',
    br: "N'ho peus resevet postel ebet ? %resend% pe skrivit deomp da %support%",
    io: 'crwdns13042:0%resend%crwdnd13042:0%support%crwdne13042:0',
    oc: 'Avètz pas recebut cap email ? %resend% o escrivètz-nos a %support%',
  },
  resend: {
    en: 'Click here to resend',
    fr: "Cliquez ici pour relancer l'envoi",
    it: 'Cliccare qui per inviare di nuovo',
    de: 'Klicke hier, um wieder zu senden.',
    pl: 'Kliknij tutaj, aby wysłać ponownie',
    es: 'Haga clic aquí para iniciar el envío',
    br: 'Klikit amañ evit adkas',
    io: 'crwdns13044:0crwdne13044:0',
    oc: 'Clicatz aicí per tornar mandar',
  },
  stayUpToDate: {
    en: 'Stay up to date with what is going on with OpenAgenda!',
    fr: 'Restez au courant de ce qui se passe chez OpenAgenda!',
    it: 'Rimani aggiornato su ciò che sta succedendo con OpenAgenda!',
    de: 'Bleibe auf dem Laufenden über das Geschehen mit der OpenAgenda!',
    pl: 'Bądź na bieżąco z tym, co dzieje się z OpenAgendą!',
    es: 'Mantenerse al tanto de lo que está sucediendo en OpenAgenda!',
    br: "Gouezit diouzh ar pezh a c'hoarvez gant OpenAgenda !",
    io: 'crwdns13046:0crwdne13046:0',
    oc: 'Demoratz al fial de çò que se passa amb OpenAgenda !',
  },
  followUs: {
    en: 'Follow us',
    fr: 'Suivez nous',
    it: 'Seguici',
    de: 'Uns folgen',
    pl: 'Podążaj za nami',
    es: 'Síguenos',
    br: "Heulhit ac'hanomp",
    io: 'crwdns13048:0crwdne13048:0',
    oc: 'Seguissètz-nos',
  },
  followUsOnLinkedIn: {
    en: 'Follow us on LinkedIn',
    fr: 'Suivez-nous sur LinkedIn',
  },
  followUsOnBlueSky: {
    en: 'Follow us on Bluesky',
    fr: 'Suivez-nous sur Bluesky',
  },
  getOurNewsletter: {
    en: 'Get our newsletter',
    fr: "Recevez notre lettre d'information",
    it: 'Ricevere la nostra newsletter',
    de: 'Unseren Newsletter bekommen',
    pl: 'Pobierz nasz biuletyn informacyjny',
    es: 'Recibe nuestro boletín',
    br: 'Resevit hol lizher-kelaouiñ',
    io: 'crwdns13050:0crwdne13050:0',
    oc: "Recebètz nòstra letra d'informacions",
  },
  yourEmail: {
    en: 'Your email',
    fr: 'Votre email',
    it: 'Il suo indirizzo e-mail',
    de: 'Deine E-Mail',
    pl: 'Twój e-mail',
    es: 'Su email',
    br: 'Ho postel',
    io: 'crwdns13052:0crwdne13052:0',
    oc: 'Vòstre email',
  },
  subscribe: {
    en: 'Subscribe',
    fr: 'Abonnez-vous',
    it: 'Abbonarsi',
    de: 'Abonnieren',
    pl: 'Subskrybuj',
    es: 'suscribir',
    br: 'Koumanantit',
    io: 'crwdns13054:0crwdne13054:0',
    oc: "S'abonar",
  },
};
