changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableTelemetry: 0

initFields:
  version: 0.0.0
  author: ''
  description: ''
  license: ISC
  main: ''
  name: ''
  repository:
    type: git
    url: ''

initScope: openagenda

nodeLinker: node-modules

npmScopes:
  openagenda:
    npmPublishRegistry: 'https://registry.npmjs.org/'
    npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@openagenda/invitations@*':
    peerDependencies:
      mysql: ^2.18.1
    peerDependenciesMeta:
      mysql:
        optional: true
  '@openagenda/labels@*':
    dependencies:
      '@babel/runtime-corejs3': ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  babel-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  bootstrap@*:
    peerDependenciesMeta:
      jquery:
        optional: true
      popper.js:
        optional: true
  grant@^3.8.0:
    dependencies:
      express: ^4.16.0
  jest-environment-enzyme@^7.1.2:
    peerDependenciesMeta:
      react:
        optional: true
  knex@*:
    peerDependenciesMeta:
      mysql:
        optional: true
  react-error-boundary@^1.2.5:
    dependencies:
      prop-types: ^15.5.10
  react-final-form@*:
    peerDependencies:
      typescript: '>=3.7.0'
    peerDependenciesMeta:
      typescript:
        optional: true
  react-spinkit@^3.0.0:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  react-tagsinput@^3.19.0:
    dependencies:
      prop-types: ^15.6.0
  redux-form@^8.1.0:
    peerDependenciesMeta:
      immutable:
        optional: true

yarnPath: .yarn/releases/yarn-4.5.3.cjs
