initScope: openagenda

initFields:
  name: ""
  version: 0.0.0
  description: ""
  repository:
    type: git
    url: ""
  author: ""
  license: "ISC"
#  files: []
  main: ""
  scripts: {}

npmScopes:
  openagenda:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

preferDeferredVersions: true

changesetBaseRefs:
  - "main"
  - "origin/main"
  - "upstream/main"

packageExtensions:
  "@openagenda/dom-utils@*":
    dependencies:
      "@babel/runtime-corejs3": ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  "@openagenda/es-node@*":
    dependencies:
      lodash: ^4.17.4
  "@openagenda/invitations@*":
    peerDependencies:
      mysql: ^2.18.1
    peerDependenciesMeta:
      mysql:
        optional: true
  "@openagenda/labels@*":
    dependencies:
      "@babel/runtime-corejs3": ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  "@openagenda/utils@*":
    dependencies:
      "@babel/runtime-corejs3": ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  babel-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  bootstrap@*:
    peerDependenciesMeta:
      jquery:
        optional: true
      popper.js:
        optional: true
  grant@^3.8.0:
    dependencies:
      express: ^4.16.0
  jest-environment-enzyme@^7.1.2:
    peerDependenciesMeta:
      react:
        optional: true
  knex@*:
    peerDependenciesMeta:
      mysql:
        optional: true
  react-error-boundary@^1.2.5:
    dependencies:
      prop-types: ^15.5.10
  react-final-form@*:
    peerDependencies:
      typescript: ">=3.7.0"
    peerDependenciesMeta:
      typescript:
        optional: true
  react-hot-loader@^4.12.19:
    peerDependenciesMeta:
      "@types/react":
        optional: true
  react-spinkit@^3.0.0:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  react-tagsinput@^3.19.0:
    dependencies:
      prop-types: ^15.6.0
  redux-form@^8.1.0:
    peerDependenciesMeta:
      immutable:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
#  - path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
#    spec: "https://unpkg.com/@openagenda/yarn-plugin-workspace-lockfile"

yarnPath: .yarn/releases/yarn-sources.cjs

#enableInlineBuilds: true

#pnpMode: loose
#pnpFallbackMode: all

nodeLinker: node-modules

# Links
enableHyperlinks: false

enableTelemetry: 0

lockfileFilename: ${OA_PUBLIC_LOCKFILE:-yarn.lock-workspace}
