initScope: openagenda

npmScopes:
  openagenda:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-rc.js

packageExtensions:
  "knex@*":
    peerDependenciesMeta:
      "mysql":
        optional: true
  "create-react-class@*":
    peerDependenciesMeta:
      "react":
        optional: true
  "grant@^3.8.0":
    dependencies:
      "express": "^4.16.0"
  "react-error-boundary@*":
    dependencies:
      "prop-types": "^15.5.10"

  "@openagenda/es-node@*":
    dependencies:
      "lodash": "^4.17.4"
  "@openagenda/invitations@*":
    peerDependencies:
      "mysql": "^2.18.1"
    peerDependenciesMeta:
      "mysql":
        optional: true
