initScope: openagenda

npmScopes:
  openagenda:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  "@openagenda/dom-utils@*":
    dependencies:
      "@babel/runtime-corejs3": ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  "@openagenda/es-node@*":
    dependencies:
      lodash: ^4.17.4
  "@openagenda/invitations@*":
    peerDependencies:
      mysql: ^2.18.1
    peerDependenciesMeta:
      mysql:
        optional: true
  "@openagenda/labels@*":
    dependencies:
      "@babel/runtime-corejs3": ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  "@openagenda/utils@*":
    dependencies:
      "@babel/runtime-corejs3": ^7.9.0
      core-js: ^3.6.4
      regenerator-runtime: ^0.13.5
  babel-plugin-react-intl@*:
    dependencies:
      "@babel/types": ^7.9.0
  create-react-class@*:
    peerDependenciesMeta:
      react:
        optional: true
  grant@^3.8.0:
    dependencies:
      express: ^4.16.0
  knex@*:
    peerDependenciesMeta:
      mysql:
        optional: true
  react-error-boundary@*:
    dependencies:
      prop-types: ^15.5.10

yarnPath: .yarn/releases/yarn-sources.js
