version: '3.8'

services:

  devinstaller:
    build:
      context: docker/devinstaller
    user: ${UID}:${GID}
    working_dir: /root/oa
    command: /root/oa/docker/devinstaller/command.sh ${SITE_DOMAIN} ${API_DOMAIN} ${PMA_HOST} ${ELASTICHQ_DOMAIN}
    volumes:
      - .:/root/oa
      - ${SF_PROJECT_PATH}:/root/cibul-symfony
      - ${SF_API_PROJECT_PATH}:/root/cibulapi-symfony
      - ${SF_PROJECT_PATH}/php.ini:/usr/local/etc/php/php.ini
    env_file:
      .env

  nginx:
    container_name: nginx
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    env_file:
      .env
    volumes:
      - ./docker/nginx:/tmp/nginx
      - ${SF_PROJECT_PATH}/web:/static
      - ${SITE_SSL_CERT}:/ssl/cert.pem
      - ${SITE_SSL_KEY}:/ssl/key.pem
      - ${CLIENT_SSL_CERT:-/dev/null}:/ssl/client.crt
      - ${ES1_SSL_CERT:-/dev/null}:/ssl/es1.cert.pem
      - ${ES1_SSL_KEY:-/dev/null}:/ssl/es1.key.pem
      - ${ES7_SSL_CERT:-/dev/null}:/ssl/es7.cert.pem
      - ${ES7_SSL_KEY:-/dev/null}:/ssl/es7.key.pem
      - ${PMA_SSL_CERT:-/dev/null}:/ssl/pma.cert.pem
      - ${PMA_SSL_KEY:-/dev/null}:/ssl/pma.key.pem
      - ${ELASTICHQ_SSL_CERT:-/dev/null}:/ssl/elastichq.cert.pem
      - ${ELASTICHQ_SSL_KEY:-/dev/null}:/ssl/elastichq.key.pem
    command: >
      /bin/bash -c
        "for filename in $$(find /tmp/nginx/ -type f -name '*'); do
          mkdir -p $$(dirname $${filename/\/tmp\/nginx/\/etc\/nginx});
          cat $$filename \
            | envsubst \"`printf '$${%s} ' $$(bash -c \"compgen -A variable\")`\" \
            > $${filename/\/tmp\/nginx/\/etc\/nginx\/conf.d};
        done;
        /tmp/nginx/command.sh ${DEPLOY_ES_NGINX_PROXY:-0} ${DEPLOY_PMA_NGINX_PROXY:-0} ${DEPLOY_MAILCATCHER_NGINX_PROXY:-0} ${DEPLOY_ELASTICHQ_NGINX_PROXY:-0};
        nginx -g 'daemon off;'"
    links:
      - es1
      - es7
      - php
      - node
      - phpmyadmin
      - mailcatcher
      - elastichq
    depends_on:
      - node
      - php

  es1:
    container_name: es1
    image: andrewvos/docker-elasticsearch
    environment:
      - "ES_HEAP_SIZE=512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - .env:/.env
      - ${SF_PROJECT_PATH}:/cibul-symfony
      - ${SF_API_PROJECT_PATH}:/cibulapi-symfony
      - ${SF_PROJECT_PATH}/php.ini:/usr/local/etc/php/php.ini
      - ${MYSQL_CONTAINER_DATA_PATH}/client-key.pem:/ssl/db-key.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/client-cert.pem:/ssl/db-cert.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/ca.pem:/ssl/db-ca.pem
    links:
      - mysql
      - redis
      - node
    env_file:
      .env

  node:
    container_name: node
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        user: ${USER}
        uid: ${UID}
        gid: ${GID}
    user: ${UID}:${GID}
    working_dir: /root/oa
    command: yarn start
    volumes:
      - .:/root/oa
      - ${MYSQL_CONTAINER_DATA_PATH}/client-key.pem:/ssl/db-key.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/client-cert.pem:/ssl/db-cert.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/ca.pem:/ssl/db-ca.pem
      - ${REPO_SSL_CLIENT}:/root/.ssh/id_rsa
    links:
      - mysql
      - redis
      - es1
      - es7
      - mailcatcher
    depends_on:
      - mysql
      - redis
      - es1
      - es7
    environment:
      TZ: Etc/UTC
      NODE_ENV: ${NODE_ENV}
      DEBUG: ${DEBUG}
      OA_PORT: 8901
      OA_API_PORT: 8902
      OA_USE_X_FWD_PROTO: 1
      OA_DEV_DOMAIN: ${SITE_DOMAIN}
      OA_DEV_ROOT: ${SITE_ROOT}
      OA_MYSQL_DEV_DATABASE: ${MYSQL_DATABASE}
      OA_MYSQL_DEV_HOST: ${MYSQL_HOST}
      OA_MYSQL_DEV_PASSWORD: ${MYSQL_PASSWORD}
      OA_MYSQL_DEV_USER: ${MYSQL_USER}
      OA_MYSQL_DEV_SSL_ENABLED: 1
      OA_MYSQL_DEV_SSL_CA: /ssl/db-ca.pem
      OA_MYSQL_DEV_SSL_KEY: /ssl/db-key.pem
      OA_MYSQL_DEV_SSL_CERT: /ssl/db-cert.pem
      OA_ELASTICSEARCH_134_DEV_HOST: ${ES1_HOST}
      OA_ELASTICSEARCH_134_DEV_PORT: ${ES1_PORT:-9200}
      OA_ELASTICSEARCH_750_DEV_HOST: ${ES7_HOST}
      OA_ELASTICSEARCH_750_DEV_PORT: ${ES7_PORT:-9200}
      OA_REDIS_DEV_PORT: ${REDIS_PORT}
      OA_REDIS_DEV_HOST: ${REDIS_HOST}
      AWS_ACCESS_KEY_ID: ${AWS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET}
      MAILCATCHER_PORT: ${MAILCATCHER_PORT}
      MAILCATCHER_HOST: ${MAILCATCHER_HOST}

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --require_secure_transport=${MYSQL_SECURE_TRANSPORT:-ON}
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_CONTAINER_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_DUMP_FILE_PATH}:/docker-entrypoint-initdb.d/oa.sql

  redis:
    container_name: redis
    image: redis:4.0.14
    ports:
      - 6379:6379

  es7:
    container_name: es7
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      # PMA_VERBOSE: 1
      PMA_SSL_KEY: /ssl/db-key.pem
      PMA_SSL_CERT: /ssl/db-cert.pem
      PMA_SSL_CA: /ssl/db-ca.pem
    volumes:
      - ./docker/php/phpmyadmin.config.php:/etc/phpmyadmin/config.user.inc.php
      - ${MYSQL_CONTAINER_DATA_PATH}/client-key.pem:/ssl/db-key.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/client-cert.pem:/ssl/db-cert.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/ca.pem:/ssl/db-ca.pem
    links:
      - mysql

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher

  elastichq:
    container_name: elastichq
    image: elastichq/elasticsearch-hq
    restart: always
    environment:
      HQ_DEFAULT_URL: ${ELASTICHQ_CLIENT_URL:-http://es7:9200}
      HQ_ENABLE_SSL: ${ELASTICHQ_ENABLE_SSL:-True}
      CLIENT_KEY: /ssl/key.pem
      CLIENT_CERT: /ssl/cert.pem
      # HQ_DEBUG: "True"
    volumes:
      - ${ELASTICHQ_CLIENT_KEY:-/dev/null}:/ssl/key.pem
      - ${ELASTICHQ_CLIENT_CERT:-/dev/null}:/ssl/cert.pem
    links:
      - es7

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
