version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:1.17
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      .env
    volumes:
      - ./docker/nginx:/tmp/nginx
      - ${ASSETS_PATH}:/static
      - ${SITE_SSL_CERT}:/ssl/cert.pem
      - ${SITE_SSL_KEY}:/ssl/key.pem
      - ${API_SSL_CERT}:/ssl/api.cert.pem
      - ${API_SSL_KEY}:/ssl/api.key.pem
      - ${CLIENT_SSL_CERT:-/dev/null}:/ssl/client.crt
      - ${ES1_SSL_CERT:-/dev/null}:/ssl/es1.cert.pem
      - ${ES1_SSL_KEY:-/dev/null}:/ssl/es1.key.pem
      - ${ES7_SSL_CERT:-/dev/null}:/ssl/es7.cert.pem
      - ${ES7_SSL_KEY:-/dev/null}:/ssl/es7.key.pem
      - ${PMA_SSL_CERT:-/dev/null}:/ssl/pma.cert.pem
      - ${PMA_SSL_KEY:-/dev/null}:/ssl/pma.key.pem
      - ${ELASTICHQ_SSL_CERT:-/dev/null}:/ssl/elastichq.cert.pem
      - ${ELASTICHQ_SSL_KEY:-/dev/null}:/ssl/elastichq.key.pem
    command: >
      /bin/bash -c
        "for filename in $$(find /tmp/nginx/ -type f -name '*'); do
          mkdir -p $$(dirname $${filename/\/tmp\/nginx/\/etc\/nginx});
          cat $$filename \
            | envsubst \"`printf '$${%s} ' $$(bash -c \"compgen -A variable\")`\" \
            > $${filename/\/tmp\/nginx/\/etc\/nginx\/conf.d};
        done;
        /tmp/nginx/command.sh ${DEPLOY_ES_NGINX_PROXY:-0} ${DEPLOY_PMA_NGINX_PROXY:-0} ${DEPLOY_MAILCATCHER_NGINX_PROXY:-0} ${DEPLOY_ELASTICHQ_NGINX_PROXY:-0} ${DEPLOY_API_NGINX_PROXY:-0};
        nginx -g 'daemon off;'"
    links:
      - es1
      - es7
      - node
      - phpmyadmin
      - mailcatcher
      - elastichq
    depends_on:
      - node

  es1:
    container_name: es1
    image: andrewvos/docker-elasticsearch
    restart: always
    environment:
      - "ES_HEAP_SIZE=512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES1_CONTAINER_DATA_PATH}:/usr/share/elasticsearch/data

  node:
    container_name: node
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: ${DOCKER_USER:-}
    working_dir: /root/oa
    command: yarn ${NODE_YARN_COMMAND:-start}
    restart: always
    volumes:
      - .:/root/oa
      - ${MYSQL_SSL_CA}:/ssl/db-ca.pem
      - ${MYSQL_SSL_CERT}:/ssl/db-cert.pem
      - ${MYSQL_SSL_KEY}:/ssl/db-key.pem
      - ${REPO_SSL_CLIENT}:/root/.ssh/id_rsa
      - ${CLIENT_SSL_KEY:-/dev/null}:/root/.ssh/client.key
      - ${CLIENT_SSL_CERT:-/dev/null}:/root/.ssh/client.cert
    links:
      - mysql
      - redis
      - es1
      - es7
      - mailcatcher
    depends_on:
      - mysql
      - redis
      - es1
      - es7
    environment:
      TZ: Etc/UTC
      NODE_ENV: ${NODE_ENV}
      DEBUG: ${DEBUG}
      DEBUG_COLORS: ${DEBUG_COLORS}
      TERM: ${TERM}
      COLORTERM: ${COLORTERM}
      OA_PORT: 8901
      OA_API_PORT: 8902
      OA_USE_X_FWD_PROTO: 1
      OA_DOMAIN: ${SITE_DOMAIN}
      OA_ROOT: ${SITE_ROOT}
      API_ROOT: ${API_ROOT}
      API_DOMAIN: ${API_DOMAIN}
      OA_MYSQL_DEV_DATABASE: ${MYSQL_DATABASE}
      OA_MYSQL_DEV_HOST: ${MYSQL_HOST}
      OA_MYSQL_DEV_PASSWORD: ${MYSQL_PASSWORD}
      OA_MYSQL_DEV_USER: ${MYSQL_USER}
      OA_MYSQL_DEV_SSL_VERIFY: ${MYSQL_SSL_VERIFY}
      OA_MYSQL_DEV_SSL_CA: /ssl/db-ca.pem
      OA_MYSQL_DEV_SSL_KEY: /ssl/db-key.pem
      OA_MYSQL_DEV_SSL_CERT: /ssl/db-cert.pem
      OA_ELASTICSEARCH_134_DEV_HOST: ${ES1_HOST}
      OA_ELASTICSEARCH_134_DEV_PORT: ${ES1_PORT:-9200}
      OA_ELASTICSEARCH_134_DEV_USE_SSL: ${ES1_USE_SSL}
      OA_ELASTICSEARCH_750_DEV_HOST: ${ES7_HOST}
      OA_ELASTICSEARCH_750_DEV_PORT: ${ES7_PORT:-9200}
      OA_ELASTICSEARCH_750_DEV_USE_SSL: ${ES7_USE_SSL}
      OA_REDIS_DEV_PORT: ${REDIS_PORT}
      OA_REDIS_DEV_HOST: ${REDIS_HOST}
      AWS_ACCESS_KEY_ID: ${AWS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET}
      MAILCATCHER_PORT: ${MAILCATCHER_PORT}
      MAILCATCHER_HOST: ${MAILCATCHER_HOST}
      OA_CLIENT_SSL_KEY: /root/.ssh/client.key
      OA_CLIENT_SSL_CERT: /root/.ssh/client.cert
      OPENCAGE_KEY: ${OPENCAGE_KEY}
      IFRAMELY_KEY: ${IFRAMELY_KEY}
      MAP_TILES: ${MAP_TILES}
      MATOMO_CLOUD_ID: ${MATOMO_CLOUD_ID}
      GOOGLE_ANALYTICS_ID: ${GOOGLE_ANALYTICS_ID}
      GOOGLE_ANALYTICS_EMBED_ID: ${GOOGLE_ANALYTICS_EMBED_ID}
      STATIC_MAP_TILES: ${STATIC_MAP_TILES}
      OA_SESSION_KEYS: ${OA_SESSION_KEYS}
      OA_SESSION_SECRET: ${OA_SESSION_SECRET}
      OA_OAUTH_GOOGLE_ID: ${OA_OAUTH_GOOGLE_ID}
      OA_OAUTH_GOOGLE_SECRET: ${OA_OAUTH_GOOGLE_SECRET}
      OA_PUBLIC_LOCKFILE: yarn.lock
      OA_DISCORD_CHANNEL: ${OA_DISCORD_CHANNEL}
      OA_DISCORD_TOKEN: ${OA_DISCORD_TOKEN}
      OA_DETECT_LOCATION_DUPLICATES: ${OA_DETECT_LOCATION_DUPLICATES}
      OA_DETECT_LOCATION_DUPLICATES_IGNORED_SET_UIDS: ${OA_DETECT_LOCATION_DUPLICATES_IGNORED_SET_UIDS}
      OA_DETECT_LOCATION_DUPLICATES_IGNORED_AGENDA_UIDS: ${OA_DETECT_LOCATION_DUPLICATES_IGNORED_AGENDA_UIDS}
      OA_DETECT_LOCATION_DUPLICATES_SLEEP: ${OA_DETECT_LOCATION_DUPLICATES_SLEEP}
      CRISP_WEBSITE_ID: ${CRISP_WEBSITE_ID}

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --require_secure_transport=${MYSQL_SECURE_TRANSPORT:-ON}
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_CONTAINER_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_DUMP_FILE_PATH}:/docker-entrypoint-initdb.d/oa.sql

  redis:
    container_name: redis
    image: redis:6.0.6
    restart: always
    ports:
      - 6379:6379

  es7:
    container_name: es7
    build:
      context: ./docker/elasticsearch
    restart: always
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      # PMA_VERBOSE: 1
      PMA_SSL_KEY: /ssl/db-key.pem
      PMA_SSL_CERT: /ssl/db-cert.pem
      PMA_SSL_CA: /ssl/db-ca.pem
    volumes:
      - ./docker/phpmyadmin.config.php:/etc/phpmyadmin/config.user.inc.php
      - ${MYSQL_CONTAINER_DATA_PATH}/client-key.pem:/ssl/db-key.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/client-cert.pem:/ssl/db-cert.pem
      - ${MYSQL_CONTAINER_DATA_PATH}/ca.pem:/ssl/db-ca.pem
    links:
      - mysql

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    restart: always
    ports:
      - 1025:1025

  elastichq:
    container_name: elastichq
    image: elastichq/elasticsearch-hq
    restart: always
    environment:
      HQ_DEFAULT_URL: ${ELASTICHQ_CLIENT_URL:-http://es7:9200}
      HQ_ENABLE_SSL: ${ELASTICHQ_ENABLE_SSL:-True}
      CLIENT_KEY: /ssl/key.pem
      CLIENT_CERT: /ssl/cert.pem
      # HQ_DEBUG: "True"
    volumes:
      - ${ELASTICHQ_CLIENT_KEY:-/dev/null}:/ssl/key.pem
      - ${ELASTICHQ_CLIENT_CERT:-/dev/null}:/ssl/cert.pem
    links:
      - es7

volumes:
  esdata:
    driver: local
