version: '3.8'

services:
  node:
    command: >
      yarn concurrently -n "node,ria" \
      "yarn workspace cibul-node start" \
      "DEV_SERVER_HOST=0.0.0.0 yarn workspace @openagenda/react-integration-app dev"
    restart: unless-stopped
    environment:
      NODE_OPTIONS: --trace-warnings
      DEV_SERVER_PORT: ${DEV_SERVER_PORT:-8905}
      DEV_SSL_CERT: /ssl/cert.pem
      DEV_SSL_KEY: /ssl/key.pem
      DEV_SSL_CA: /ssl/ca.pem
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    volumes:
      - ${SITE_SSL_CERT}:/ssl/cert.pem
      - ${SITE_SSL_KEY}:/ssl/key.pem
      - ${SITE_SSL_CA}:/ssl/ca.pem
    ports:
      - 8905:8905
