version: '3.8'

services:
  node:
    command: >
      yarn concurrently -n "node,next,ria" \
      "yarn workspace cibul-node ${NODE_YARN_COMMAND:-start}" \
      "yarn workspace @openagenda/next dev" \
      "DEV_SERVER_HOST=0.0.0.0 yarn workspace @openagenda/react-integration-app dev"
    restart: unless-stopped
    environment:
      NODE_OPTIONS: --trace-warnings
      DEV_SERVER_PORT: ${DEV_SERVER_PORT:-8905}
      DEV_SSL_CERT: /ssl/cert.pem
      DEV_SSL_KEY: /ssl/key.pem
      DEV_SSL_CA: /ssl/ca.pem
    volumes:
      - ${SITE_SSL_CERT}:/ssl/cert.pem
      - ${SITE_SSL_KEY}:/ssl/key.pem
      - ${SITE_SSL_CA}:/ssl/ca.pem
    ports:
      - ${DEV_SERVER_PORT:-8905}:${DEV_SERVER_PORT:-8905}
