"use strict";

const _ = require( 'lodash' );
const { promisify } = require( 'util' );

const log = require( '@openagenda/logs' )( 'middleware/schema' );

const FormSchema = require( '../../iso/FormSchema' );


// const FILE_FIELD_PREFIX = require( '../../iso/fileFieldPrefix' );

module.exports = {
  clean
} 

function clean( ns, req, res, next ) {

  const namespaces = _.assign( {
    schema: 'schema',
    fileFieldValues: 'fileFieldValues',
    clean: 'clean',
    errors: 'errors'
  }, ns || {} );

  const values = {}; // values received in json bundle
  const decoratedValues = {}; // values decorated with processed field values received as multipart
  const clean = {}; // clean values to be generated by this mw

  // parse submitted values

  try {

    _.assign( values, JSON.parse( req.body.data ) );

  } catch ( e ) {

    log( 'error', 'could not parse submitted json', e );

    return next();

  }

  // add processed field values

  if ( _.keys( _.get( req, namespaces.fileFieldValues ) ).length ) {

    _.assign( decoratedValues, values, _.get( req, namespaces.fileFieldValues ) );

  } else {

    _.assign( decoratedValues, values );

  }

  // validate the whole thing

  const validate = ( new FormSchema( req[ namespaces.schema ] ) ).getValidate( { draft: req.draft } );

  try {

    _.assign( clean, validate( decoratedValues ) );

  } catch ( errors ) {

    req[ namespaces.errors ] = errors;

    return next();

  }

  req[ namespaces.clean ] = clean;

  next();

}
