'use strict';

const labels = require('@openagenda/labels/agenda-locations/exportHeaders');

module.exports = [{
  field: 'id',
  optional: false,
  fieldType: 'integer',
  read: ['internal'],
  write: ['internal'],
}, {
  field: 'uid',
  fieldType: 'integer',
  optional: false,
  read: ['internal', 'public', 'list'],
  write: ['internal'],
  label: labels.uid,
}, {
  field: 'agendaId',
  fieldType: 'integer',
  optional: false,
  read: ['internal'],
  write: ['internal'],
}, {
  field: 'setUid',
  fieldType: 'integer',
  optional: true,
  default: null,
  read: ['internal', 'public'],
  write: ['internal'],
}, {
  field: 'slug',
  fieldType: 'text',
  optional: false,
  read: ['internal', 'public'],
  write: ['internal'],
  max: 100,
}, {
  field: 'name',
  db: 'placename',
  optional: false,
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'list', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'text',
  max: 150,
  label: labels.name,
}, {
  field: 'address',
  optional: false,
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'list'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.address,
}, {
  field: 'countryCode',
  db: 'country',
  optional: false,
  fieldType: 'text',
  max: 2,
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  label: labels.countryCode,
}, {
  field: 'adminLevel1',
  optional: true,
  fieldType: 'text',
  db: 'region',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.region,
}, {
  field: 'adminLevel2',
  optional: true,
  fieldType: 'text',
  db: 'department',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.department,
}, {
  field: 'adminLevel3',
  optional: true,
  fieldType: 'text',
  db: 'admin_level_3',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.adminLevel3,
}, {
  field: 'adminLevel4',
  optional: true,
  fieldType: 'text',
  db: 'city',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 100,
  label: labels.city,
}, {
  field: 'city',
  optional: true,
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 100,
  label: labels.city,
}, {
  field: 'adminLevel5',
  optional: true,
  fieldType: 'text',
  db: 'admin_level_5',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
}, {
  field: 'adminLevel6',
  optional: true,
  fieldType: 'text',
  db: 'city_district',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
}, {
  field: 'district',
  optional: true,
  fieldType: 'text',
  db: 'city_district',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.district,
}, {
  field: 'postalCode',
  optional: true,
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 20,
  label: labels.postalCode,
}, {
  field: 'insee',
  optional: true,
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 10,
  label: labels.insee,
}, {
  field: 'latitude',
  optional: false,
  fieldType: 'latitude',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'list'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  label: labels.latitude,
}, {
  field: 'longitude',
  optional: false,
  fieldType: 'longitude',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'list'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  label: labels.longitude,
}, {
  field: 'region',
  optional: true,
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.region,
}, {
  field: 'department',
  optional: true,
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'terms'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  max: 255,
  label: labels.department,
}, {
  field: 'timezone',
  optional: true,
  db: {
    type: 'json',
    field: 'store.timezone',
    assign: true,
  },
  fieldType: 'text',
  read: ['internal', 'public'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
}, {
  field: 'updatedAt',
  optional: false,
  fieldType: 'date',
  read: ['internal', 'public'],
  write: ['internal'],
}, {
  field: 'createdAt',
  optional: false,
  fieldfieldType: 'date',
  read: ['internal', 'public'],
  write: ['internal'],
}, {
  field: 'image',
  optional: true,
  db: {
    type: 'json',
    field: 'store.image',
    assign: true,
  },
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'stream',
  allowNull: true,
}, {
  field: 'description',
  label: labels.description,
  optional: true,
  db: {
    type: 'json',
    field: 'store.description',
    assign: true,
  },
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'multilingual',
  languages: [],
  max: 5000,
}, {
  field: 'tags',
  optional: true,
  db: {
    type: 'json',
    field: 'store.tags',
    assign: true,
  },
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'pass',
}, {
  field: 'website',
  db: {
    type: 'json',
    field: 'store.website',
    assign: true,
  },
  optional: true,
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'link',
  label: labels.website,
}, {
  field: 'email',
  db: {
    type: 'json',
    field: 'store.email',
    assign: true,
  },
  optional: true,
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'email',
}, {
  field: 'phone',
  db: {
    type: 'json',
    field: 'store.phone',
    assign: true,
  },
  optional: true,
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'phone',
}, {
  field: 'links',
  optional: true,
  db: {
    type: 'json',
    field: 'store.links',
    assign: true,
  },
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  list: true,
  fieldType: 'link',
}, {
  field: 'access',
  label: labels.access,
  optional: true,
  db: {
    type: 'json',
    field: 'store.access',
    assign: true,
  },
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  fieldType: 'multilingual',
  languages: [],
  max: 1000,
}, {
  field: 'state',
  optional: true,
  db: {
    type: 'json',
    field: 'store.state',
    assign: true,
  },
  fieldType: 'choice',
  unique: true,
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor', 'list'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  default: 0,
  options: [0, 1],
}, {
  field: 'imageCredits',
  optional: true,
  db: {
    type: 'json',
    field: 'store.imageCredits',
    assign: true,
  },
  fieldType: 'text',
  read: ['internal', 'public', 'administrator', 'moderator', 'contributor'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  enableWith: 'image',
}, {
  field: 'imageRightsAreHeld',
  optional: true,
  db: {
    type: 'json',
    field: 'store.imageRightsAreHeld',
    assign: true,
  },
  fieldType: 'text',
  read: ['internal', 'public'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
  enableWith: 'image',
}, {
  field: 'extId',
  optional: true,
  fieldType: 'text',
  read: ['internal', 'public'],
  write: ['internal', 'administrator', 'moderator', 'contributor'],
}, {
  field: 'eveId',
  optional: true,
  fieldType: 'text',
  read: ['internal'],
  write: ['internal'],
}, {
  field: 'duplicateCandidates',
  fieldType: 'integer',
  list: {
    max: 100,
  },
  default: null,
  db: {
    assign: true,
    type: 'json',
    field: 'duplicates.candidates',
  },
  optional: true,
  read: ['internal', 'public'],
  write: ['internal', 'contributor'],
}, {
  field: 'disqualifiedDuplicates',
  fieldType: 'integer',
  list: {
    max: 100,
  },
  default: null,
  db: {
    assign: true,
    type: 'json',
    field: 'duplicates.disqualified',
  },
  optional: true,
  read: ['internal', 'public'],
  write: ['internal', 'contributor'],
}, {
  field: 'mergedIn',
  fieldType: 'integer',
  optional: true,
  default: null,
  read: ['internal', 'public'],
  write: ['internal'],
},
];
