create table if not exists `agenda_event` (
  id bigint(20) not null auto_increment,
  agenda_uid bigint(20) not null,
  event_uid bigint(20) not null,
  user_uid bigint(20),
  source_agenda_uid varchar(2000),
  state tinyint(1) not null default 0,
  featured tinyint(1) not null default 0,
  can_edit tinyint(1) default 0,
  created_at datetime not null,
  updated_at datetime not null,
  removed tinyint(1) not null default 0,
  aggregated varchar(32) default null,
  motive TEXT default null,
  index user_uid_idx (user_uid),
  index agenda_uid_idx (agenda_uid),
  index event_uid_idx (event_uid),
  index aggregated_idx (aggregated),
  index agenda_uid_event_uid_idx (agenda_uid, event_uid),
  primary key ( id )
) engine=InnoDB  default character set utf8mb4 collate utf8mb4_0900_ai_ci;
