"use strict";

module.exports = {
  "AD": {
    "en": "Andorra",
    "fr": "Andorre",
    "de": "Andorra",
    "es": "Andorra",
    "it": "Andorra",
    "io": "crwdns11610:0crwdne11610:0",
    "oc": "Andòrra",
    "nl": "Andorra",
    "br": "Andorra"
  },
  "AE": {
    "en": "United Arab Emirates",
    "fr": "Emirats Arabes Unis",
    "de": "Vereinigte Arabische Emirate",
    "es": "Emiratos Árabes Unidos",
    "it": "Emirati Arabi Uniti",
    "io": "crwdns11612:0crwdne11612:0",
    "oc": "Emirats Arabs Units",
    "nl": "Verenigde Arabische Emiraten",
    "br": "Emirelezhioù Arab Unanet"
  },
  "AF": {
    "en": "Afghanistan",
    "fr": "Afghanistan",
    "de": "Afghanistan",
    "es": "Afganistán",
    "it": "Afghanistan",
    "io": "crwdns11614:0crwdne11614:0",
    "oc": "Afganistan",
    "nl": "Afghanistan",
    "br": "Afghanistan"
  },
  "AG": {
    "en": "Antigua and Barbuda",
    "fr": "Antigua et Barbuda",
    "de": "Antigua und Barbuda",
    "es": "Antigua y Barbuda",
    "it": "Antigua e Barbuda",
    "io": "crwdns11616:0crwdne11616:0",
    "oc": "Antigua e Barbuda",
    "nl": "Antigua en Barbuda",
    "br": "Antigua ha Barbuda"
  },
  "AI": {
    "en": "Anguilla",
    "fr": "Anguilla",
    "de": "Anguilla",
    "es": "Anguilla",
    "it": "Anguilla",
    "io": "crwdns11618:0crwdne11618:0",
    "oc": "Anguilha",
    "nl": "Anguilla",
    "br": "Anguilla"
  },
  "AL": {
    "en": "Albania",
    "fr": "Albanie",
    "de": "Albanien",
    "es": "Albania",
    "it": "Albania",
    "io": "crwdns11620:0crwdne11620:0",
    "oc": "Albania",
    "nl": "Albanië",
    "br": "Albania"
  },
  "AM": {
    "en": "Armenia",
    "fr": "Arménie",
    "de": "Armenien",
    "es": "Armenia",
    "it": "Armenia",
    "io": "crwdns11622:0crwdne11622:0",
    "oc": "Armenia",
    "nl": "Armenië",
    "br": "Armenia"
  },
  "AN": {
    "en": "Netherlands Antilles",
    "fr": "Antilles Néerlandaises",
    "de": "Niederländische Antillen",
    "es": "Antillas Holandesas",
    "it": "Antille olandesi",
    "io": "crwdns11624:0crwdne11624:0",
    "oc": "Antilhas olandesas",
    "nl": "Nederlandse Antillen",
    "br": "Antilhez Nederlandat"
  },
  "AO": {
    "en": "Angola",
    "fr": "Angola",
    "de": "Angola",
    "es": "Angola",
    "it": "Angola",
    "io": "crwdns11626:0crwdne11626:0",
    "oc": "Angòla",
    "nl": "Angola",
    "br": "Angola"
  },
  "AQ": {
    "en": "Antarctica",
    "fr": "Antartique",
    "de": "Antarktika",
    "es": "Antártida",
    "it": "Antartico",
    "io": "crwdns11628:0crwdne11628:0",
    "oc": "Antartica",
    "nl": "Antarctica",
    "br": "Antarktika"
  },
  "AR": {
    "en": "Argentina",
    "fr": "Argentine",
    "de": "Argentinien",
    "es": "Argentina",
    "it": "Argentina",
    "io": "crwdns11630:0crwdne11630:0",
    "oc": "Argentina",
    "nl": "Argentinië",
    "br": "Arc'hantina"
  },
  "AS": {
    "en": "American Samoa",
    "fr": "Samoa Américaines",
    "de": "Amerikanischen Samoa-Inseln",
    "es": "Samoa Americana",
    "it": "Samoa americane",
    "io": "crwdns11632:0crwdne11632:0",
    "oc": "Samoa americana",
    "nl": "Amerikaans-Samoa",
    "br": "Samoa Amerikan"
  },
  "AT": {
    "en": "Austria",
    "fr": "Autriche",
    "de": "Österreich",
    "es": "Austria",
    "it": "Austria",
    "io": "crwdns11634:0crwdne11634:0",
    "oc": "Àustria",
    "nl": "Oostenrijk",
    "br": "Aostria"
  },
  "AU": {
    "en": "Australia",
    "fr": "Australie",
    "de": "Australien",
    "es": "Australia",
    "it": "Australia",
    "io": "crwdns11636:0crwdne11636:0",
    "oc": "Austràlia",
    "nl": "Australië",
    "br": "Aostralia"
  },
  "AW": {
    "en": "Aruba",
    "fr": "Aruba",
    "de": "Aruba",
    "es": "aruba",
    "it": "Aruba",
    "io": "crwdns11638:0crwdne11638:0",
    "oc": "Aruba",
    "nl": "Aruba",
    "br": "Aruba"
  },
  "AZ": {
    "en": "Azerbaijan",
    "fr": "Azerbaïdjan",
    "de": "Aserbaidschan",
    "es": "Azerbaiyán",
    "it": "Azerbaigian",
    "io": "crwdns11640:0crwdne11640:0",
    "oc": "Azerbaitjan",
    "nl": "Azerbeidzjan",
    "br": "Azerbaidjan"
  },
  "BA": {
    "en": "Bosnia and Herzegovina",
    "fr": "Bosnie Herzégovine",
    "de": "Bosnien und Herzegowina",
    "es": "Bosnia Herzegovina",
    "it": "Bosnia-Erzegovina",
    "io": "crwdns11642:0crwdne11642:0",
    "oc": "Bòsnia e Ercegovina",
    "nl": "Bosnië en Herzegovina",
    "br": "Bosnia-Herzegovina"
  },
  "BB": {
    "en": "Barbados",
    "fr": "Barbados",
    "de": "Barbados",
    "es": "Barbados",
    "it": "Barbados",
    "io": "crwdns11644:0crwdne11644:0",
    "oc": "Barbados",
    "nl": "Barbados",
    "br": "Barbados"
  },
  "BD": {
    "en": "Bangladesh",
    "fr": "Bengladesh",
    "de": "Bangladesch",
    "es": "Bangladesh",
    "it": "Bangladesh",
    "io": "crwdns11646:0crwdne11646:0",
    "oc": "Bangladèsh",
    "nl": "Bangladesh",
    "br": "Bangladesh"
  },
  "BE": {
    "en": "Belgium",
    "fr": "Belgique",
    "de": "Belgien",
    "es": "Bélgica",
    "it": "Belgio",
    "io": "crwdns11648:0crwdne11648:0",
    "oc": "Belgica",
    "nl": "België",
    "br": "Belgia"
  },
  "BF": {
    "en": "Burkina Faso",
    "fr": "Burkina Faso",
    "de": "Burkina Faso",
    "es": "Burkina Faso",
    "it": "Burkina Faso",
    "io": "crwdns11650:0crwdne11650:0",
    "oc": "Burkina Faso",
    "nl": "Burkina Faso",
    "br": "Burkina Faso"
  },
  "BG": {
    "en": "Bulgaria",
    "fr": "Bulgarie",
    "de": "Bulgarien",
    "es": "Bulgaria",
    "it": "Bulgaria",
    "io": "crwdns11652:0crwdne11652:0",
    "oc": "Bulgaria",
    "nl": "Bulgarije",
    "br": "Bulgaria"
  },
  "BH": {
    "en": "Bahrain",
    "fr": "Barheïn",
    "de": "Bahrein",
    "es": "Bahrein",
    "it": "Bahrein",
    "io": "crwdns11654:0crwdne11654:0",
    "oc": "Bahrain",
    "nl": "Bahrein",
    "br": "Bahrein"
  },
  "BI": {
    "en": "Burundi",
    "fr": "Burundi",
    "de": "Burundi",
    "es": "Burundi",
    "it": "Burundi",
    "io": "crwdns11656:0crwdne11656:0",
    "oc": "Burundi",
    "nl": "Burundi",
    "br": "Burundi"
  },
  "BJ": {
    "en": "Benin",
    "fr": "Bénin",
    "de": "Benin",
    "es": "Benin",
    "it": "Benin",
    "io": "crwdns11658:0crwdne11658:0",
    "oc": "Benin",
    "nl": "Benin",
    "br": "Benin"
  },
  "BL": {
    "en": "Saint-Barthélemy",
    "fr": "Saint-Barthélemy",
    "de": "Saint-Barthélemy",
    "es": "San Bartolomé",
    "it": "Saint-Barthélemy",
    "io": "crwdns11660:0crwdne11660:0",
    "oc": "Sant Bartomieu",
    "nl": "Saint-Barthélemy",
    "br": "Sant-Barthélemy"
  },
  "BM": {
    "en": "Bermuda",
    "fr": "Bermudes",
    "de": "Bermuda",
    "es": "Bermuda",
    "it": "Bermuda",
    "io": "crwdns11662:0crwdne11662:0",
    "oc": "Bermudas",
    "nl": "Bermuda",
    "br": "Bermuda"
  },
  "BN": {
    "en": "Brunei Darussalam",
    "fr": "Bruneï",
    "de": "Brunei Darussalam",
    "es": "Brunei",
    "it": "Brunei",
    "io": "crwdns11664:0crwdne11664:0",
    "oc": "Brunei Darussalam",
    "nl": "Brunei",
    "br": "Brunei"
  },
  "BO": {
    "en": "Bolivia",
    "fr": "Bolivie",
    "de": "Bolivien",
    "es": "Bolivia",
    "it": "Bolivia",
    "io": "crwdns11666:0crwdne11666:0",
    "oc": "Bolívia",
    "nl": "Bolivia",
    "br": "Bolivia"
  },
  "BR": {
    "en": "Brazil",
    "fr": "Brésil",
    "de": "Brasilien",
    "es": "Brasil",
    "it": "Brasile",
    "io": "crwdns11668:0crwdne11668:0",
    "oc": "Brasil",
    "nl": "Brazilië",
    "br": "Brazil"
  },
  "BS": {
    "en": "Bahamas",
    "fr": "Bahamas",
    "de": "Bahamas",
    "es": "Bahamas",
    "it": "Bahamas",
    "io": "crwdns11670:0crwdne11670:0",
    "oc": "Bahamas",
    "nl": "Bahama's",
    "br": "Bahamas"
  },
  "BT": {
    "en": "Bhutan",
    "fr": "Boutan",
    "de": "Bhutan",
    "es": "Bután",
    "it": "Boutan",
    "io": "crwdns11672:0crwdne11672:0",
    "oc": "Botan",
    "nl": "Bhutan",
    "br": "Bhoutan"
  },
  "BV": {
    "en": "Bouvet Island",
    "fr": "Bouvet Island",
    "de": "Bouvet-Insel",
    "es": "Isla Bouvet",
    "it": "Isola di Bouvet",
    "io": "crwdns11674:0crwdne11674:0",
    "oc": "Illa Bovet",
    "nl": "Bouvet",
    "br": "Enez Bouvet"
  },
  "BW": {
    "en": "Botswana",
    "fr": "Botswana",
    "de": "Botswana",
    "es": "Botswana",
    "it": "Botswana",
    "io": "crwdns11676:0crwdne11676:0",
    "oc": "Botswana",
    "nl": "Botswana",
    "br": "Botswana"
  },
  "BY": {
    "en": "Belarus",
    "fr": "Biélorussie",
    "de": "Weißrussland",
    "es": "Bielorrusia",
    "it": "Bielorussia",
    "io": "crwdns11678:0crwdne11678:0",
    "oc": "Bielorussia",
    "nl": "Wit-Rusland",
    "br": "Belarus"
  },
  "BZ": {
    "en": "Belize",
    "fr": "Bélize",
    "de": "Belize",
    "es": "Belice",
    "it": "Belize",
    "io": "crwdns11680:0crwdne11680:0",
    "oc": "Belize",
    "nl": "Belize",
    "br": "Belize"
  },
  "CA": {
    "en": "Canada",
    "fr": "Canada",
    "de": "Kanada",
    "es": "Canadá",
    "it": "Canada",
    "io": "crwdns11682:0crwdne11682:0",
    "oc": "Canadà",
    "nl": "Canada",
    "br": "Kanada"
  },
  "CC": {
    "en": "Cocos (Keeling) Islands",
    "fr": "Iles Coco",
    "de": "Cocos (Keeling) Islands",
    "es": "Islas Coco",
    "it": "Isole del Cocco",
    "io": "crwdns11684:0crwdne11684:0",
    "oc": "Illas Cocos",
    "nl": "Cocoseilanden (Keeling)",
    "br": "Inizi Kokoz (Keeling)"
  },
  "CD": {
    "en": "Democratic Republic of Congo",
    "fr": "République Démocratique du Congo",
    "de": "Demokratische Republik Kongo",
    "es": "República Democrática del Congo",
    "it": "Repubblica Democratica del Congo",
    "io": "crwdns11686:0crwdne11686:0",
    "oc": "Republica Democratica de Còngo",
    "nl": "Democratische Republiek Congo",
    "br": "Republik Demokratel Kongo"
  },
  "CF": {
    "en": "Central African Republic",
    "fr": "Républiqe d’Afrique Centrale",
    "de": "Zentralafrikanische Republik",
    "es": "Républiqe África central",
    "it": "Repubblica Centrafricana",
    "io": "crwdns11688:0crwdne11688:0",
    "oc": "Republica d'Africa Centrala",
    "nl": "Centraal-Afrikaanse Republiek",
    "br": "Republik Kreizafrikan"
  },
  "CG": {
    "en": "Congo",
    "fr": "Congo",
    "de": "Kongo",
    "es": "Congo",
    "it": "Congo",
    "io": "crwdns11690:0crwdne11690:0",
    "oc": "Còngo",
    "nl": "Congo",
    "br": "Kongo"
  },
  "CH": {
    "en": "Switzerland",
    "fr": "Suisse",
    "de": "Schweiz",
    "es": "Suiza",
    "it": "Svizzera",
    "io": "crwdns11692:0crwdne11692:0",
    "oc": "Soïssa",
    "nl": "Zwitserland",
    "br": "Suis"
  },
  "CI": {
    "en": "Cote D'Ivoire",
    "fr": "Côte d'Ivoire",
    "de": "Elfenbeinküste",
    "es": "Costa de Marfil",
    "it": "Costa d'Avorio",
    "io": "crwdns11694:0crwdne11694:0",
    "oc": "Còsta d'Evòri",
    "nl": "Ivoorkust",
    "br": "Aod an Olifant"
  },
  "CK": {
    "en": "Cook Islands",
    "fr": "Îles Cook",
    "de": "Cookinseln",
    "es": "Islas cook",
    "it": "Isole Cook",
    "io": "crwdns11696:0crwdne11696:0",
    "oc": "Illas Cook",
    "nl": "Cookeilanden",
    "br": "Inizi Cook"
  },
  "CL": {
    "en": "Chile",
    "fr": "Chili",
    "de": "Chile",
    "es": "Chile",
    "it": "Cile",
    "io": "crwdns11698:0crwdne11698:0",
    "oc": "Chile",
    "nl": "Chili",
    "br": "Chile"
  },
  "CM": {
    "en": "Cameroon",
    "fr": "Cameroun",
    "de": "Kamerun",
    "es": "Camerún",
    "it": "Camerun",
    "io": "crwdns11700:0crwdne11700:0",
    "oc": "Cameron",
    "nl": "Kameroen",
    "br": "Kameroun"
  },
  "CN": {
    "en": "China",
    "fr": "Chine",
    "de": "China",
    "es": "China",
    "it": "Cina",
    "io": "crwdns11702:0crwdne11702:0",
    "oc": "China",
    "nl": "China",
    "br": "Sina"
  },
  "CO": {
    "en": "Colombia",
    "fr": "Colombie",
    "de": "Kolumbien",
    "es": "Colombia",
    "it": "Colombia",
    "io": "crwdns11704:0crwdne11704:0",
    "oc": "Colómbia",
    "nl": "Colombia",
    "br": "Kolombia"
  },
  "CR": {
    "en": "Costa Rica",
    "fr": "Costa Rica",
    "de": "Costa Rica",
    "es": "Costa Rica",
    "it": "Costa Rica",
    "io": "crwdns11706:0crwdne11706:0",
    "oc": "Còsta Rica",
    "nl": "Costa Rica",
    "br": "Costa Rica"
  },
  "ME": {
    "en": "Montenegro",
    "fr": "Monténegro",
    "de": "Montenegro",
    "es": "Montenegro",
    "it": "Montenegro",
    "io": "crwdns11708:0crwdne11708:0",
    "oc": "Montenegro",
    "nl": "Montenegro",
    "br": "Montenegro"
  },
  "MF": {
    "en": "Saint-Martin ( French Part )",
    "fr": "Saint-Martin ( Partie Française )",
    "de": "Saint-Martin (Französisch Part)",
    "es": "San Martín (parte francesa)",
    "it": "Sint Maarten ( parte francese )",
    "io": "crwdns11710:0crwdne11710:0",
    "oc": "Sant Martin (partida francesa)",
    "nl": "Sint-Maarten (Frans deel)",
    "br": "Sant-Martin (Lodenn C'hall)"
  },
  "RS": {
    "en": "Serbia",
    "fr": "Serbie",
    "de": "Serbien",
    "es": "Serbia",
    "it": "Serbia",
    "io": "crwdns11712:0crwdne11712:0",
    "oc": "Serbia",
    "nl": "Servië",
    "br": "Serbia"
  },
  "CU": {
    "en": "Cuba",
    "fr": "Cuba",
    "de": "Kuba",
    "es": "Cuba",
    "it": "Cuba",
    "io": "crwdns11714:0crwdne11714:0",
    "oc": "Cuba",
    "nl": "Cuba",
    "br": "Kuba"
  },
  "CV": {
    "en": "Cape Verde",
    "fr": "Cap Vert",
    "de": "Kap Verde",
    "es": "cabo Verde",
    "it": "Capo Verde",
    "io": "crwdns11716:0crwdne11716:0",
    "oc": "Cap Verd",
    "nl": "Kaapverdië",
    "br": "Kab-Glas"
  },
  "CX": {
    "en": "Christmas Island",
    "fr": "Iles Christmas",
    "de": "Weihnachtsinsel",
    "es": "Isla de Navidad",
    "it": "Isole di Natale",
    "io": "crwdns11718:0crwdne11718:0",
    "oc": "Illa de Christmas",
    "nl": "Christmaseiland",
    "br": "Enez Christmas"
  },
  "CY": {
    "en": "Cyprus",
    "fr": "Chypre",
    "de": "Zypern",
    "es": "Chipre",
    "it": "Cipro",
    "io": "crwdns11720:0crwdne11720:0",
    "oc": "Chipre",
    "nl": "Cyprus",
    "br": "Kiprenez"
  },
  "CZ": {
    "en": "Czech Republic",
    "fr": "République Tchèque",
    "de": "Tschechische Republik",
    "es": "República Checa",
    "it": "Repubblica Ceca",
    "io": "crwdns11722:0crwdne11722:0",
    "oc": "Republica Chèca",
    "nl": "Tsjechië",
    "br": "Republik Tchek"
  },
  "DE": {
    "en": "Germany",
    "fr": "Allemagne",
    "de": "Deutschland",
    "es": "Alemania",
    "it": "Germania",
    "io": "crwdns11724:0crwdne11724:0",
    "oc": "Alemanha",
    "nl": "Duitsland",
    "br": "Alamagn"
  },
  "DJ": {
    "en": "Djibouti",
    "fr": "Djibouti",
    "de": "Dschibuti",
    "es": "Djibouti",
    "it": "Gibuti",
    "io": "crwdns11726:0crwdne11726:0",
    "oc": "Jiboti",
    "nl": "Djibouti",
    "br": "Djibouti"
  },
  "DK": {
    "en": "Denmark",
    "fr": "Danemark",
    "de": "Dänemark",
    "es": "Dinamarca",
    "it": "Danimarca",
    "io": "crwdns11728:0crwdne11728:0",
    "oc": "Danemarc",
    "nl": "Denemarken",
    "br": "Danmark"
  },
  "DM": {
    "en": "Dominica",
    "fr": "Dominique",
    "de": "Dominica",
    "es": "dominica",
    "it": "Dominica",
    "io": "crwdns11730:0crwdne11730:0",
    "oc": "Dominica",
    "nl": "Dominica",
    "br": "Dominika"
  },
  "DO": {
    "en": "Dominican Republic",
    "fr": "République Dominicaine",
    "de": "Dominikanische Republik",
    "es": "República Dominicana",
    "it": "Repubblica Dominicana",
    "io": "crwdns11732:0crwdne11732:0",
    "oc": "Republica Dominicana",
    "nl": "Dominicaanse Republiek",
    "br": "Republik Dominikan"
  },
  "DZ": {
    "en": "Algeria",
    "fr": "Algérie",
    "de": "Algerien",
    "es": "Argelia",
    "it": "Algeria",
    "io": "crwdns11734:0crwdne11734:0",
    "oc": "Argeria",
    "nl": "Algerije",
    "br": "Aljeria"
  },
  "EC": {
    "en": "Ecuador",
    "fr": "Equateur",
    "de": "Ecuador",
    "es": "Ecuador",
    "it": "Ecuador",
    "io": "crwdns11736:0crwdne11736:0",
    "oc": "Eqüator",
    "nl": "Ecuador",
    "br": "Ecuador"
  },
  "EE": {
    "en": "Estonia",
    "fr": "Estonie",
    "de": "Estland",
    "es": "Estonia",
    "it": "Estonia",
    "io": "crwdns11738:0crwdne11738:0",
    "oc": "Estonia",
    "nl": "Estland",
    "br": "Estonia"
  },
  "EG": {
    "en": "Egypt",
    "fr": "Egypte",
    "de": "Ägypten",
    "es": "Egipto",
    "it": "Egitto",
    "io": "crwdns11740:0crwdne11740:0",
    "oc": "Egipte",
    "nl": "Egypte",
    "br": "Egipt"
  },
  "EH": {
    "en": "Western Sahara",
    "fr": "Sahara occidental",
    "de": "Westsahara",
    "es": "Sahara Occidental",
    "it": "Sahara occidentale",
    "io": "crwdns11742:0crwdne11742:0",
    "oc": "Sahara Occidental",
    "nl": "Westelijke Sahara",
    "br": "Sahara ar C'hornog"
  },
  "ER": {
    "en": "Eritrea",
    "fr": "Erythrée",
    "de": "Eritrea",
    "es": "Eritrea",
    "it": "Eritrea",
    "io": "crwdns11744:0crwdne11744:0",
    "oc": "Eritrèa",
    "nl": "Eritrea",
    "br": "Eritrea"
  },
  "ES": {
    "en": "Spain",
    "fr": "Espagne",
    "de": "Spanien",
    "es": "España",
    "it": "Spagna",
    "io": "crwdns11746:0crwdne11746:0",
    "oc": "Espanha",
    "nl": "Spanje",
    "br": "Spagn"
  },
  "ET": {
    "en": "Ethiopia",
    "fr": "Ethiopie",
    "de": "Äthiopien",
    "es": "Etiopía",
    "it": "Etiopia",
    "io": "crwdns11748:0crwdne11748:0",
    "oc": "Etiopia",
    "nl": "Ethiopië",
    "br": "Etiopia"
  },
  "FI": {
    "en": "Finland",
    "fr": "Finlande",
    "de": "Finnland",
    "es": "Finlandia",
    "it": "Finlandia",
    "io": "crwdns11750:0crwdne11750:0",
    "oc": "Finlàndia",
    "nl": "Finland",
    "br": "Finland"
  },
  "FJ": {
    "en": "Fiji",
    "fr": "Fiji",
    "de": "Fidschi",
    "es": "Fiji",
    "it": "Figi",
    "io": "crwdns11752:0crwdne11752:0",
    "oc": "Fiji",
    "nl": "Fiji",
    "br": "Fidji"
  },
  "FK": {
    "en": "Falkland Islands (Malvinas)",
    "fr": "Iles Malouines",
    "de": "Falklandinseln (Malvinas)",
    "es": "islas Malvinas",
    "it": "Isole Falkland",
    "io": "crwdns11754:0crwdne11754:0",
    "oc": "Illas Falklands (Malvinas)",
    "nl": "Falklandeilanden (Malvinas)",
    "br": "Inizi Falkland (Malvinas)"
  },
  "FM": {
    "en": "(Micronesia), Federated States of",
    "fr": "Micronésie",
    "de": "(Mikronesien), den Föderierten Staaten von",
    "es": "micronesia",
    "it": "Micronesia",
    "io": "crwdns11756:0crwdne11756:0",
    "oc": "(Micronesia), Estats Federats de",
    "nl": "(Micronesië), Federale Staten van",
    "br": "(Mikronezia), Stadoù Kevredet"
  },
  "FO": {
    "en": "Faroe Islands",
    "fr": "Iles Féroée",
    "de": "Färöer Inseln",
    "es": "Islas Féroée",
    "it": "Isole Faroe",
    "io": "crwdns11758:0crwdne11758:0",
    "oc": "Illas Feròe",
    "nl": "Faeröer",
    "br": "Inizi Faero"
  },
  "FR": {
    "en": "France (Metropolitan)",
    "fr": "France (Métropole)",
    "de": "Frankreich (Metropolitan)",
    "es": "Francia (Metropolitana)",
    "it": "Francia (continente)",
    "io": "crwdns11760:0crwdne11760:0",
    "oc": "França (Metropolitana)",
    "nl": "Frankrijk (Europees)",
    "br": "Frañs (Metropol)"
  },
  "GA": {
    "en": "Gabon",
    "fr": "Gabon",
    "de": "Gabun",
    "es": "Gabón",
    "it": "Gabon",
    "io": "crwdns11762:0crwdne11762:0",
    "oc": "Gabon",
    "nl": "Gabon",
    "br": "Gabon"
  },
  "GB": {
    "en": "United Kingdom",
    "fr": "Royaume Uni",
    "de": "Großbritannien",
    "es": "Reino Unido",
    "it": "Regno Unito",
    "io": "crwdns11764:0crwdne11764:0",
    "oc": "Reialme Unit",
    "nl": "Verenigd Koninkrijk",
    "br": "Rouantelezh-Unanet"
  },
  "GD": {
    "en": "Grenada",
    "fr": "Grenade",
    "de": "Grenada",
    "es": "granada",
    "it": "Granada",
    "io": "crwdns11766:0crwdne11766:0",
    "oc": "Grenada",
    "nl": "Grenada",
    "br": "Grenada"
  },
  "GE": {
    "en": "Georgia",
    "fr": "Géorgie",
    "de": "Georgia",
    "es": "Georgia",
    "it": "Georgia",
    "io": "crwdns11768:0crwdne11768:0",
    "oc": "Georgia",
    "nl": "Georgië",
    "br": "Jorjia"
  },
  "GG": {
    "en": "Guernsey",
    "fr": "Guernesey",
    "de": "Guernsey",
    "es": "Guernsey",
    "it": "Guernsey",
    "io": "crwdns35389:0crwdne35389:0",
    "oc": "Guernsey"
  },
  "GF": {
    "en": "French Guiana",
    "fr": "Guyane Française",
    "de": "Französisch-Guayana",
    "es": "Guayana francés",
    "it": "Guyana Francese",
    "io": "crwdns11770:0crwdne11770:0",
    "oc": "Guiana Francesa",
    "nl": "Frans-Guyana",
    "br": "Gwiana C'hall"
  },
  "GH": {
    "en": "Ghana",
    "fr": "Ghana",
    "de": "Ghana",
    "es": "Ghana",
    "it": "Ghana",
    "io": "crwdns11772:0crwdne11772:0",
    "oc": "Ghana",
    "nl": "Ghana",
    "br": "Ghana"
  },
  "GI": {
    "en": "Gibraltar",
    "fr": "Gibraltar",
    "de": "Gibraltar",
    "es": "Gibraltar",
    "it": "Gibilterra",
    "io": "crwdns11774:0crwdne11774:0",
    "oc": "Gibartar",
    "nl": "Gibraltar",
    "br": "Jibraltar"
  },
  "GL": {
    "en": "Greenland",
    "fr": "Groënland",
    "de": "Grönland",
    "es": "Groenlandia",
    "it": "Groenlandia",
    "io": "crwdns11776:0crwdne11776:0",
    "oc": "Groenlàndia",
    "nl": "Groenland",
    "br": "Greunland"
  },
  "GM": {
    "en": "Gambia",
    "fr": "Gambie",
    "de": "Gambia",
    "es": "Gambia",
    "it": "Il Gambia",
    "io": "crwdns11778:0crwdne11778:0",
    "oc": "Gàmbia",
    "nl": "Gambia",
    "br": "Gambia"
  },
  "GN": {
    "en": "Guinea",
    "fr": "Guinée",
    "de": "Guinea",
    "es": "Guinea",
    "it": "Guinea",
    "io": "crwdns11780:0crwdne11780:0",
    "oc": "Guinèa",
    "nl": "Guinee",
    "br": "Ginea"
  },
  "GP": {
    "en": "Guadeloupe",
    "fr": "Guadeloupe",
    "de": "Guadeloupe",
    "es": "Guadalupe",
    "it": "Guadalupa",
    "io": "crwdns11782:0crwdne11782:0",
    "oc": "Guadalope",
    "nl": "Guadeloupe",
    "br": "Gwadeloup"
  },
  "GQ": {
    "en": "Equatorial Guinea",
    "fr": "Guinée Equatoriale",
    "de": "Äquatorialguinea",
    "es": "Guinea Ecuatorial",
    "it": "Guinea Equatoriale",
    "io": "crwdns11784:0crwdne11784:0",
    "oc": "Guinèa Eqüatoriala",
    "nl": "Equatoriaal-Guinea",
    "br": "Ginea ar C'heheder"
  },
  "GR": {
    "en": "Greece",
    "fr": "Grèce",
    "de": "Griechenland",
    "es": "Grecia",
    "it": "Grecia",
    "io": "crwdns11786:0crwdne11786:0",
    "oc": "Grècia",
    "nl": "Griekenland",
    "br": "Gres"
  },
  "GS": {
    "en": "South Georgia and the South Sandwich Islands",
    "fr": "Géorgie du Sud-et-les Îles Sandwich du Sud",
    "de": "Süd-Georgien und die südlichen Sandwich-Inseln",
    "es": "Georgia del Sur y las Islas Sandwich del Sur",
    "it": "Georgia del Sud e Isole Sandwich del Sud",
    "io": "crwdns11788:0crwdne11788:0",
    "oc": "Illas Georgia del Sud e Sandwich del Sud",
    "nl": "Zuid-Georgia en de Zuidelijke Sandwicheilanden",
    "br": "Jorjia ar Su hag Inizi Sandwich ar Su"
  },
  "GT": {
    "en": "Guatemala",
    "fr": "Guatemala",
    "de": "Guatemala",
    "es": "Guatemala",
    "it": "Guatemala",
    "io": "crwdns11790:0crwdne11790:0",
    "oc": "Guatemala",
    "nl": "Guatemala",
    "br": "Guatemala"
  },
  "GU": {
    "en": "Guam",
    "fr": "Guam",
    "de": "Guam",
    "es": "Guam",
    "it": "Guam",
    "io": "crwdns11792:0crwdne11792:0",
    "oc": "Guam",
    "nl": "Guam",
    "br": "Guam"
  },
  "GW": {
    "en": "Guinea-Bissau",
    "fr": "Guinée-Bissau",
    "de": "Guinea-Bissau",
    "es": "Guinea-Bissau",
    "it": "Guinea-Bissau",
    "io": "crwdns11794:0crwdne11794:0",
    "oc": "Guinèa Bissau",
    "nl": "Guinee-Bissau",
    "br": "Ginea-Bissau"
  },
  "GY": {
    "en": "Guyana",
    "fr": "Guyane",
    "de": "Guyana",
    "es": "Guayana",
    "it": "Guyana Francese",
    "io": "crwdns11796:0crwdne11796:0",
    "oc": "Guyana",
    "nl": "Guyana",
    "br": "Guyana"
  },
  "HK": {
    "en": "Hong Kong",
    "fr": "Hong Kong",
    "de": "Hongkong",
    "es": "Hong Kong",
    "it": "Hong Kong",
    "io": "crwdns11798:0crwdne11798:0",
    "oc": "Hong Kong",
    "nl": "Hongkong",
    "br": "Hong Kong"
  },
  "HM": {
    "en": "Heard Island and Mcdonald Islands",
    "fr": "Iles Heard et Mac Donald",
    "de": "Heard und McDonald-Inseln",
    "es": "Islas Heard y MacDonald",
    "it": "Isole Heard e McDonald",
    "io": "crwdns11800:0crwdne11800:0",
    "oc": "Illa Heard e Illas McDonald",
    "nl": "Heard en McDonaldeilanden",
    "br": "Enez Heard hag Inizi McDonald"
  },
  "HN": {
    "en": "Honduras",
    "fr": "Honduras",
    "de": "Honduras",
    "es": "Honduras",
    "it": "Honduras",
    "io": "crwdns11802:0crwdne11802:0",
    "oc": "Onduras",
    "nl": "Honduras",
    "br": "Honduras"
  },
  "HR": {
    "en": "Croatia",
    "fr": "Croatie",
    "de": "Kroatien",
    "es": "Croacia",
    "it": "Croazia",
    "io": "crwdns11804:0crwdne11804:0",
    "oc": "Croàcia",
    "nl": "Kroatië",
    "br": "Kroatia"
  },
  "HT": {
    "en": "Haiti",
    "fr": "Haïti",
    "de": "Haiti",
    "es": "Haití",
    "it": "Haiti",
    "io": "crwdns11806:0crwdne11806:0",
    "oc": "Haití",
    "nl": "Haïti",
    "br": "Haiti"
  },
  "HU": {
    "en": "Hungary",
    "fr": "Hongrie",
    "de": "Ungarn",
    "es": "Hungría",
    "it": "Ungheria",
    "io": "crwdns11808:0crwdne11808:0",
    "oc": "Ongria",
    "nl": "Hongarije",
    "br": "Hungaria"
  },
  "ID": {
    "en": "Indonesia",
    "fr": "Indonésie",
    "de": "Indonesien",
    "es": "Indonesia",
    "it": "Indonesia",
    "io": "crwdns11810:0crwdne11810:0",
    "oc": "Indonesia",
    "nl": "Indonesië",
    "br": "Indonezia"
  },
  "IE": {
    "en": "Ireland",
    "fr": "Irlande",
    "de": "Irland",
    "es": "Irlanda",
    "it": "Irlanda",
    "io": "crwdns11812:0crwdne11812:0",
    "oc": "Irlanda",
    "nl": "Ierland",
    "br": "Iwerzhon"
  },
  "IL": {
    "en": "Israel",
    "fr": "Israël",
    "de": "Israel",
    "es": "Israel",
    "it": "Israele",
    "io": "crwdns11814:0crwdne11814:0",
    "oc": "Israèl",
    "nl": "Israël",
    "br": "Israel"
  },
  "IN": {
    "en": "India",
    "fr": "Inde",
    "de": "Indien",
    "es": "India",
    "it": "India",
    "io": "crwdns11816:0crwdne11816:0",
    "oc": "Índia",
    "nl": "India",
    "br": "India"
  },
  "IO": {
    "en": "British Indian Ocean Territory",
    "fr": "Territories britanniques dans l'océan indien",
    "de": "Britisches Territorium des Indischen Ozeans",
    "it": "British Indian Ocean Territory",
    "io": "crwdns11818:0crwdne11818:0",
    "oc": "Territòri britanic de l'Ocean indian",
    "es": "Territorios Británicos del Océano Índico",
    "nl": "Brits Indische Oceaanterritorium",
    "br": "Tiriad Meurvor Indez Breizh-Veur"
  },
  "IQ": {
    "en": "Iraq",
    "fr": "Irak",
    "de": "Irak",
    "es": "Irak",
    "it": "Iraq",
    "io": "crwdns11820:0crwdne11820:0",
    "oc": "Iraq",
    "nl": "Irak",
    "br": "Irak"
  },
  "IR": {
    "en": "Iran",
    "fr": "Iran",
    "de": "Ich rannte",
    "es": "Irán",
    "it": "Iran",
    "io": "crwdns11822:0crwdne11822:0",
    "oc": "Iran",
    "nl": "Iran",
    "br": "Iran"
  },
  "IS": {
    "en": "Iceland",
    "fr": "Islande",
    "de": "Island",
    "es": "Islandia",
    "it": "Islanda",
    "io": "crwdns11824:0crwdne11824:0",
    "oc": "Islàndia",
    "nl": "IJsland",
    "br": "Island"
  },
  "IT": {
    "en": "Italy",
    "fr": "Italie",
    "de": "Italien",
    "es": "Italia",
    "it": "Italia",
    "io": "crwdns11826:0crwdne11826:0",
    "oc": "Itàlia",
    "nl": "Italië",
    "br": "Italia"
  },
  "JE": {
    "en": "Jersey",
    "fr": "Jersey",
    "de": "Jersey",
    "es": "Jersey",
    "it": "Jersey",
    "io": "crwdns35391:0crwdne35391:0",
    "oc": "Jersey"
  },
  "JM": {
    "en": "Jamaica",
    "fr": "Jamaïque",
    "de": "Jamaika",
    "es": "Jamaica",
    "it": "Giamaica",
    "io": "crwdns11828:0crwdne11828:0",
    "oc": "Jamaica",
    "nl": "Jamaica",
    "br": "Jamaika"
  },
  "JO": {
    "en": "Jordan",
    "fr": "Jordanie",
    "de": "Jordan",
    "es": "Jordania",
    "it": "Giordania",
    "io": "crwdns11830:0crwdne11830:0",
    "oc": "Jordania",
    "nl": "Jordanië",
    "br": "Jordania"
  },
  "JP": {
    "en": "Japan",
    "fr": "Japon",
    "de": "Japan",
    "es": "Japón",
    "it": "Giappone",
    "io": "crwdns11832:0crwdne11832:0",
    "oc": "Japon",
    "nl": "Japan",
    "br": "Japan"
  },
  "KE": {
    "en": "Kenya",
    "fr": "Kénya",
    "de": "Kenia",
    "es": "Kenia",
    "it": "Kenya",
    "io": "crwdns11834:0crwdne11834:0",
    "oc": "Kenya",
    "nl": "Kenia",
    "br": "Kenya"
  },
  "KG": {
    "en": "Kyrgyzstan",
    "fr": "Kirghizistan",
    "de": "Kirgisistan",
    "es": "Kirguizistán",
    "it": "Kirghizistan",
    "io": "crwdns11836:0crwdne11836:0",
    "oc": "Quirguizstan",
    "nl": "Kirgizië",
    "br": "Kirgizstan"
  },
  "KH": {
    "en": "Cambodia",
    "fr": "Cambodge",
    "de": "Kambodscha",
    "es": "Camboya",
    "it": "Cambogia",
    "io": "crwdns11838:0crwdne11838:0",
    "oc": "Cambòtja",
    "nl": "Cambodja",
    "br": "Kambodja"
  },
  "KI": {
    "en": "Kiribati",
    "fr": "Kiribati",
    "de": "Kiribati",
    "es": "Kiribati",
    "it": "Kiribati",
    "io": "crwdns11840:0crwdne11840:0",
    "oc": "Kiribati",
    "nl": "Kiribati",
    "br": "Kiribati"
  },
  "KM": {
    "en": "Comoros",
    "fr": "Comores",
    "de": "Komoren",
    "es": "Comorres",
    "it": "Comorres",
    "io": "crwdns11842:0crwdne11842:0",
    "oc": "Comòras",
    "nl": "Comoren",
    "br": "Komorez"
  },
  "KN": {
    "en": "Saint Kitts and Nevis",
    "fr": "Saint Kitts et Nevis",
    "de": "St. Kitts und Nevis",
    "es": "Saint Kitts y Nevis",
    "it": "Saint Kitts e Nevis",
    "io": "crwdns11844:0crwdne11844:0",
    "oc": "Sant Kitts e Nevis",
    "nl": "Saint Kitts en Nevis",
    "br": "Sant Kitts ha Nevis"
  },
  "KP": {
    "en": "North Korea",
    "fr": "Corée du Nord",
    "de": "Nord Korea",
    "es": "Corea del Norte",
    "it": "Corea del Nord",
    "io": "crwdns11846:0crwdne11846:0",
    "oc": "Corèa del Nòrd",
    "nl": "Noord-Korea",
    "br": "Korea an Norzh"
  },
  "KR": {
    "en": "South Korea",
    "fr": "Corée du Sud",
    "de": "Südkorea",
    "es": "Corea del Sur",
    "it": "Corea del Sud",
    "io": "crwdns11848:0crwdne11848:0",
    "oc": "Corèa del Sud",
    "nl": "Zuid-Korea",
    "br": "Korea ar Su"
  },
  "KW": {
    "en": "Kuwait",
    "fr": "Koweït",
    "de": "Kuwait",
    "es": "Kuwait",
    "it": "Kuwait",
    "io": "crwdns11850:0crwdne11850:0",
    "oc": "Kowait",
    "nl": "Koeweit",
    "br": "Koweit"
  },
  "KY": {
    "en": "Cayman Islands",
    "fr": "Îles Caïman",
    "de": "Cayman Inseln",
    "es": "Islas Caimán",
    "it": "Isole Cayman",
    "io": "crwdns11852:0crwdne11852:0",
    "oc": "Illas Caiman",
    "nl": "Kaaimaneilanden",
    "br": "Inizi Cayman"
  },
  "KZ": {
    "en": "Kazakhstan",
    "fr": "Kazakhstan",
    "de": "Kasachstan",
    "es": "Kazajstán",
    "it": "Kazakistan",
    "io": "crwdns11854:0crwdne11854:0",
    "oc": "Cazacstan",
    "nl": "Kazachstan",
    "br": "Kazakstan"
  },
  "LA": {
    "en": "Lao People's Democratic Republic",
    "fr": "Laos",
    "de": "Lao Demokratischen Volksrepublik",
    "es": "Laos",
    "it": "Laos",
    "io": "crwdns11856:0crwdne11856:0",
    "oc": "Laos",
    "nl": "Laos",
    "br": "Laos"
  },
  "LB": {
    "en": "Lebanon",
    "fr": "Liban",
    "de": "Libanon",
    "es": "Líbano",
    "it": "Libano",
    "io": "crwdns11858:0crwdne11858:0",
    "oc": "Liban",
    "nl": "Libanon",
    "br": "Liban"
  },
  "LC": {
    "en": "Saint Lucia",
    "fr": "Sainte Lucie",
    "de": "St. Lucia",
    "es": "Santa Lucía",
    "it": "Santa Lucia",
    "io": "crwdns11860:0crwdne11860:0",
    "oc": "Santa Lúcia",
    "nl": "Saint Lucia",
    "br": "Sant Lucia"
  },
  "LI": {
    "en": "Liechtenstein",
    "fr": "Liechtenstein",
    "de": "Liechtenstein",
    "es": "Liechtenstein",
    "it": "Liechtenstein",
    "io": "crwdns11862:0crwdne11862:0",
    "oc": "Liechtenstein",
    "nl": "Liechtenstein",
    "br": "Liechtenstein"
  },
  "LK": {
    "en": "Sri Lanka",
    "fr": "Sri Lanka",
    "de": "Sri Lanka",
    "es": "Sri Lanka",
    "it": "Sri Lanka",
    "io": "crwdns11864:0crwdne11864:0",
    "oc": "Sri Lanka",
    "nl": "Sri Lanka",
    "br": "Sri Lanka"
  },
  "LR": {
    "en": "Liberia",
    "fr": "Liberia",
    "de": "Liberia",
    "es": "Liberia",
    "it": "Liberia",
    "io": "crwdns11866:0crwdne11866:0",
    "oc": "Libèria",
    "nl": "Liberia",
    "br": "Liberia"
  },
  "LS": {
    "en": "Lesotho",
    "fr": "Lesotho",
    "de": "Lesotho",
    "es": "Lesoto",
    "it": "Lesotho",
    "io": "crwdns11868:0crwdne11868:0",
    "oc": "Lesotho",
    "nl": "Lesotho",
    "br": "Lesotho"
  },
  "LT": {
    "en": "Lithuania",
    "fr": "Lituanie",
    "de": "Litauen",
    "es": "Lituania",
    "it": "Lituania",
    "io": "crwdns11870:0crwdne11870:0",
    "oc": "Lituània",
    "nl": "Litouwen",
    "br": "Lituania"
  },
  "LU": {
    "en": "Luxembourg",
    "fr": "Luxembourg",
    "de": "Luxemburg",
    "es": "Luxemburgo",
    "it": "Lussemburgo",
    "io": "crwdns11872:0crwdne11872:0",
    "oc": "Luxemborg",
    "nl": "Luxemburg",
    "br": "Luksembourg"
  },
  "LV": {
    "en": "Latvia",
    "fr": "Lettonie",
    "de": "Lettland",
    "es": "Letonia",
    "it": "Lettonia",
    "io": "crwdns11874:0crwdne11874:0",
    "oc": "Letònia",
    "nl": "Letland",
    "br": "Latvia"
  },
  "LY": {
    "en": "Libyan Arab Jamahiriya",
    "fr": "Libye",
    "de": "Libysch-Arabische Dschamahirija",
    "es": "Libia",
    "it": "Libia",
    "io": "crwdns11876:0crwdne11876:0",
    "oc": "Libia",
    "nl": "Libië",
    "br": "Libia"
  },
  "MA": {
    "en": "Morocco",
    "fr": "Maroc",
    "de": "Marokko",
    "es": "Marruecos",
    "it": "Marocco",
    "io": "crwdns11878:0crwdne11878:0",
    "oc": "Marròc",
    "nl": "Marokko",
    "br": "Maroko"
  },
  "MC": {
    "en": "Monaco",
    "fr": "Monaco",
    "de": "Monaco",
    "es": "Mónaco",
    "it": "Monaco",
    "io": "crwdns11880:0crwdne11880:0",
    "oc": "Mónegue",
    "nl": "Monaco",
    "br": "Monako"
  },
  "MD": {
    "en": "(Moldova), Republic of",
    "fr": "Moldavie",
    "de": "(Moldawien), Republik",
    "es": "Moldavia",
    "it": "Moldavia",
    "io": "crwdns11882:0crwdne11882:0",
    "oc": "Moldàvia",
    "nl": "(Moldavië), Republiek",
    "br": "(Moldova), Republik"
  },
  "MG": {
    "en": "Madagascar",
    "fr": "Madagascar",
    "de": "Madagaskar",
    "es": "Madagascar",
    "it": "Madagascar",
    "io": "crwdns11884:0crwdne11884:0",
    "oc": "Madagascar",
    "nl": "Madagaskar",
    "br": "Madagaskar"
  },
  "MH": {
    "en": "Marshall Islands",
    "fr": "Iles Marshall",
    "de": "Marshallinseln",
    "es": "Islas Marshall",
    "it": "Isole Marshall",
    "io": "crwdns11886:0crwdne11886:0",
    "oc": "Illas Marshall",
    "nl": "Marshalleilanden",
    "br": "Inizi Marshall"
  },
  "MK": {
    "en": "Macedonia",
    "fr": "Macédoine",
    "de": "Mazedonien",
    "es": "macedonia",
    "it": "Macedonia",
    "io": "crwdns11888:0crwdne11888:0",
    "oc": "Macedònia",
    "nl": "Noord-Macedonië",
    "br": "Makedonia"
  },
  "ML": {
    "en": "Mali",
    "fr": "Mali",
    "de": "Mali",
    "es": "mali",
    "it": "Mali",
    "io": "crwdns11890:0crwdne11890:0",
    "oc": "Mali",
    "nl": "Mali",
    "br": "Mali"
  },
  "MM": {
    "en": "Myanmar",
    "fr": "Birmanie",
    "de": "Myanmar",
    "es": "Birmania",
    "it": "Birmania",
    "io": "crwdns11892:0crwdne11892:0",
    "oc": "Myanmar",
    "nl": "Myanmar",
    "br": "Myanmar"
  },
  "MN": {
    "en": "Mongolia",
    "fr": "Mongolie",
    "de": "Mongolei",
    "es": "Mongolia",
    "it": "Mongolia",
    "io": "crwdns11894:0crwdne11894:0",
    "oc": "Mongolia",
    "nl": "Mongolië",
    "br": "Mongolia"
  },
  "MO": {
    "en": "Macao",
    "fr": "Macao",
    "de": "Macao",
    "es": "macao",
    "it": "Macao",
    "io": "crwdns11896:0crwdne11896:0",
    "oc": "Macau",
    "nl": "Macau",
    "br": "Macau"
  },
  "MP": {
    "en": "Northern Mariana Islands",
    "fr": "Îles Mariannes du Nord",
    "de": "Nördliche Marianneninseln",
    "es": "Islas Marianas del Norte",
    "it": "Isole Marianne Settentrionali",
    "io": "crwdns11898:0crwdne11898:0",
    "oc": "Illas Marianna del Nòrd",
    "nl": "Noordelijke Marianen",
    "br": "Inizi Mariana an Norzh"
  },
  "MQ": {
    "en": "Martinique",
    "fr": "Martinique",
    "de": "Martinique",
    "es": "Martinica",
    "it": "Martinica",
    "io": "crwdns11900:0crwdne11900:0",
    "oc": "Martinica",
    "nl": "Martinique",
    "br": "Martinik"
  },
  "MR": {
    "en": "Mauritania",
    "fr": "Mauritanie",
    "de": "Mauretanien",
    "es": "Mauritania",
    "it": "Mauritania",
    "io": "crwdns11902:0crwdne11902:0",
    "oc": "Mauritània",
    "nl": "Mauritanië",
    "br": "Maouritania"
  },
  "MS": {
    "en": "Montserrat",
    "fr": "Montserrat",
    "de": "Montserrat",
    "it": "Montserrat",
    "io": "crwdns11904:0crwdne11904:0",
    "oc": "Montserrat",
    "es": "Montserrat",
    "nl": "Montserrat",
    "br": "Montserrat"
  },
  "MT": {
    "en": "Malta",
    "fr": "Malte",
    "de": "Malta",
    "es": "Malta",
    "it": "Malta",
    "io": "crwdns11906:0crwdne11906:0",
    "oc": "Malta",
    "nl": "Malta",
    "br": "Malta"
  },
  "MU": {
    "en": "Mauritius",
    "fr": "Ile Maurice",
    "de": "Mauritius",
    "es": "Isla Mauricio",
    "it": "Mauritius",
    "io": "crwdns11908:0crwdne11908:0",
    "oc": "Maurici",
    "nl": "Mauritius",
    "br": "Moris"
  },
  "MV": {
    "en": "Maldives",
    "fr": "Maldives",
    "de": "Malediven",
    "es": "Maldivas",
    "it": "Maldive",
    "io": "crwdns11910:0crwdne11910:0",
    "oc": "Maldivas",
    "nl": "Maldiven",
    "br": "Maldivez"
  },
  "MW": {
    "en": "Malawi",
    "fr": "Malawi",
    "de": "Malawi",
    "es": "Malawi",
    "it": "Malawi",
    "io": "crwdns11912:0crwdne11912:0",
    "oc": "Malawi",
    "nl": "Malawi",
    "br": "Malawi"
  },
  "MX": {
    "en": "Mexico",
    "fr": "Mexique",
    "de": "Mexiko",
    "es": "México",
    "it": "Messico",
    "io": "crwdns11914:0crwdne11914:0",
    "oc": "Mexic",
    "nl": "Mexico",
    "br": "Mec'hiko"
  },
  "MY": {
    "en": "Malaysia",
    "fr": "Malaisie",
    "de": "Malaysia",
    "es": "Malasia",
    "it": "Malesia",
    "io": "crwdns11916:0crwdne11916:0",
    "oc": "Malàisia",
    "nl": "Maleisië",
    "br": "Malaysia"
  },
  "MZ": {
    "en": "Mozambique",
    "fr": "Mozambique",
    "de": "Mosambik",
    "es": "Mozambique",
    "it": "Mozambico",
    "io": "crwdns11918:0crwdne11918:0",
    "oc": "Moçambic",
    "nl": "Mozambique",
    "br": "Mozambik"
  },
  "NA": {
    "en": "Namibia",
    "fr": "Namibie",
    "de": "Namibia",
    "es": "Namibia",
    "it": "Namibia",
    "io": "crwdns11920:0crwdne11920:0",
    "oc": "Namibia",
    "nl": "Namibië",
    "br": "Namibia"
  },
  "NC": {
    "en": "New Caledonia",
    "fr": "Nouvelle Calédonie",
    "de": "Neu-Kaledonien",
    "es": "Nueva Caledonia",
    "it": "Nuova Caledonia",
    "io": "crwdns11922:0crwdne11922:0",
    "oc": "Nòva Caledònia",
    "nl": "Nieuw-Caledonië",
    "br": "Kaledonia Nevez"
  },
  "NE": {
    "en": "Niger",
    "fr": "Niger",
    "de": "Niger",
    "es": "Níger",
    "it": "Niger",
    "io": "crwdns11924:0crwdne11924:0",
    "oc": "Nigèr",
    "nl": "Niger",
    "br": "Niger"
  },
  "NF": {
    "en": "Norfolk Island",
    "fr": "Île Norfolk",
    "de": "Norfolkinsel",
    "es": "isla Norfolk",
    "it": "Isola di Norfolk",
    "io": "crwdns11926:0crwdne11926:0",
    "oc": "Illa Norfolk",
    "nl": "Norfolk",
    "br": "Enez Norfolk"
  },
  "NG": {
    "en": "Nigeria",
    "fr": "Nigeria",
    "de": "Nigeria",
    "es": "Nigeria",
    "it": "Nigeria",
    "io": "crwdns11928:0crwdne11928:0",
    "oc": "Nigèria",
    "nl": "Nigeria",
    "br": "Nigeria"
  },
  "NI": {
    "en": "Nicaragua",
    "fr": "Nicaragua",
    "de": "Nicaragua",
    "es": "Nicaragua",
    "it": "Nicaragua",
    "io": "crwdns11930:0crwdne11930:0",
    "oc": "Nicaragua",
    "nl": "Nicaragua",
    "br": "Nicaragua"
  },
  "NL": {
    "en": "Netherlands",
    "fr": "Pays-Bas",
    "de": "Niederlande",
    "es": "Países Bajos",
    "it": "Paesi Bassi",
    "io": "crwdns11932:0crwdne11932:0",
    "oc": "Païses Basses",
    "nl": "Nederland",
    "br": "Izelvroioù"
  },
  "NO": {
    "en": "Norway",
    "fr": "Norvège",
    "de": "Norwegen",
    "es": "Noruega",
    "it": "Norvegia",
    "io": "crwdns11934:0crwdne11934:0",
    "oc": "Norvègia",
    "nl": "Noorwegen",
    "br": "Norvegia"
  },
  "NP": {
    "en": "Nepal",
    "fr": "Népal",
    "de": "Nepal",
    "es": "Nepal",
    "it": "Nepal",
    "io": "crwdns11936:0crwdne11936:0",
    "oc": "Nepal",
    "nl": "Nepal",
    "br": "Nepal"
  },
  "NR": {
    "en": "Nauru",
    "fr": "Nauru",
    "de": "Nauru",
    "es": "Nauru",
    "it": "Nauru",
    "io": "crwdns11938:0crwdne11938:0",
    "oc": "Nauru",
    "nl": "Nauru",
    "br": "Nauru"
  },
  "NU": {
    "en": "Niue",
    "fr": "Niue",
    "de": "Niue",
    "es": "Niue",
    "it": "Niue",
    "io": "crwdns11940:0crwdne11940:0",
    "oc": "Niue",
    "nl": "Niue",
    "br": "Niue"
  },
  "NZ": {
    "en": "New Zealand",
    "fr": "Nouvelle Zélande",
    "de": "Neuseeland",
    "es": "Nueva Zelanda",
    "it": "Nuova Zelanda",
    "io": "crwdns11942:0crwdne11942:0",
    "oc": "Nòva Zelanda",
    "nl": "Nieuw-Zeeland",
    "br": "Zeland-Nevez"
  },
  "OM": {
    "en": "Oman",
    "fr": "Oman",
    "de": "Oman",
    "es": "Omán",
    "it": "Oman",
    "io": "crwdns11944:0crwdne11944:0",
    "oc": "Oman",
    "nl": "Oman",
    "br": "Oman"
  },
  "PA": {
    "en": "Panama",
    "fr": "Panama",
    "de": "Panama",
    "es": "Panamá",
    "it": "Panama",
    "io": "crwdns11946:0crwdne11946:0",
    "oc": "Panamà",
    "nl": "Panama",
    "br": "Panama"
  },
  "PE": {
    "en": "Peru",
    "fr": "Pérou",
    "de": "Peru",
    "es": "Perú",
    "it": "Perù",
    "io": "crwdns11948:0crwdne11948:0",
    "oc": "Peró",
    "nl": "Peru",
    "br": "Perou"
  },
  "PF": {
    "en": "French Polynesia",
    "fr": "Polynésie Française",
    "de": "Französisch Polynesien",
    "es": "Polinesia francesa",
    "it": "Polinesia Francese",
    "io": "crwdns11950:0crwdne11950:0",
    "oc": "Polinesia Francesa",
    "nl": "Frans-Polynesië",
    "br": "Polinezia C'hall"
  },
  "PG": {
    "en": "Papua New Guinea",
    "fr": "Papouasie Nouvelle Guinée",
    "de": "Papua Neu-Guinea",
    "es": "Papua Nueva Guinea",
    "it": "Papua Nuova Guinea",
    "io": "crwdns11952:0crwdne11952:0",
    "oc": "Papoa Nòva Guinèa",
    "nl": "Papoea-Nieuw-Guinea",
    "br": "Papoua Ginea-Nevez"
  },
  "PH": {
    "en": "Philippines",
    "fr": "Philippines",
    "de": "Philippinen",
    "es": "filipinas",
    "it": "Filippine",
    "io": "crwdns11954:0crwdne11954:0",
    "oc": "Filipinas",
    "nl": "Filipijnen",
    "br": "Filipinez"
  },
  "PK": {
    "en": "Pakistan",
    "fr": "Pakistan",
    "de": "Pakistan",
    "es": "Pakistán",
    "it": "Pakistan",
    "io": "crwdns11956:0crwdne11956:0",
    "oc": "Paquistan",
    "nl": "Pakistan",
    "br": "Pakistan"
  },
  "PL": {
    "en": "Poland",
    "fr": "Pologne",
    "de": "Polen",
    "es": "Polonia",
    "it": "Polonia",
    "io": "crwdns11958:0crwdne11958:0",
    "oc": "Polonha",
    "nl": "Polen",
    "br": "Polonia"
  },
  "PM": {
    "en": "Saint Pierre and Miquelon",
    "fr": "Saint Pierre et Miquelon",
    "de": "Saint-Pierre und Miquelon",
    "es": "San Pedro y Miquelón",
    "it": "San Pietro e Miquelon",
    "io": "crwdns11960:0crwdne11960:0",
    "oc": "Sant Pèire e Miquelon",
    "nl": "Saint-Pierre en Miquelon",
    "br": "Sant-Pêr-ha-Mikelon"
  },
  "PN": {
    "en": "Pitcairn",
    "fr": "Pitcairn",
    "de": "Pitcairn",
    "es": "Pitcairn",
    "it": "Pitcairn",
    "io": "crwdns11962:0crwdne11962:0",
    "oc": "Pitcairn",
    "nl": "Pitcairn",
    "br": "Pitcairn"
  },
  "PR": {
    "en": "Puerto Rico",
    "fr": "Puerto Rico",
    "de": "Puerto Rico",
    "es": "Puerto Rico",
    "it": "Porto Rico",
    "io": "crwdns11964:0crwdne11964:0",
    "oc": "Puerto Rico",
    "nl": "Puerto Rico",
    "br": "Puerto Rico"
  },
  "PS": {
    "en": "Palestine",
    "fr": "Palestine",
    "de": "Palästina",
    "es": "Palestina",
    "it": "Palestina",
    "io": "crwdns11966:0crwdne11966:0",
    "oc": "Palestina",
    "nl": "Palestina",
    "br": "Palestina"
  },
  "PT": {
    "en": "Portugal",
    "fr": "Portugal",
    "de": "Portugal",
    "es": "Portugal",
    "it": "Portogallo",
    "io": "crwdns11968:0crwdne11968:0",
    "oc": "Portugal",
    "nl": "Portugal",
    "br": "Portugal"
  },
  "PW": {
    "en": "Palau",
    "fr": "Palau",
    "de": "Palau",
    "es": "Palau",
    "it": "Palau",
    "io": "crwdns11970:0crwdne11970:0",
    "oc": "Palau",
    "nl": "Palau",
    "br": "Palau"
  },
  "PY": {
    "en": "Paraguay",
    "fr": "Paraguay",
    "de": "Paraguay",
    "es": "Paraguay",
    "it": "Paraguay",
    "io": "crwdns11972:0crwdne11972:0",
    "oc": "Paraguai",
    "nl": "Paraguay",
    "br": "Paraguay"
  },
  "QA": {
    "en": "Qatar",
    "fr": "Quatar",
    "de": "Katar",
    "es": "Katar",
    "it": "Qatar",
    "io": "crwdns11974:0crwdne11974:0",
    "oc": "Qatar",
    "nl": "Qatar",
    "br": "Qatar"
  },
  "RE": {
    "en": "Reunion",
    "fr": "Réunion",
    "de": "Wiedervereinigung",
    "es": "reunión",
    "it": "Riunione",
    "io": "crwdns11976:0crwdne11976:0",
    "oc": "Reünion",
    "nl": "Réunion",
    "br": "Ar Reünion"
  },
  "RO": {
    "en": "Romania",
    "fr": "Roumanie",
    "de": "Rumänien",
    "es": "Rumania",
    "it": "Romania",
    "io": "crwdns11978:0crwdne11978:0",
    "oc": "Romania",
    "nl": "Roemenië",
    "br": "Roumania"
  },
  "RU": {
    "en": "Russia",
    "fr": "Russie",
    "de": "Russland",
    "es": "Rusia",
    "it": "Russia",
    "io": "crwdns11980:0crwdne11980:0",
    "oc": "Russia",
    "nl": "Rusland",
    "br": "Rusia"
  },
  "RW": {
    "en": "Rwanda",
    "fr": "Rwanda",
    "de": "Ruanda",
    "es": "Ruanda",
    "it": "Ruanda",
    "io": "crwdns11982:0crwdne11982:0",
    "oc": "Rwanda",
    "nl": "Rwanda",
    "br": "Rwanda"
  },
  "SA": {
    "en": "Saudi Arabia",
    "fr": "Arabie Saoudite",
    "de": "Saudi Arabien",
    "es": "Arabia Saudita",
    "it": "Arabia Saudita",
    "io": "crwdns11984:0crwdne11984:0",
    "oc": "Arabia Saudita",
    "nl": "Saudi-Arabië",
    "br": "Arabia Saoudat"
  },
  "SB": {
    "en": "Solomon Islands",
    "fr": "Iles Salomon",
    "de": "Salomon-Inseln",
    "es": "Islas Salomón",
    "it": "Isole Salomone",
    "io": "crwdns11986:0crwdne11986:0",
    "oc": "Illas Salamon",
    "nl": "Salomonseilanden",
    "br": "Inizi Salomon"
  },
  "SC": {
    "en": "Seychelles",
    "fr": "Seychelles",
    "de": "Seychellen",
    "es": "Seychelles",
    "it": "Seychelles",
    "io": "crwdns11988:0crwdne11988:0",
    "oc": "Seichèlas",
    "nl": "Seychellen",
    "br": "Sechelez"
  },
  "SD": {
    "en": "Sudan",
    "fr": "Soudan",
    "de": "Sudan",
    "es": "Sudán",
    "it": "Sudan",
    "io": "crwdns11990:0crwdne11990:0",
    "oc": "Sodan",
    "nl": "Soedan",
    "br": "Soudan"
  },
  "SE": {
    "en": "Sweden",
    "fr": "Suède",
    "de": "Schweden",
    "es": "Suecia",
    "it": "Svezia",
    "io": "crwdns11992:0crwdne11992:0",
    "oc": "Suècia",
    "nl": "Zweden",
    "br": "Sveden"
  },
  "SG": {
    "en": "Singapore",
    "fr": "Singapour",
    "de": "Singapur",
    "es": "Singapur",
    "it": "Singapore",
    "io": "crwdns11994:0crwdne11994:0",
    "oc": "Singapor",
    "nl": "Singapore",
    "br": "Singapour"
  },
  "SH": {
    "en": "Saint Helena",
    "fr": "Sainte Hélène",
    "de": "St. Helena",
    "es": "Santa Elena",
    "it": "Sant'Elena",
    "io": "crwdns11996:0crwdne11996:0",
    "oc": "Santa Elena",
    "nl": "Sint-Helena",
    "br": "Sant Helena"
  },
  "SI": {
    "en": "Slovenia",
    "fr": "Slovénie",
    "de": "Slowenien",
    "es": "Eslovenia",
    "it": "Slovenia",
    "io": "crwdns11998:0crwdne11998:0",
    "oc": "Eslovènia",
    "nl": "Slovenië",
    "br": "Slovenia"
  },
  "SJ": {
    "en": "Svalbard and Jan Mayen",
    "fr": "Svalbard et Jan Mayen",
    "de": "Svalbard",
    "es": "Svalbard y Jan Mayen",
    "it": "Svalbard e Jan Mayen",
    "io": "crwdns12000:0crwdne12000:0",
    "oc": "Svalbard e Jan Mayen",
    "nl": "Svalbard en Jan Mayen",
    "br": "Svalbard ha Jan Mayen"
  },
  "SK": {
    "en": "Slovakia",
    "fr": "Slovaquie",
    "de": "Slowakei",
    "es": "Eslovaquia",
    "it": "Slovacchia",
    "io": "crwdns12002:0crwdne12002:0",
    "oc": "Eslovaquia",
    "nl": "Slowakije",
    "br": "Slovakia"
  },
  "SL": {
    "en": "Sierra Leone",
    "fr": "Sierra Leone",
    "de": "Sierra Leone",
    "es": "Sierra Leona",
    "it": "Sierra Leone",
    "io": "crwdns12004:0crwdne12004:0",
    "oc": "Sierra Leone",
    "nl": "Sierra Leone",
    "br": "Sierra Leone"
  },
  "SM": {
    "en": "San Marino",
    "fr": "San Marin",
    "de": "San Marino",
    "es": "San Marino",
    "it": "San Marino",
    "io": "crwdns12006:0crwdne12006:0",
    "oc": "Sant Marin",
    "nl": "San Marino",
    "br": "San Marino"
  },
  "SN": {
    "en": "Senegal",
    "fr": "Sénégal",
    "de": "Senegal",
    "es": "Senegal",
    "it": "Senegal",
    "io": "crwdns12008:0crwdne12008:0",
    "oc": "Senegal",
    "nl": "Senegal",
    "br": "Senegal"
  },
  "SO": {
    "en": "Somalia",
    "fr": "Somalie",
    "de": "Somalia",
    "es": "Somalia",
    "it": "Somalia",
    "io": "crwdns12010:0crwdne12010:0",
    "oc": "Somalia",
    "nl": "Somalië",
    "br": "Somalia"
  },
  "SR": {
    "en": "Suriname",
    "fr": "Suriname",
    "de": "Suriname",
    "es": "Surinam",
    "it": "Suriname",
    "io": "crwdns12012:0crwdne12012:0",
    "oc": "Surinam",
    "nl": "Suriname",
    "br": "Surinam"
  },
  "ST": {
    "en": "Sao Tome and Principe",
    "fr": "Sao Tomé et Principe",
    "de": "Sao Tome und Principe",
    "es": "Sao Tome Principe",
    "it": "Sao Tome e Principe",
    "io": "crwdns12014:0crwdne12014:0",
    "oc": "Sao Tomé e Principe",
    "nl": "São Tomé en Principe",
    "br": "São Tomé ha Príncipe"
  },
  "SV": {
    "en": "El Salvador",
    "fr": "Salvador",
    "de": "El Salvador",
    "es": "Salvador",
    "it": "El Salvador",
    "io": "crwdns12016:0crwdne12016:0",
    "oc": "Lo Salvador",
    "nl": "El Salvador",
    "br": "Salvador"
  },
  "SY": {
    "en": "Syria",
    "fr": "Syrie",
    "de": "Syrien",
    "es": "Siria",
    "it": "Siria",
    "io": "crwdns12018:0crwdne12018:0",
    "oc": "Siria",
    "nl": "Syrië",
    "br": "Siria"
  },
  "SZ": {
    "en": "Swaziland",
    "fr": "Swaziland",
    "de": "Swasiland",
    "es": "suazilandia",
    "it": "Swaziland",
    "io": "crwdns12020:0crwdne12020:0",
    "oc": "Swaziland",
    "nl": "Swaziland",
    "br": "Swaziland"
  },
  "TC": {
    "en": "Turks and Caicos Islands",
    "fr": "Îles Turques-et-Caïques",
    "de": "Turks- und Caicosinseln",
    "es": "Turquía y Caicos",
    "it": "Isole Turks e Caicos",
    "io": "crwdns12022:0crwdne12022:0",
    "oc": "Illas Turcas e Caïcas",
    "nl": "Turks- en Caicoseilanden",
    "br": "Inizi Turks ha Caicos"
  },
  "TD": {
    "en": "Chad",
    "fr": "Tchad",
    "de": "Tschad",
    "es": "Chad",
    "it": "Ciad",
    "io": "crwdns12024:0crwdne12024:0",
    "oc": "Chad",
    "nl": "Tsjaad",
    "br": "Tchad"
  },
  "TF": {
    "en": "French Southern Territories",
    "fr": "Territoires Français du Sud",
    "de": "Südfranzösische Territorien",
    "es": "Territorios Franceses del Sur",
    "it": "Territori francesi del Sud",
    "io": "crwdns12026:0crwdne12026:0",
    "oc": "Territòris franceses del Sud",
    "nl": "Franse Zuidelijke Gebieden",
    "br": "Douaroù Aostral Frañs"
  },
  "TG": {
    "en": "Togo",
    "fr": "Togo",
    "de": "Gehen",
    "es": "Togo",
    "it": "Togo",
    "io": "crwdns12028:0crwdne12028:0",
    "oc": "Tògo",
    "nl": "Togo",
    "br": "Togo"
  },
  "TH": {
    "en": "Thailand",
    "fr": "Thaïlande",
    "de": "Thailand",
    "es": "Tailandia",
    "it": "Thailandia",
    "io": "crwdns12030:0crwdne12030:0",
    "oc": "Tailàndia",
    "nl": "Thailand",
    "br": "Thailand"
  },
  "TJ": {
    "en": "Tajikistan",
    "fr": "Tadjikistan",
    "de": "Tadschikistan",
    "es": "Tayikistán",
    "it": "Tajikistan",
    "io": "crwdns12032:0crwdne12032:0",
    "oc": "Tatgiquistan",
    "nl": "Tadzjikistan",
    "br": "Tadjikistan"
  },
  "TK": {
    "en": "Tokelau",
    "fr": "Tokelau",
    "de": "Tokelau",
    "es": "Tokelau",
    "it": "Tokelau",
    "io": "crwdns12034:0crwdne12034:0",
    "oc": "Tokelau",
    "nl": "Tokelau",
    "br": "Tokelau"
  },
  "TL": {
    "en": "Timor-Leste",
    "fr": "Timor oriental",
    "de": "Timor-Leste",
    "es": "Timor del Este",
    "it": "Timor Est",
    "io": "crwdns12036:0crwdne12036:0",
    "oc": "Timòr Èst",
    "nl": "Oost-Timor",
    "br": "Timor-Leste"
  },
  "TM": {
    "en": "Turkmenistan",
    "fr": "Turkmenistan",
    "de": "Turkmenistan",
    "es": "Turkmenistán",
    "it": "Turkmenistan",
    "io": "crwdns12038:0crwdne12038:0",
    "oc": "Turcmenistan",
    "nl": "Turkmenistan",
    "br": "Turkmenistan"
  },
  "TN": {
    "en": "Tunisia",
    "fr": "Tunisie",
    "de": "Tunesien",
    "es": "Túnez",
    "it": "Tunisia",
    "io": "crwdns12040:0crwdne12040:0",
    "oc": "Tunisia",
    "nl": "Tunesië",
    "br": "Tunizia"
  },
  "TO": {
    "en": "Tonga",
    "fr": "Tonga",
    "de": "Tonga",
    "es": "Tonga",
    "it": "Tonga",
    "io": "crwdns12042:0crwdne12042:0",
    "oc": "Tònga",
    "nl": "Tonga",
    "br": "Tonga"
  },
  "TR": {
    "en": "Turkey",
    "fr": "Turquie",
    "de": "Türkei",
    "es": "Turquía",
    "it": "Turchia",
    "io": "crwdns12044:0crwdne12044:0",
    "oc": "Turquia",
    "nl": "Turkije",
    "br": "Turkia"
  },
  "TT": {
    "en": "Trinidad and Tobago",
    "fr": "Trinidad et Tobago",
    "de": "Trinidad und Tobago",
    "es": "Trinidad y Tobago",
    "it": "Trinidad e Tobago",
    "io": "crwdns12046:0crwdne12046:0",
    "oc": "Trinitat e Tobago",
    "nl": "Trinidad en Tobago",
    "br": "Trinidad ha Tobago"
  },
  "TV": {
    "en": "Tuvalu",
    "fr": "Tuvalu",
    "de": "Tuvalu",
    "es": "Tuvalu",
    "it": "Tuvalu",
    "io": "crwdns12048:0crwdne12048:0",
    "oc": "Tuvalu",
    "nl": "Tuvalu",
    "br": "Tuvalu"
  },
  "TW": {
    "en": "Taiwan, China",
    "fr": "Taiwan, Chine",
    "de": "Taiwan, China",
    "es": "Taiwan, China",
    "it": "Taiwan, Cina",
    "io": "crwdns12050:0crwdne12050:0",
    "oc": "Taiwan, China",
    "nl": "Taiwan, China",
    "br": "Taiwan, Sina"
  },
  "TZ": {
    "en": "Tanzania",
    "fr": "Tanzanie",
    "de": "Tansania",
    "es": "Tanzania",
    "it": "Tanzania",
    "io": "crwdns12052:0crwdne12052:0",
    "oc": "Tanzania",
    "nl": "Tanzania",
    "br": "Tanzania"
  },
  "UA": {
    "en": "Ukraine",
    "fr": "Ukraine",
    "de": "Ukraine",
    "es": "Ucrania",
    "it": "Ucraina",
    "io": "crwdns12054:0crwdne12054:0",
    "oc": "Ucraïna",
    "nl": "Oekraïne",
    "br": "Ukraina"
  },
  "UG": {
    "en": "Uganda",
    "fr": "Ouganda",
    "de": "Uganda",
    "es": "Uganda",
    "it": "Uganda",
    "io": "crwdns12056:0crwdne12056:0",
    "oc": "Oganda",
    "nl": "Oeganda",
    "br": "Ouganda"
  },
  "US": {
    "en": "United States",
    "fr": "États-Unis",
    "de": "Vereinigte Staaten",
    "es": "Estados Unidos",
    "it": "Stati Uniti",
    "io": "crwdns12058:0crwdne12058:0",
    "oc": "Estats Units",
    "nl": "Verenigde Staten",
    "br": "Stadoù-Unanet"
  },
  "UY": {
    "en": "Uruguay",
    "fr": "Uruguay",
    "de": "Uruguay",
    "es": "Uruguay",
    "it": "Uruguay",
    "io": "crwdns12060:0crwdne12060:0",
    "oc": "Uruguai",
    "nl": "Uruguay",
    "br": "Uruguay"
  },
  "UZ": {
    "en": "Uzbekistan",
    "fr": "Ouzbekistan",
    "de": "Usbekistan",
    "es": "Uzbekistán",
    "it": "Uzbekistan",
    "io": "crwdns12062:0crwdne12062:0",
    "oc": "Ozbequistan",
    "nl": "Oezbekistan",
    "br": "Ouzbekistan"
  },
  "VA": {
    "en": "Vatican",
    "fr": "Vatican",
    "de": "Vatikan",
    "es": "Vaticano",
    "it": "Vaticano",
    "io": "crwdns12064:0crwdne12064:0",
    "oc": "Vatican",
    "nl": "Vaticaan",
    "br": "Vatikan"
  },
  "VC": {
    "en": "Saint Vincent and the Grenadines",
    "fr": "Saint Vincent et les Grenadines",
    "de": "St. Vincent und die Grenadinen",
    "es": "San Vicente y las Granadinas",
    "it": "San Vincenzo e le Grenadine",
    "io": "crwdns12066:0crwdne12066:0",
    "oc": "Sant Vincenç e las Grenadinas",
    "nl": "Saint Vincent en de Grenadines",
    "br": "Sant Visant hag ar Grenadinez"
  },
  "VE": {
    "en": "Venezuela",
    "fr": "Venezuela",
    "de": "Venezuela",
    "es": "Venezuela",
    "it": "Venezuela",
    "io": "crwdns12068:0crwdne12068:0",
    "oc": "Veneçuèla",
    "nl": "Venezuela",
    "br": "Venezuela"
  },
  "VG": {
    "en": "British Virgin Islands",
    "fr": "Iles Vierges britanniques",
    "de": "Britische Jungferninseln",
    "es": "Islas Vírgenes Británicas",
    "it": "Isole Vergini britanniche",
    "io": "crwdns12070:0crwdne12070:0",
    "oc": "Illas Verges Britanicas",
    "nl": "Britse Maagdeneilanden",
    "br": "Inizi Gwerc'h Breizh-Veur"
  },
  "VI": {
    "en": "U.S. Virgin Islands",
    "fr": "Îles Vierges américaines",
    "de": "US Jungferninseln",
    "es": "Islas Vírgenes de los EE.UU.",
    "it": "Isole Vergini Americane",
    "io": "crwdns12072:0crwdne12072:0",
    "oc": "Illas Verges Americanas",
    "nl": "Amerikaanse Maagdeneilanden",
    "br": "Inizi Gwerc'h ar Stadoù-Unanet"
  },
  "VN": {
    "en": "Viet Nam",
    "fr": "Vietnam",
    "de": "Vietnam",
    "es": "Vietnam",
    "it": "Vietnam",
    "io": "crwdns12074:0crwdne12074:0",
    "oc": "Vietnam",
    "nl": "Vietnam",
    "br": "Viêt Nam"
  },
  "VU": {
    "en": "Vanuatu",
    "fr": "Vanuatu",
    "de": "Vanuatu",
    "es": "Vanuatu",
    "it": "Vanuatu",
    "io": "crwdns12076:0crwdne12076:0",
    "oc": "Vanuatu",
    "nl": "Vanuatu",
    "br": "Vanuatu"
  },
  "WF": {
    "en": "Wallis and Futuna",
    "fr": "Wallis et Futuna",
    "de": "Wallis und Futuna",
    "es": "Wallis y Futuna",
    "it": "Wallis e Futuna",
    "io": "crwdns12078:0crwdne12078:0",
    "oc": "Wallis e Futuna",
    "nl": "Wallis en Futuna",
    "br": "Wallis ha Futuna"
  },
  "WS": {
    "en": "Samoa",
    "fr": "Samoa Américaines",
    "de": "Samoa",
    "es": "Samoa Americana",
    "it": "Samoa americane",
    "io": "crwdns12080:0crwdne12080:0",
    "oc": "Samoa",
    "nl": "Samoa",
    "br": "Samoa"
  },
  "XK": {
    "en": "Kosovo",
    "fr": "Kosovo",
    "de": "Kosovo",
    "es": "Kosovo",
    "it": "Kosovo",
    "io": "crwdns12082:0crwdne12082:0",
    "oc": "Kosova",
    "nl": "Kosovo",
    "br": "Kosovo"
  },
  "YE": {
    "en": "Yemen",
    "fr": "Yémen",
    "de": "Jemen",
    "es": "Yemen",
    "it": "Yemen",
    "io": "crwdns12084:0crwdne12084:0",
    "oc": "Iemèn",
    "nl": "Jemen",
    "br": "Yemen"
  },
  "YT": {
    "en": "Mayotte",
    "fr": "Mayotte",
    "de": "Mayotte",
    "es": "Mayotte",
    "it": "Mayotte",
    "io": "crwdns12086:0crwdne12086:0",
    "oc": "Maiòta",
    "nl": "Mayotte",
    "br": "Mayotte"
  },
  "ZA": {
    "en": "South Africa",
    "fr": "Afrique du Sud",
    "de": "Südafrika",
    "es": "Africa del Sur",
    "it": "Sudafrica",
    "io": "crwdns12088:0crwdne12088:0",
    "oc": "Africa del Sud",
    "nl": "Zuid-Afrika",
    "br": "Suafrika"
  },
  "ZM": {
    "en": "Zambia",
    "fr": "Zambie",
    "de": "Sambia",
    "es": "Zambia",
    "it": "Zambia",
    "io": "crwdns12090:0crwdne12090:0",
    "oc": "Zambia",
    "nl": "Zambia",
    "br": "Zambia"
  },
  "ZW": {
    "en": "Zimbabwe",
    "fr": "Zimbabwe",
    "de": "Zimbabwe",
    "es": "Zimbabue",
    "it": "Zimbabwe",
    "io": "crwdns12092:0crwdne12092:0",
    "oc": "Zimbabwe",
    "nl": "Zimbabwe",
    "br": "Zimbabwe"
  }
}
