"use strict";

module.exports = {
  "addField": {
    "fr": "Ajouter un champ",
    "en": "Add a field",
    "de": "Fügen Sie ein Feld hinzu",
    "es": "Agregar campo",
    "it": "Aggiungere un campo",
    "io": "crwdns14674:0crwdne14674:0",
    "oc": "Apondre un camp",
    "nl": "Een veld toevoegen",
    "br": "Ouzhpennañ ur vaezienn"
  },
  "draggableField": {
    "fr": "Glisser-déposer pour trier",
    "en": "Drag and drop to sort",
    "de": "Zum Sortieren ziehen und ablegen",
    "es": "Arrastrar y soltar para ordenar",
    "it": "Trascinare e rilasciare per ordinare",
    "io": "crwdns14676:0crwdne14676:0",
    "oc": "Fasètz lisar per triar",
    "nl": "Slepen en neerzetten om te sorteren",
    "br": "Riklañ-dilec'hiañ evit rummañ"
  },
  "editField": {
    "fr": "Modifier",
    "en": "Edit",
    "de": "Bearbeiten",
    "es": "Editar",
    "it": "Modificare",
    "io": "crwdns14678:0crwdne14678:0",
    "oc": "Modificar",
    "nl": "Bewerken",
    "br": "Aozañ"
  },
  "hideField": {
    "fr": "Cacher",
    "en": "Hide",
    "de": "Verstecken",
    "es": "Ocultar",
    "it": "Nascondere",
    "io": "crwdns14680:0crwdne14680:0",
    "oc": "Amagar",
    "nl": "Verbergen",
    "br": "Kuzhat"
  },
  "showField": {
    "fr": "Afficher le champ",
    "en": "Display the field",
    "de": "Zeigen Sie das Feld an",
    "es": "Mostrar campo",
    "it": "Visualizzare il campo",
    "io": "crwdns14682:0crwdne14682:0",
    "oc": "Mostrar lo camp",
    "nl": "Het veld weergeven",
    "br": "Diskouez ar vaezienn"
  },
  "hiddenField": {
    "fr": "Champ caché",
    "en": "Hidden field",
    "de": "Verstecktes Feld",
    "es": "Ocultar campo",
    "it": "Campo nascosto",
    "io": "crwdns14684:0crwdne14684:0",
    "oc": "Camp amagat",
    "nl": "Verborgen veld",
    "br": "Maezienn guzhet"
  },
  "removeField": {
    "fr": "Supprimer",
    "en": "Delete",
    "de": "Löschen",
    "es": "Eliminar",
    "it": "Cancellare",
    "io": "crwdns14686:0crwdne14686:0",
    "oc": "Suprimir",
    "nl": "Verwijderen",
    "br": "Lemel"
  },
  "editFieldLabels": {
    "fr": "Modifier les labels",
    "en": "Edit labels",
    "de": "Beschriftungen bearbeiten",
    "es": "Editar las etiquetas",
    "it": "Modifica etichette",
    "io": "crwdns14688:0crwdne14688:0",
    "oc": "Modificar las etiquetas",
    "nl": "Labels bewerken",
    "br": "Embann ar skritelligoù"
  },
  "editFieldSave": {
    "fr": "Sauvegarder",
    "en": "Save",
    "de": "Speichern",
    "es": "Guardar",
    "it": "Registrare",
    "br": "Enrollañ",
    "io": "crwdns14690:0crwdne14690:0",
    "oc": "Enregistrar",
    "nl": "Opslaan"
  },
  "editFieldCancel": {
    "fr": "Annuler",
    "en": "Cancel",
    "de": "Stornieren",
    "es": "Anular",
    "it": "Annulla",
    "br": "Nullañ",
    "io": "crwdns14692:0crwdne14692:0",
    "oc": "Anullar",
    "nl": "Annuleren"
  },
  "orderField": {
    "fr": "Glisser / déposer",
    "en": "Drag and drop",
    "de": "Ziehen und ablegen",
    "es": "Arrastrar y soltar",
    "it": "Trascina e rilascia",
    "io": "crwdns14694:0crwdne14694:0",
    "oc": "Lisar / pausar",
    "nl": "Slepen en neerzetten",
    "br": "Riklañ / dilec'hiañ"
  },
  "fieldLabel": {
    "fr": "Titre du champ",
    "en": "Field title",
    "de": "Feldtitel",
    "es": "Campo para el título",
    "it": "Titolo del campo",
    "io": "crwdns14696:0crwdne14696:0",
    "oc": "Títol del camp",
    "nl": "Veldtitel",
    "br": "Titl ar vaezienn"
  },
  "fieldInfo": {
    "fr": "Information complémentaire",
    "en": "Additional information",
    "de": "Weitere Informationen",
    "es": "Información adicional",
    "it": "Ulteriori informazioni",
    "io": "crwdns14698:0crwdne14698:0",
    "oc": "Informacions complementàrias",
    "nl": "Aanvullende informatie",
    "br": "Titouroù ouzhpenn"
  },
  "fieldOptions": {
    "fr": "Valeurs possibles",
    "en": "Possible values",
    "de": "Mögliche Werte",
    "es": "Valores posibles",
    "it": "Valori possibili",
    "io": "crwdns14700:0crwdne14700:0",
    "oc": "Valors possiblas",
    "nl": "Mogelijke waarden",
    "br": "Talvoudoù posupl"
  },
  "fieldInfoInfo": {
    "fr": "S'affiche sous le titre (comme ceci)",
    "en": "Displayed below the title (like this)",
    "de": "Wird unter dem Titel angezeigt (so)",
    "es": "Aparece bajo el título (como este)",
    "it": "Visualizza sotto il titolo (così)",
    "io": "crwdns14702:0crwdne14702:0",
    "oc": "Apareis dejol títol (atal)",
    "nl": "Wordt onder de titel weergegeven (zoals dit)",
    "br": "Diskouezet dindan an titl (evel-se)"
  },
  "fieldPlaceholder": {
    "fr": "Substitut",
    "en": "Placeholder",
    "de": "Platzhalter",
    "es": "Sustituto",
    "it": "Sostituire",
    "io": "crwdns14704:0crwdne14704:0",
    "oc": "Tapatrauc",
    "nl": "Tijdelijke aanduiding",
    "br": "Erlec'hier"
  },
  "fieldPlaceholderPlaceholder": {
    "fr": "S'affiche à l'intérieur (comme ceci)",
    "en": "Is displayed inside the field (like this)",
    "de": "Wird innerhalb des Feldes angezeigt (so)",
    "es": "Se muestra al interior del campo (como este)",
    "it": "Display all'interno (come questo)",
    "io": "crwdns14706:0crwdne14706:0",
    "oc": "Apareis dins lo camp (atal)",
    "nl": "Wordt binnen het veld weergegeven (zoals dit)",
    "br": "Diskouezet e-barzh ar vaezienn (evel-se)"
  },
  "fieldSub": {
    "fr": "Label de sous-champ",
    "en": "Sub info label",
    "de": "Unterinfo-Label",
    "es": "Etiqueta de subcampo",
    "it": "Etichetta del sottocampo",
    "io": "crwdns14708:0crwdne14708:0",
    "oc": "Etiqueta de soscamp",
    "nl": "Subveld label",
    "br": "Skritellig is-vaezienn"
  },
  "fieldSubSub": {
    "fr": "S'affiche sous le champ (comme ceci)",
    "en": "Is displayed below the field (like this)",
    "de": "Wird unterhalb des Feldes angezeigt (so)",
    "es": "Aparece debajo del campo (como este)",
    "it": "Visualizza sotto il campo (così)",
    "io": "crwdns14710:0crwdne14710:0",
    "oc": "Apareis dejol camp (atal)",
    "nl": "Wordt onder het veld weergegeven (zoals dit)",
    "br": "Diskouezet dindan ar vaezienn (evel-se)"
  },
  "fieldMinMaxSection": {
    "fr": "Min et max",
    "en": "Min and max",
    "de": "Min und Max",
    "es": "Mín. y máx.",
    "it": "Min e max",
    "oc": "Min e max",
    "nl": "Min en max",
    "br": "Min ha max"
  },
  "fieldMinMaxSectionInfo": {
    "fr": "Longueur du texte ou plage de valeurs autorisée",
    "en": "Text length or allowed value range",
    "de": "Textlänge oder zulässiger Wertebereich",
    "es": "Longitud del texto o rango de valores permitido",
    "it": "Lunghezza del testo o intervallo di valori consentito",
    "oc": "Longor del tèxte o plaja de valors autorizadas",
    "nl": "Tekstlengte of toegestaan waardenbereik",
    "br": "Hirder an destenn pe sourm a dalvoudoù aotreet"
  },
  "fieldInfoSection": {
    "fr": "Information complémentaire",
    "en": "Additional information",
    "de": "Weitere Informationen",
    "es": "Información adicional",
    "it": "Ulteriori informazioni",
    "oc": "Informacions complementàrias",
    "nl": "Aanvullende informatie",
    "br": "Titouroù ouzhpenn"
  },
  "fieldInfoSectionInfo": {
    "fr": "Texte affiché sous le titre du champ",
    "en": "Text shown below the field title",
    "de": "Text, der unter dem Feldtitel angezeigt wird",
    "es": "Texto mostrado debajo del título del campo",
    "it": "Testo visualizzato sotto il titolo del campo",
    "oc": "Tèxte afichat dejol lo títol del camp",
    "nl": "Tekst die onder de veldtitel wordt weergegeven",
    "br": "Testenn diskouezet dindan titl ar vaezienn"
  },
  "fieldPlaceholderSubSection": {
    "fr": "Substitut et label de sous-champ",
    "en": "Placeholder and sub label",
    "de": "Platzhalter und Unterinfo-Label",
    "es": "Sustituto y etiqueta de subcampo",
    "it": "Sostituto ed etichetta del sottocampo",
    "oc": "Tapatrauc e etiqueta de soscamp",
    "nl": "Tijdelijke aanduiding en subveldlabel",
    "br": "Erlec'hier ha skritellig is-vaezienn"
  },
  "fieldPlaceholderSubSectionInfo": {
    "fr": "Textes affichés à l'intérieur et en dessous du champ",
    "en": "Texts shown inside and below the field",
    "de": "Texte, die innerhalb und unterhalb des Feldes angezeigt werden",
    "es": "Textos mostrados dentro y debajo del campo",
    "it": "Testi visualizzati all'interno e sotto il campo",
    "oc": "Tèxtes afichats a l'interior e dejol lo camp",
    "nl": "Teksten die binnen en onder het veld worden weergegeven",
    "br": "Testennoù diskouezet e-barzh hag dindan ar vaezienn"
  },
  "fieldHelpSection": {
    "fr": "Aide contextuelle",
    "en": "Contextual help",
    "de": "Kontextbezogene Hilfe",
    "es": "Ayuda contextual",
    "it": "Aiuto contestuale",
    "oc": "Ajuda contextuala",
    "nl": "Contextuele hulp",
    "br": "Skoazell diouzh ar c'hempred"
  },
  "fieldHelpSectionInfo": {
    "fr": "Message d'aide, lien et infobulle au format Markdown",
    "en": "Help message, link and Markdown tooltip",
    "de": "Hilfetext, Link und Markdown-Tooltip",
    "es": "Mensaje de ayuda, enlace e información sobre herramientas en Markdown",
    "it": "Messaggio di aiuto, collegamento e tooltip in Markdown",
    "oc": "Messatge d'ajuda, ligam e infobulla al format Markdown",
    "nl": "Hulptekst, link en Markdown-tooltip",
    "br": "Kemennadenn skoazell, liamm hag infobullenn er stumm Markdown"
  },
  "fieldHelp": {
    "fr": "Texte d'aide",
    "en": "Help text",
    "de": "Hilfetext",
    "es": "Texto de ayuda",
    "it": "Testo di aiuto",
    "oc": "Tèxte d'ajuda",
    "nl": "Helptekst",
    "br": "Testenn skoazell"
  },
  "fieldHelpInfo": {
    "fr": "Court message d'aide affiché à côté du champ",
    "en": "Short help message shown next to the field",
    "de": "Kurzer Hilfetext, der neben dem Feld angezeigt wird",
    "es": "Mensaje corto de ayuda mostrado junto al campo",
    "it": "Breve messaggio di aiuto visualizzato accanto al campo",
    "oc": "Cort messatge d'ajuda afichat al costat del camp",
    "nl": "Korte hulptekst die naast het veld wordt weergegeven",
    "br": "Kemennadenn skoazell verr diskouezet e-kichen ar vaezienn"
  },
  "fieldHelpLink": {
    "fr": "Lien d'aide",
    "en": "Help link",
    "de": "Hilfe-Link",
    "es": "Enlace de ayuda",
    "it": "Collegamento di aiuto",
    "oc": "Ligam d'ajuda",
    "nl": "Hulplink",
    "br": "Liamm skoazell"
  },
  "fieldHelpLinkPlaceholder": {
    "fr": "https://… ou mailto:…",
    "en": "https://… or mailto:…",
    "de": "https://… oder mailto:…",
    "es": "https://… o mailto:…",
    "it": "https://… o mailto:…",
    "oc": "https://… o mailto:…",
    "nl": "https://… of mailto:…",
    "br": "https://… pe mailto:…"
  },
  "fieldHelpContent": {
    "fr": "Contenu d'aide (Markdown)",
    "en": "Help content (Markdown)",
    "de": "Hilfe-Inhalt (Markdown)",
    "es": "Contenido de ayuda (Markdown)",
    "it": "Contenuto di aiuto (Markdown)",
    "oc": "Contengut d'ajuda (Markdown)",
    "nl": "Hulpinhoud (Markdown)",
    "br": "Endalc'had skoazell (Markdown)"
  },
  "fieldHelpContentInfo": {
    "fr": "Texte Markdown affiché au survol d'une icône d'aide",
    "en": "Markdown text shown when hovering a help icon",
    "de": "Markdown-Text, der beim Überfahren eines Hilfe-Symbols angezeigt wird",
    "es": "Texto Markdown mostrado al pasar el cursor sobre un icono de ayuda",
    "it": "Testo Markdown visualizzato al passaggio del mouse su un'icona di aiuto",
    "oc": "Tèxte Markdown afichat en passant lo cursor sus una icòna d'ajuda",
    "nl": "Markdown-tekst die wordt weergegeven bij het zweven over een hulppictogram",
    "br": "Testenn Markdown diskouezet pa veler dreist ur skeudennig skoazell"
  },
  "addLanguages": {
    "fr": "Ajouter des langues",
    "en": "Add languages",
    "de": "Sprachen hinzufügen",
    "es": "Añadir idiomas",
    "it": "Aggiungere una lingua",
    "io": "crwdns14712:0crwdne14712:0",
    "oc": "Apondre de lengas",
    "nl": "Talen toevoegen",
    "br": "Ouzhpennañ yezhoù"
  },
  "monolingualLabels": {
    "fr": "Monolingue",
    "en": "Monolingual",
    "de": "Einsprachig",
    "es": "Monolingüe",
    "it": "Monolingue",
    "io": "crwdns14714:0crwdne14714:0",
    "oc": "Monolingüe",
    "nl": "Eentalig",
    "br": "Unyezhek"
  },
  "multilingualLabels": {
    "fr": "Langues des labels",
    "en": "Label languages",
    "de": "Sprachen beschriften",
    "es": "Etiquetas de idioma",
    "it": "Lingue dell'etichetta",
    "io": "crwdns14716:0crwdne14716:0",
    "oc": "Lengas de las etiquetas",
    "nl": "Labeltalen",
    "br": "Yezhoù ar skritelligoù"
  },
  "editLabelLanguages": {
    "fr": "Modifier",
    "en": "Edit",
    "de": "Bearbeiten",
    "es": "Editar",
    "it": "Modificare",
    "io": "crwdns14718:0crwdne14718:0",
    "oc": "Modificar",
    "nl": "Bewerken",
    "br": "Aozañ"
  },
  "editLabelLanguagesInfo": {
    "fr": "Listez les langues dans lesquelles devront être déclinées les labels du formulaire",
    "en": "List the languages in which the labels of the form will be available",
    "de": "Listen Sie die Sprachen auf, in denen die Beschriftungen des Formulars verfügbar sein werden",
    "es": "Enumerar los idiomas que será rechazada etiquetas forman",
    "it": "Elencare le lingue in cui le etichette sul modulo devono essere disponibili.",
    "io": "crwdns14720:0crwdne14720:0",
    "oc": "Listatz las lengas dins las qualas las etiquetas del formulari seràn disponiblas",
    "nl": "Geef de talen op waarin de labels van het formulier beschikbaar moeten zijn",
    "br": "Listennet ar yezhoù ma vo kinniget skritelligoù ar furmskrid enno"
  },
  "uneditableFieldInfo": {
    "fr": "Ce champ ne peut pas être modifié",
    "en": "This field cannot be modified",
    "de": "Dieses Feld kann nicht geändert werden",
    "es": "Este campo no se puede modificar",
    "it": "Questo campo non può essere modificato",
    "io": "crwdns14722:0crwdne14722:0",
    "oc": "Aqueste camp se pòt pas modificar",
    "nl": "Dit veld kan niet worden gewijzigd",
    "br": "N'hall ket ar vaezienn-mañ bezañ kemmet"
  },
  "editFieldInfo": {
    "fr": "Modifier les propriétés de ce champ",
    "en": "Update properties of this field",
    "de": "Eigenschaften dieses Feldes aktualisieren",
    "es": "Editar las propiedades de este campo",
    "it": "Modificare le proprietà di questo campo",
    "io": "crwdns14724:0crwdne14724:0",
    "oc": "Metre a jorn las proprietats d'aqueste camp",
    "nl": "Eigenschappen van dit veld bijwerken",
    "br": "Kemmañ perzhioù ar vaezienn-mañ"
  },
  "addLabelLanguages": {
    "fr": "Définir des langues",
    "en": "Define languages",
    "de": "Sprachen definieren",
    "es": "Establecer idioma",
    "it": "Definire le lingue",
    "io": "crwdns14726:0crwdne14726:0",
    "oc": "Definir de lengas",
    "nl": "Talen definiëren",
    "br": "Termeniñ yezhoù"
  },
  "submitLabelLanguages": {
    "fr": "Enregistrer",
    "en": "Submit",
    "de": "Speichern",
    "es": "Registrar",
    "it": "Convalidare",
    "br": "Kemmañ",
    "io": "crwdns14728:0crwdne14728:0",
    "oc": "Sometre",
    "nl": "Opslaan"
  },
  "removeLabelLanguages": {
    "fr": "Retirer les langues",
    "en": "Clear languages",
    "de": "Klare Sprachen",
    "es": "Eliminar idiomas",
    "it": "Rimozione delle lingue",
    "io": "crwdns14730:0crwdne14730:0",
    "oc": "Levar las lengas",
    "nl": "Talen verwijderen",
    "br": "Lemel ar yezhoù"
  },
  "fieldLabelLanguages": {
    "fr": "Langues des labels",
    "en": "Label languages",
    "de": "Sprachen beschriften",
    "es": "Etiquetas de idioma",
    "it": "Lingue dell'etichetta",
    "io": "crwdns14732:0crwdne14732:0",
    "oc": "Lengas de las etiquetas",
    "nl": "Labeltalen",
    "br": "Yezhoù ar skritelligoù"
  },
  "textFieldType": {
    "fr": "Champ texte",
    "en": "Text field",
    "de": "Textfeld",
    "es": "Campo de texto",
    "it": "Campo di testo",
    "io": "crwdns14734:0crwdne14734:0",
    "oc": "Camp de tèxte",
    "nl": "Tekstveld",
    "br": "Maezienn destenn"
  },
  "textareaFieldType": {
    "fr": "Champ texte multilignes (Paragraphe)",
    "en": "Textarea",
    "de": "Textbereich",
    "es": "Texto (Párrafo)",
    "it": "Testo (Paragrafo)",
    "io": "crwdns14736:0crwdne14736:0",
    "oc": "Zòna de tèxte",
    "nl": "Tekstveld met meerdere regels (Paragraaf)",
    "br": "Maezienn destenn lieslinenn (Rannbennad)"
  },
  "markdownFieldType": {
    "fr": "Texte enrichi",
    "en": "Rich text",
    "de": "Rich-Text",
    "es": "Texto enriquecido",
    "it": "Testo arricchito",
    "io": "crwdns14738:0crwdne14738:0",
    "oc": "Tèxte ric",
    "nl": "Opgemaakte tekst",
    "br": "Testenn pinvidikaet"
  },
  "markdownFieldTypeInfo": {
    "fr": "Champ texte enrichi (markdown)",
    "en": "Enriched text field (markdown)",
    "de": "Angereichertes Textfeld (Markdown)",
    "io": "crwdns14740:0crwdne14740:0",
    "it": "Campo di testo arricchito (markdown)",
    "oc": "Camp de tèxte enriquesit (markdown)",
    "es": "Campo de texto enriquecido (markdown)",
    "nl": "Opgemaakt tekstveld (markdown)",
    "br": "Maezienn destenn pinvidikaet (markdown)"
  },
  "integerFieldType": {
    "fr": "Nombre entier",
    "en": "Integer number",
    "de": "Ganzzahlige Zahl",
    "es": "Número completo",
    "it": "Numero intero",
    "io": "crwdns14742:0crwdne14742:0",
    "oc": "Nombre entièr",
    "nl": "Geheel getal",
    "br": "Niver klok"
  },
  "emailFieldType": {
    "fr": "Email",
    "en": "Email",
    "de": "Email",
    "es": "Dirección de correo electrónico",
    "it": "Email",
    "br": "Postel",
    "io": "crwdns14744:0crwdne14744:0",
    "oc": "Email",
    "nl": "E-mail"
  },
  "phoneFieldType": {
    "fr": "Numéro de téléphone",
    "en": "Phone number",
    "es": "Número de teléfono",
    "oc": "Numèro de telefòne",
    "io": "crwdns34158:0crwdne34158:0",
    "it": "Telefono",
    "nl": "Telefoonnummer",
    "br": "Niverenn bellgomz"
  },
  "linkFieldType": {
    "fr": "Hyperlien",
    "en": "Hyperlink",
    "de": "Hyperlink",
    "it": "Hyperlink",
    "es": "Enlace",
    "io": "crwdns14746:0crwdne14746:0",
    "oc": "Ligam ipertèxte",
    "nl": "Hyperlink",
    "br": "Gourliamm"
  },
  "textMultilingualFieldType": {
    "fr": "Text multilingue",
    "en": "Multilingual text",
    "de": "Mehrsprachiger Text",
    "es": "Texto en varios idiomas",
    "it": "Testo multilingue",
    "io": "crwdns14748:0crwdne14748:0",
    "oc": "Tèxte multilingüe",
    "nl": "Meertalige tekst",
    "br": "Testenn liesyezhek"
  },
  "checkboxFieldType": {
    "fr": "Liste de cases à cocher, à choix multiples",
    "en": "Multiple checkbox selection",
    "de": "Auswahl mehrerer Kontrollkästchen",
    "es": "Selección de múltiples casillas por marcar",
    "it": "Selezione a scelta multipla",
    "io": "crwdns14750:0crwdne14750:0",
    "oc": "Tièra de casas de picar, causida multipla",
    "nl": "Lijst met selectievakjes, meerdere keuzes",
    "br": "Roll logoù da askañ, dibab liesel"
  },
  "checkboxFieldTypeInfo": {
    "fr": "Séries de cases à cocher permettant la sélection de valeurs multiples",
    "en": "A series of checkboxes allowing for the selection of multiple values",
    "de": "Eine Reihe von Kontrollkästchen, die die Auswahl mehrerer Werte ermöglichen",
    "io": "crwdns14752:0crwdne14752:0",
    "it": "Una serie di caselle di controllo che permettono la selezione di più valori",
    "oc": "Una tièra de casas de picar que permet de triar mai d'una valor",
    "es": "Serie de casillas por marcar que permiten la selección de múltiples valores",
    "nl": "Een reeks selectievakjes die het selecteren van meerdere waarden mogelijk maakt",
    "br": "Ur steudad logoù da askañ a ro tu da ziuzañ meur a dalvoud"
  },
  "multiselectFieldType": {
    "fr": "Menu déroulant à sélection multiple",
    "en": "Multiple choice dropdown select",
    "de": "Multiple-Choice-Dropdown-Auswahl",
    "io": "crwdns14754:0crwdne14754:0",
    "it": "Selezione a discesa a scelta multipla",
    "oc": "Menut desrotlant a causida multipla",
    "es": "Menú desplegable de selección múltiple",
    "nl": "Vervolgkeuzemenu met meerdere selecties",
    "br": "Lañser diwar-ziskouez dibab liesel"
  },
  "multiselectFieldTypeInfo": {
    "fr": "Champ de saisie avec menu déroulant et auto-completion permettant la sélection de valeurs multiples",
    "en": "Input field with dropdown and autocomplete allowing the selection of multiple values from a list",
    "de": "Eingabefeld mit Dropdown und Autovervollständigung, das die Auswahl mehrerer Werte aus einer Liste ermöglicht",
    "io": "crwdns14756:0crwdne14756:0",
    "it": "Campo di input con dropdown e autocompletamento che permette la selezione di più valori da una lista",
    "oc": "Camp de sasida amb menut desrotlant e autocomplecion que permet de triar mai d'una valor dins una lista",
    "es": "Campo de entrada con menú desplegable y autocompletado que permite la selección de múltiples valores de una lista",
    "nl": "Invoerveld met vervolgkeuzemenu en automatisch aanvullen voor het selecteren van meerdere waarden uit een lijst",
    "br": "Maezienn enankañ gant lañser diwar-ziskouez hag emleuniañ a ro tu da ziuzañ meur a dalvoud diwar ul listenn"
  },
  "radioFieldType": {
    "fr": "Liste de cases à cocher, à choix unique",
    "en": "Single choice selection",
    "de": "Single-Choice-Auswahl",
    "es": "Selección única",
    "it": "Selezione a scelta singola",
    "io": "crwdns14758:0crwdne14758:0",
    "oc": "Causida simpla",
    "nl": "Lijst met selectievakjes, enkele keuze",
    "br": "Roll logoù da askañ, dibab nemetañ"
  },
  "radioFieldTypeInfo": {
    "fr": "Adapté pour la sélection d'une valeur, une seule, parmi plusieurs options",
    "en": "List of choices allowing the selection of a unique value",
    "de": "Liste von Auswahlmöglichkeiten, die die Auswahl eines eindeutigen Werts ermöglichen",
    "io": "crwdns14760:0crwdne14760:0",
    "it": "Elenco di scelte che permettono la selezione di un valore unico",
    "oc": "Lista de causidas que permet de causir pas qu'una valor",
    "es": "Lista de opciones que permiten la selección de un valor único",
    "nl": "Keuzelijst voor het selecteren van één unieke waarde",
    "br": "Roll dibaboù a ro tu da ziuzañ un dalvoud nemetañ"
  },
  "selectFieldType": {
    "fr": "Menu déroulant à sélection unique",
    "en": "Single selection dropdown select",
    "de": "Einzelauswahl-Dropdown-Auswahl",
    "io": "crwdns14762:0crwdne14762:0",
    "it": "Selezione singola a discesa",
    "oc": "Menut desrotlant a causida unica",
    "es": "Menú desplegable de selección única",
    "nl": "Vervolgkeuzemenu met enkele selectie",
    "br": "Lañser diwar-ziskouez dibab nemetañ"
  },
  "selectFieldTypeInfo": {
    "fr": "Adapté à une longue liste de choix. Cela affiche un champ de saisie avec menu déroulant et auto-completion pour trouver et sélectionner rapidement une valeur",
    "en": "Input field with dropdown and autocomplete allowing the selection of single value from a list",
    "de": "Eingabefeld mit Dropdown-Liste und automatischer Vervollständigung, die die Auswahl eines einzelnen Werts aus einer Liste ermöglicht",
    "io": "crwdns14764:0crwdne14764:0",
    "it": "Campo di input con dropdown e autocompletamento che permette la selezione di più valori da una lista",
    "oc": "Camp de sasida amb menut desrotlant e autocomplecion que permet de triar una sola valor dins una lista",
    "es": "Campo de entrada con menú desplegable y autocompletado que permite la selección de un valor único de una lista",
    "nl": "Invoerveld met vervolgkeuzemenu en automatisch aanvullen voor het selecteren van één waarde uit een lijst",
    "br": "Maezienn enankañ gant lañser diwar-ziskouez hag emleuniañ a ro tu da ziuzañ un dalvoud nemetañ diwar ul listenn"
  },
  "booleanFieldType": {
    "fr": "Case à cocher unique",
    "en": "Single checkbox",
    "de": "Einzelnes Kontrollkästchen",
    "es": "Casillas por marcar única",
    "it": "Casella di controllo singola",
    "io": "crwdns14766:0crwdne14766:0",
    "oc": "Casa de picar unica",
    "nl": "Enkel selectievakje",
    "br": "Log da askañ nemetañ"
  },
  "booleanFieldTypeInfo": {
    "fr": "Adapté aux choix de type oui/non",
    "en": "Yes/no choice",
    "de": "Ja/Nein-Auswahl",
    "io": "crwdns14768:0crwdne14768:0",
    "it": "Scelta sì/no",
    "oc": "Causida òc/non",
    "es": "Opción Si / No",
    "nl": "Ja/nee keuze",
    "br": "Dibab a seurt ya/nann"
  },
  "dateFieldType": {
    "fr": "Sélecteur de date",
    "en": "Date selection",
    "de": "Datumsauswahl",
    "it": "Selezione della data",
    "io": "crwdns16462:0crwdne16462:0",
    "oc": "Seleccion de data",
    "es": "Selección de fecha",
    "nl": "Datumselectie",
    "br": "Dibaber deiziad"
  },
  "dateFieldTypeInfo": {
    "fr": "Un calendrier permet la sélection d'une date",
    "en": "A calendar to select a date",
    "de": "Ein Kalender zur Auswahl eines Datums",
    "it": "Un calendario per selezionare una data",
    "io": "crwdns16464:0crwdne16464:0",
    "oc": "Un calendièr per causir una data",
    "es": "Un calendario para seleccionar una fecha",
    "nl": "Een kalender om een datum te selecteren",
    "br": "Un deiziadur evit diuzañ un deiziad"
  },
  "section": {
    "fr": "Section",
    "en": "Section",
    "de": "Abschnitt",
    "io": "crwdns32877:0crwdne32877:0",
    "es": "Sección",
    "nl": "Sectie",
    "br": "Lodenn"
  },
  "sectionType": {
    "fr": "Titre de section / séparateur",
    "en": "Section title / divider",
    "de": "Abschnittstitel/Trenner",
    "io": "crwdns32879:0crwdne32879:0",
    "it": "Titolo di sezione",
    "es": "Título de sección / separador",
    "nl": "Sectietitel / scheidingslijn",
    "br": "Titl lodenn / dispartier"
  },
  "sectionTypeInfo": {
    "fr": "Affiche un titre de section dans le formulaire marquant une séparation visuelle dans l'affichage des champs",
    "en": "Displays a section head in the form creating a visual separation between the fields above and below",
    "de": "Zeigt einen Abschnittskopf im Formular an, wodurch eine visuelle Trennung zwischen den Feldern darüber und darunter entsteht",
    "io": "crwdns32881:0crwdne32881:0",
    "it": "Visualizza una testa di sezione nel modulo, creando una separazione visiva tra i campi sopra e sotto",
    "es": "Muestra un encabezado de sección en el formulario creando una separación visual entre los campos de arriba y abajo",
    "nl": "Toont een sectiekop in het formulier die een visuele scheiding creëert tussen de velden erboven en eronder",
    "br": "Diskouez un titl lodenn er furmskrid o krouiñ un dispartiadur gweledel etre ar maeziennoù a-us hag a-zindan"
  },
  "sectionLabel": {
    "fr": "Titre",
    "en": "Title",
    "de": "Titel",
    "it": "Titolo",
    "oc": "Títol",
    "io": "crwdns32883:0crwdne32883:0",
    "es": "Título",
    "nl": "Titel",
    "br": "Titl"
  },
  "sectionInfo": {
    "fr": "Laissez ce champ vide si vous souhaitez insérer une séparation sans titre",
    "en": "Leave this field empty if you wish to insert a separation without a title",
    "de": "Lassen Sie dieses Feld leer, wenn Sie eine Trennung ohne Titel einfügen möchten",
    "io": "crwdns32885:0crwdne32885:0",
    "it": "Lasciare questo campo vuoto se si desidera inserire una separazione senza titolo",
    "es": "Deja este campo vacío si deseas insertar una separación sin título",
    "nl": "Laat dit veld leeg als u een scheiding zonder titel wilt invoegen",
    "br": "Lezit ar vaezienn-mañ goullo ma fell deoc'h enlakaat un dispartier hep titl"
  },
  "imageFieldType": {
    "fr": "Image",
    "en": "Image",
    "de": "Bild",
    "es": "Imagen",
    "it": "Immagine",
    "io": "crwdns14770:0crwdne14770:0",
    "oc": "Imatge",
    "nl": "Afbeelding",
    "br": "Skeudenn"
  },
  "unknownFieldType": {
    "fr": "Type inconnu",
    "en": "Unknown type",
    "de": "Unbekannter Typ",
    "es": "Tipo desconocido",
    "it": "Tipo sconosciuto",
    "io": "crwdns14772:0crwdne14772:0",
    "nl": "Onbekend type",
    "br": "Seurt dianav"
  },
  "languagesFieldType": {
    "fr": "Langues de saisie",
    "en": "Input languages",
    "es": "Idiomas de entrada",
    "it": "Lingue di ingresso",
    "de": "Wählen Sie eine Sprache",
    "br": "Choazit ur yezh",
    "io": "crwdns14774:0crwdne14774:0",
    "oc": "Lengas de sasida",
    "nl": "Invoertalen"
  },
  "markdownMultilingualFieldType": {
    "fr": "Texte enrichi multilingue",
    "en": "Multilingual rich text",
    "de": "Mehrsprachiger Rich-Text",
    "es": "Texto enriquecido multilingüe",
    "it": "Testo ricco multilingue",
    "io": "crwdns14776:0crwdne14776:0",
    "nl": "Meertalige opgemaakte tekst",
    "br": "Testenn pinvidikaet liesyezhek"
  },
  "registrationFieldType": {
    "fr": "Liens, téléphone, email",
    "en": "Link, phone, email",
    "de": "Link, telefon, e-mail",
    "es": "Enlaces, teléfono, correo electrónico",
    "it": "Link, telefono, e-mail",
    "io": "crwdns14778:0crwdne14778:0",
    "nl": "Link, telefoon, e-mail",
    "br": "Liamm, pellgomz, postel"
  },
  "locationFieldType": {
    "fr": "Choix du lieu",
    "en": "Location selection",
    "de": "Standortauswahl",
    "es": "Selección del sitio",
    "it": "Scelta della posizione",
    "io": "crwdns14780:0crwdne14780:0",
    "nl": "Locatieselectie",
    "br": "Dibab al lec'h"
  },
  "accessibilityFieldType": {
    "fr": "Choix accessibilité",
    "en": "Accessibility selection",
    "de": "Auswahl der Barrierefreiheit",
    "es": "Elección de la accesibilidad ",
    "it": "Scelta dell'accessibilità",
    "io": "crwdns14782:0crwdne14782:0",
    "nl": "Toegankelijkheidsselectie",
    "br": "Dibab monedusted"
  },
  "timingsFieldType": {
    "fr": "Sélection des horaires",
    "en": "Timings selection",
    "de": "Auswahl der Timings",
    "es": "Sección de selección de horarios",
    "it": "Selezione degli orari",
    "io": "crwdns14784:0crwdne14784:0",
    "nl": "Tijdenselectie",
    "br": "Dibab an eurioù"
  },
  "fileFieldType": {
    "fr": "Fichier",
    "en": "File",
    "de": "Datei",
    "es": "Archivo",
    "it": "Documento",
    "io": "crwdns32887:0crwdne32887:0",
    "nl": "Bestand",
    "br": "Restr"
  },
  "ageFieldType": {
    "fr": "Sélection de la tranche d'âge",
    "en": "Selection of age group",
    "de": "Auswahl der Altersgruppe",
    "es": "Selección de la franja de edad",
    "it": "Selezione della fascia di età",
    "io": "crwdns32889:0crwdne32889:0",
    "nl": "Selectie van leeftijdsgroep",
    "br": "Dibab ar rummad oad"
  },
  "longDescriptionFieldType": {
    "fr": "Champ texte",
    "en": "Text field",
    "de": "Textfeld",
    "es": "Campo de texto",
    "it": "Campo di testo",
    "io": "crwdns32891:0crwdne32891:0",
    "oc": "Camp de tèxte",
    "nl": "Tekstveld",
    "br": "Maezienn destenn"
  },
  "keywordsFieldType": {
    "fr": "Mots clés",
    "en": "Keywords",
    "de": "Schlüsselwörter",
    "es": "Palabras claves",
    "it": "Parole Chiave",
    "oc": "Mots claus",
    "io": "crwdns32893:0crwdne32893:0",
    "nl": "Trefwoorden",
    "br": "Gerioù-alc'hwez"
  },
  "buttonSave": {
    "fr": "Sauvegarder",
    "en": "Save",
    "de": "Zum Schutz",
    "es": "Guardar",
    "it": "Salva",
    "br": "Enrollañ",
    "io": "crwdns14786:0crwdne14786:0",
    "oc": "Enregistrar",
    "nl": "Opslaan"
  },
  "buttonSaved": {
    "fr": "Enregistré",
    "en": "Saved",
    "es": "Guardar",
    "it": "Registrato",
    "de": "Gespeichert",
    "io": "crwdns14788:0crwdne14788:0",
    "oc": "Enregistrat",
    "nl": "Opgeslagen",
    "br": "Enrollet"
  },
  "buttonError": {
    "fr": "Il y a eu un souci lors de la sauvegarde tentez de nouveau dans un instant",
    "en": "There was a problem during save. Try again shortly",
    "de": "Beim Speichern ist ein Problem aufgetreten. Versuchen Sie es in Kürze noch einmal",
    "es": "Ocurrió un error al registrar. Inténtalo nuevamente",
    "it": "C'è stato un problema. Per favore riprovare in un attimo",
    "io": "crwdns14790:0crwdne14790:0",
    "nl": "Er was een probleem tijdens het opslaan. Probeer het over een moment opnieuw",
    "br": "Ur gudenn zo bet pa enrolled. Klaskit en-dro a-benn nebeut"
  },
  "orderCancel": {
    "fr": "Annuler",
    "en": "Cancel",
    "de": "Stornieren",
    "es": "Anular",
    "it": "Annullare",
    "br": "Nullañ",
    "io": "crwdns14792:0crwdne14792:0",
    "oc": "Anullar",
    "nl": "Annuleren"
  },
  "orderEdit": {
    "fr": "Modifier",
    "en": "Edit",
    "de": "Bearbeiten",
    "es": "Editar",
    "it": "Modificare",
    "io": "crwdns14794:0crwdne14794:0",
    "oc": "Modificar",
    "nl": "Bewerken",
    "br": "Aozañ"
  },
  "orderInstruction": {
    "fr": "Glissez-déposez chaque champ dans l'emplacement désiré",
    "en": "Drag and drop fields to the desired position",
    "de": "Ziehen Sie Felder per Drag-and-Drop an die gewünschte Position",
    "es": "Arrastre y suelte cada campo en el lugar deseado",
    "it": "Trascinare i campi nella posizione desiderata",
    "io": "crwdns14796:0crwdne14796:0",
    "nl": "Sleep elk veld naar de gewenste positie",
    "br": "Riklit-dilec'hit pep maezienn d'al lec'h a fell deoc'h"
  },
  "orderSave": {
    "fr": "Appliquer le nouvel ordre",
    "en": "Apply the new order",
    "de": "Wenden Sie die neue Reihenfolge an",
    "es": "Aplicar el nuevo orden",
    "it": "Applicare il nuovo ordine",
    "io": "crwdns14798:0crwdne14798:0",
    "nl": "De nieuwe volgorde toepassen",
    "br": "Arloañ an urzh nevez"
  },
  "orderTitle": {
    "fr": "Ordre des champs",
    "en": "Field order",
    "de": "Feldreihenfolge",
    "es": "Orden de los campos",
    "it": "Ordine dei campi",
    "io": "crwdns14800:0crwdne14800:0",
    "nl": "Veldvolgorde",
    "br": "Urzh ar maeziennoù"
  },
  "fieldFormOptional": {
    "fr": "Ce champ est facultatif",
    "en": "This field is optional",
    "de": "Dieses Feld ist optional",
    "es": "Este campo es opcional",
    "it": "Questo campo è opzionale",
    "io": "crwdns14802:0crwdne14802:0",
    "nl": "Dit veld is optioneel",
    "br": "Diret eo ar vaezienn-mañ"
  },
  "fieldFormAllowFalse": {
    "fr": "Autoriser que ce champ soit non-coché",
    "en": "Allow this field to be unchecked",
    "de": "Falschen Wert zulassen",
    "es": "Permitir valor falso",
    "it": "Consenti valore falso",
    "io": "crwdns35203:0crwdne35203:0"
  },
  "requiredField": {
    "fr": "Obligatoire",
    "en": "Required",
    "es": "Necesario",
    "it": "Obbligatorio",
    "de": "Erforderlich",
    "br": "Rekis",
    "io": "crwdns14804:0crwdne14804:0",
    "oc": "Requesit",
    "nl": "Verplicht"
  },
  "fieldFormMaxTextLength": {
    "fr": "Longueur maximale du texte saisi",
    "en": "Maximum length of the typed text",
    "de": "Maximale Länge des eingegebenen Textes",
    "es": "Longitud máxima del texto introducido",
    "it": "Lunghezza massima del testo inserito",
    "io": "crwdns14806:0crwdne14806:0",
    "nl": "Maximale lengte van de ingevoerde tekst",
    "br": "Ment vrasañ an destenn enanket"
  },
  "fieldFormMinTextLength": {
    "fr": "Longueur minimal du texte saisi",
    "en": "Minimum length of the typed text",
    "de": "Mindestlänge des eingegebenen Textes",
    "es": "Longitud mínima del texto introducido",
    "it": "Lunghezza minima del testo inserito",
    "io": "crwdns14808:0crwdne14808:0",
    "nl": "Minimale lengte van de ingevoerde tekst",
    "br": "Ment vihanañ an destenn enanket"
  },
  "chooseFieldType": {
    "fr": "Type du champ",
    "en": "Field type",
    "de": "Feldtyp",
    "es": "Tipo de campo",
    "it": "Selezione del tipo di campo",
    "io": "crwdns14810:0crwdne14810:0",
    "nl": "Veldtype",
    "br": "Seurt ar vaezienn"
  },
  "chooseFieldTypePlaceholder": {
    "fr": "Choisissez un type de champ",
    "en": "Choose a field type",
    "de": "Wählen Sie einen Feldtyp",
    "io": "crwdns32764:0crwdne32764:0",
    "it": "Selezionare un tipo di campo",
    "es": "Elige un tipo de campo",
    "nl": "Kies een veldtype",
    "br": "Dibabit ur seurt maezienn"
  },
  "chooseOtherType": {
    "fr": "Choisir un autre type",
    "en": "Choose another type",
    "de": "Wählen Sie einen anderen Typ",
    "io": "crwdns32766:0crwdne32766:0",
    "it": "Seleziona un altro tipo",
    "es": "Elige otro tipo",
    "nl": "Kies een ander type",
    "br": "Dibab ur seurt all"
  },
  "isLabelDuplicateError": {
    "fr": "Le titre saisi est déjà pris par un autre champ. Veuillez le modifier avant de retenter l'ajout.",
    "en": "The title for this field is already taken by another of the form. Modify it before trying to add it again.",
    "de": "Der Titel für dieses Feld wird bereits von einem anderen Formular übernommen. Ändern Sie es, bevor Sie versuchen, es erneut hinzuzufügen.",
    "io": "crwdns32768:0crwdne32768:0",
    "it": "Il titolo di questo campo è già occupato da un altro del modulo. Modificarlo prima di provare ad aggiungerlo di nuovo.",
    "es": "El título de este campo ya está siendo usado por otro campo del formulario. Modifícalo antes de intentar agregarlo nuevamente.",
    "nl": "De ingevoerde titel wordt al gebruikt door een ander veld. Wijzig deze voordat u opnieuw probeert toe te voegen.",
    "br": "Kemeret eo an titl enanket gant ur vaezienn all eus ar furmskrid dija. Kemmit anezhañ a-raok klask ouzhpennañ en-dro."
  },
  "isSulgDuplicateError": {
    "fr": "Le slug associé est déjà pris par un autre champ. Veuillez le modifier le titre avant de retenter l'ajout.",
    "en": "The associated slug is already taken by another field. Please modify the title before trying to add it again.",
    "de": "Der zugehörige Slug wird bereits von einem anderen Feld verwendet. Bitte ändern Sie den Titel, bevor Sie versuchen, ihn erneut hinzuzufügen.",
    "es": "El slug asociado ya está siendo usado por otro campo. Por favor, modifica el título antes de intentar agregarlo nuevamente.",
    "it": "Lo slug associato è già utilizzato da un altro campo. Si prega di modificare il titolo prima di riprovare ad aggiungerlo.",
    "io": "crwdns35395:0crwdne35395:0"
  },
  "isReservedError": {
    "fr": "Le slug associé est reservé. Veuillez le modifier le titre avant de retenter l'ajout.",
    "en": "The associated slug is reserved. Please modify the title before trying to add it again.",
    "de": "Der zugehörige Slug ist reserviert. Bitte ändern Sie den Titel, bevor Sie versuchen, ihn erneut hinzuzufügen.",
    "es": "El slug asociado está reservado. Por favor, modifica el título antes de intentar agregarlo nuevamente.",
    "it": "Lo slug associato è riservato. Si prega di modificare il titolo prima di riprovare ad aggiungerlo.",
    "io": "crwdns35397:0crwdne35397:0"
  },
  "confirmFieldType": {
    "fr": "Configurer le champ",
    "en": "Configure the field",
    "de": "Konfigurieren Sie das Feld",
    "es": "Configurar el campo",
    "it": "Configurazione del campo",
    "io": "crwdns14812:0crwdne14812:0",
    "nl": "Het veld configureren",
    "br": "Kefluniañ ar vaezienn"
  },
  "confirmFieldCreate": {
    "fr": "Créer le champ",
    "en": "Create the field",
    "de": "Erstellen Sie das Feld",
    "es": "Crear el campo",
    "it": "Creare il campo",
    "io": "crwdns14814:0crwdne14814:0",
    "nl": "Het veld aanmaken",
    "br": "Krouiñ ar vaezienn"
  },
  "confirmFieldUpdate": {
    "fr": "Modifier",
    "en": "Update",
    "de": "Aktualisieren",
    "es": "Actualizar",
    "it": "Aggiornare",
    "br": "Hizivaat",
    "io": "crwdns14816:0crwdne14816:0",
    "oc": "Metre a jorn",
    "nl": "Wijzigen"
  },
  "backToFieldType": {
    "fr": "Retour au choix du type",
    "en": "Back to field type",
    "de": "Zurück zum Feldtyp",
    "es": "Volver a selección",
    "it": "Torna alla selezione del tipo",
    "io": "crwdns14818:0crwdne14818:0",
    "nl": "Terug naar veldtype",
    "br": "Distro d'an dibab seurt"
  },
  "cancelFieldEdit": {
    "fr": "Annuler",
    "en": "Cancel",
    "de": "Stornieren",
    "es": "Anular",
    "it": "Annullare",
    "br": "Nullañ",
    "io": "crwdns14820:0crwdne14820:0",
    "oc": "Anullar",
    "nl": "Annuleren"
  },
  "optionAdd": {
    "fr": "Ajouter des valeurs",
    "en": "Add values",
    "de": "Werte hinzufügen",
    "es": "Añadir valores",
    "it": "Aggiungere valori",
    "io": "crwdns14822:0crwdne14822:0",
    "nl": "Waarden toevoegen",
    "br": "Ouzhpennañ talvoudoù"
  },
  "optionAddAction": {
    "fr": "Ajouter",
    "en": "Add",
    "de": "Hinzufügen",
    "es": "Añadir",
    "it": "Aggiungere",
    "io": "crwdns14824:0crwdne14824:0",
    "oc": "Apondre",
    "nl": "Toevoegen",
    "br": "Ouzhpennañ"
  },
  "optionUpdateAction": {
    "fr": "Modifier",
    "en": "Update",
    "de": "Aktualisieren",
    "es": "Actualizar",
    "it": "Aggiornare",
    "br": "Hizivaat",
    "io": "crwdns14826:0crwdne14826:0",
    "oc": "Metre a jorn",
    "nl": "Wijzigen"
  },
  "optionEdit": {
    "fr": "Modifier",
    "en": "Edit",
    "de": "Bearbeiten",
    "es": "Editar",
    "it": "Modificare",
    "io": "crwdns14828:0crwdne14828:0",
    "oc": "Modificar",
    "nl": "Bewerken",
    "br": "Aozañ"
  },
  "optionEditCancel": {
    "fr": "Annuler",
    "en": "Cancel",
    "de": "Stornieren",
    "es": "Anular",
    "it": "Annullare",
    "br": "Nullañ",
    "io": "crwdns14830:0crwdne14830:0",
    "oc": "Anullar",
    "nl": "Annuleren"
  },
  "optionDrag": {
    "fr": "Trier",
    "en": "Sort",
    "de": "Sortieren",
    "es": "Clasificar",
    "it": "Ordina",
    "io": "crwdns14832:0crwdne14832:0",
    "nl": "Sorteren",
    "br": "Rummañ"
  },
  "optionOrder": {
    "fr": "Modifier l'ordre",
    "en": "Change order",
    "de": "Bestellung ändern",
    "es": "Cambiar orden",
    "it": "Ordina",
    "br": "Cheñch an urzh",
    "io": "crwdns14834:0crwdne14834:0",
    "oc": "Cambiar l'òrdre",
    "nl": "Volgorde wijzigen"
  },
  "optionRemove": {
    "fr": "Retirer",
    "en": "Remove",
    "de": "Entfernen",
    "es": "Eliminar",
    "it": "Rimuovere",
    "br": "Lemel",
    "io": "crwdns14836:0crwdne14836:0",
    "oc": "Suprimir",
    "nl": "Verwijderen"
  },
  "optionOrderEndAction": {
    "fr": "Terminer le tri",
    "en": "End re-ordering",
    "de": "Nachbestellung beenden",
    "es": "Finalizar el cambio de orden",
    "it": "Finire la cernita",
    "io": "crwdns14838:0crwdne14838:0",
    "nl": "Sorteren beëindigen",
    "br": "Echuiñ ar rummañ"
  },
  "emptyOptions": {
    "fr": "Aucune valeur n'est encore définie",
    "en": "No option is defined yet",
    "de": "Es ist noch keine Option definiert",
    "es": "Ningún valor se ha definido todavía",
    "it": "Nessun valore è ancora definito",
    "io": "crwdns14840:0crwdne14840:0",
    "nl": "Er is nog geen waarde gedefinieerd",
    "br": "N'eus dibab ebet termenet c'hoazh"
  },
  "optionDuplicateError": {
    "fr": "Cette valeur est déjà existante",
    "en": "This value already exists",
    "de": "Dieser Wert existiert bereits",
    "es": "Este valor ya existe",
    "it": "Questo valore esiste già",
    "io": "crwdns14842:0crwdne14842:0",
    "nl": "Deze waarde bestaat al",
    "br": "An talvoud-mañ zo anezhañ dija"
  },
  "optionEmptyError": {
    "fr": "Les valeurs ne doivent pas être vides",
    "en": "Values cannot be empty",
    "de": "Werte dürfen nicht leer sein",
    "es": "Los valores no pueden estar vacíos",
    "it": "I valori non devono essere vuoti",
    "io": "crwdns14844:0crwdne14844:0",
    "nl": "Waarden mogen niet leeg zijn",
    "br": "Ne c'hall ket an talvoudoù bezañ goullo"
  },
  "requiredError": {
    "fr": "Tous les champs sont obligatoires",
    "en": "All fields are required",
    "de": "alle Felder sind erforderlich",
    "es": "Todos los campos son requeridos",
    "it": "Tutti i campi sono obbligatori",
    "io": "crwdns14846:0crwdne14846:0",
    "nl": "Alle velden zijn verplicht",
    "br": "Ret eo leuniañ an holl vaeziennoù"
  },
  "moreOptions": {
    "fr": "choix",
    "en": "choices",
    "de": "Entscheidungen",
    "es": "opciones",
    "it": "scelte",
    "io": "crwdns32895:0crwdne32895:0",
    "nl": "keuzes",
    "br": "dibab"
  },
  "isMultilingual": {
    "fr": "Multilingue",
    "en": "Multilingual",
    "de": "Mehrsprachig",
    "es": "Multilingüe",
    "it": "Multilingue",
    "io": "crwdns32897:0crwdne32897:0",
    "nl": "Meertalig",
    "br": "Liesyezhek"
  },
  "defaultValue": {
    "fr": "Valeur par défaut",
    "en": "Default value",
    "de": "Standardwert",
    "es": "Valor por defecto",
    "it": "Valore per difetto",
    "io": "crwdns32899:0crwdne32899:0",
    "nl": "Standaardwaarde",
    "br": "Talvoud dre ziouer"
  },
  "maxLength": {
    "fr": "Longueur max",
    "en": "Max length",
    "de": "Maximale länge",
    "es": "Longitud máxima",
    "it": "Lunghezza max",
    "io": "crwdns32901:0crwdne32901:0",
    "nl": "Max lengte",
    "br": "Ment vrasañ"
  },
  "jsonKey": {
    "fr": "Clé JSON",
    "en": "JSON key",
    "de": "JSON-Schlüssel",
    "es": "Clave JSON",
    "it": "chiave JSON",
    "io": "crwdns32903:0crwdne32903:0",
    "nl": "JSON-sleutel",
    "br": "Alc'hwez JSON"
  },
  "isSelected": {
    "fr": "Sélectionné",
    "en": "Selected",
    "es": "Seleccionado",
    "it": "Selezionato",
    "oc": "Seleccionat",
    "io": "crwdns32905:0crwdne32905:0",
    "de": "Auswählen",
    "nl": "Geselecteerd",
    "br": "Diuzet"
  },
  "notSelected": {
    "fr": "Non sélectionné",
    "en": "Not selected",
    "es": "No seleccionado",
    "it": "Non selezionato",
    "oc": "Pas seleccionat",
    "io": "crwdns32907:0crwdne32907:0",
    "de": "Nicht ausgewählt",
    "nl": "Niet geselecteerd",
    "br": "Ket diuzet"
  },
  "enabledWhenLinkedFieldHasValue": {
    "fr": "Actif lorsque le champ %linkedFieldName% est saisi",
    "en": "Active when %linkedFieldName% field is entered",
    "de": "Aktiv, wenn das Feld %linkedFieldName% eingegeben wird",
    "es": "Activo cuando el campo %linkedFieldName% está llenado",
    "it": "Attivo quando viene inserito il campo %linkedFieldName%",
    "io": "crwdns32909:0%linkedFieldName%crwdne32909:0",
    "nl": "Actief wanneer het veld %linkedFieldName% is ingevuld",
    "br": "Oberiant pa vez leuniet ar vaezienn %linkedFieldName%"
  },
  "enabledWhenLinkedFieldHasSpecificValue": {
    "fr": "Actif lorsque le champ %linkedFieldName% prend la valeur %specificValue%",
    "en": "Active when the %linkedFieldName% field is set to %specificValue%",
    "de": "Aktiv, wenn das Feld %linkedFieldName% auf %specificValue% gesetzt ist",
    "es": "Activo cuando el campo %linkedFieldName% toma el valor %specificValue%",
    "it": "Attivo quando il campo %linkedFieldName% assume il valore %specificValue%",
    "io": "crwdns32911:0%linkedFieldName%crwdnd32911:0%specificValue%crwdne32911:0",
    "nl": "Actief wanneer het veld %linkedFieldName% is ingesteld op %specificValue%",
    "br": "Oberiant pa vez lakaet ar vaezienn %linkedFieldName% da %specificValue%"
  },
  "optionalWhenLinkedFieldHasValue": {
    "fr": "Optionnel lorsque le champ %linkedFieldName% est saisi",
    "en": "Optional when the field %linkedFieldName% is entered",
    "de": "Optional, wenn das Feld %linkedFieldName% eingegeben wird",
    "es": "Opcional cuando el campo %linkedFieldName% está llenado",
    "it": "Opzionale quando viene inserito il campo %linkedFieldName%",
    "io": "crwdns32913:0%linkedFieldName%crwdne32913:0",
    "nl": "Optioneel wanneer het veld %linkedFieldName% is ingevuld",
    "br": "Diret pa vez leuniet ar vaezienn %linkedFieldName%"
  },
  "optionalWhenLinkedFieldHasSpecificValue": {
    "fr": "Optionnel lorsque le champ %linkedFieldName% prend la valeur %specificValue%",
    "en": "Optional when the %linkedFieldName% field is set to %specificValue%",
    "de": "Optional, wenn das Feld %linkedFieldName% auf %specificValue% gesetzt ist.",
    "es": "Opcional cuando el campo %linkedFieldName% toma el valor %specificValue%",
    "it": "Opzionale quando il campo %linkedFieldName% assume il valore %specificValue%",
    "io": "crwdns32915:0%linkedFieldName%crwdnd32915:0%specificValue%crwdne32915:0",
    "nl": "Optioneel wanneer het veld %linkedFieldName% is ingesteld op %specificValue%",
    "br": "Diret pa vez lakaet ar vaezienn %linkedFieldName% da %specificValue%"
  },
  "linkedTo": {
    "fr": "Lié au champ %fieldName%",
    "en": "Linked to %fieldName% field",
    "de": "Mit dem Feld %fieldName% verknüpft",
    "es": "Relacionado con el campo %fieldName%",
    "it": "Relativo al campo %fieldName%",
    "io": "crwdns32917:0%fieldName%crwdne32917:0",
    "nl": "Gekoppeld aan veld %fieldName%",
    "br": "Liammet ouzh ar vaezienn %fieldName%"
  },
  "fieldConditionalSection": {
    "fr": "Logique conditionnelle",
    "en": "Conditional logic",
    "de": "Bedingte Logik",
    "es": "Lógica condicional",
    "it": "Logica condizionale",
    "nl": "Voorwaardelijke logica",
    "br": "Poellata diviz",
    "oc": "Logica condicionala"
  },
  "fieldConditionalSectionInfo": {
    "fr": "Active ou rend optionnel ce champ en fonction d’un autre champ du formulaire",
    "en": "Enable or make this field optional based on another field in the form",
    "de": "Aktiviert dieses Feld oder macht es optional in Abhängigkeit von einem anderen Feld des Formulars",
    "es": "Activa o hace opcional este campo en función de otro campo del formulario",
    "it": "Attiva o rende opzionale questo campo in base a un altro campo del modulo",
    "nl": "Activeer dit veld of maak het optioneel op basis van een ander veld in het formulier",
    "br": "Aktivañ pe lakaat diret ar vaezienn-mañ hervez ur vaezienn all eus ar furmskrid",
    "oc": "Activa o rend opcional aqueste camp en foncion d’un autre camp del formulari"
  },
  "fieldConditionalSectionDisabledReason": {
    "fr": "Ce champ est hérité, il ne peut être conditionné.",
    "en": "This field is inherited and cannot be conditioned.",
    "de": "Dieses Feld ist geerbt und kann nicht bedingt gemacht werden.",
    "es": "Este campo es heredado y no puede condicionarse.",
    "it": "Questo campo è ereditato e non può essere condizionato.",
    "nl": "Dit veld is overgeërfd en kan niet voorwaardelijk worden gemaakt.",
    "br": "Hêret eo ar vaezienn-mañ ha ne c’hell ket bezañ diviz.",
    "oc": "Aqueste camp es eretat e pòt pas èsser condicionat."
  },
  "fieldConditionalModeNone": {
    "fr": "Aucune",
    "en": "None",
    "de": "Keine",
    "es": "Ninguna",
    "it": "Nessuna",
    "nl": "Geen",
    "br": "Hini ebet",
    "oc": "Cap"
  },
  "fieldConditionalModeEnable": {
    "fr": "Activé uniquement quand…",
    "en": "Active only when…",
    "de": "Nur aktiv, wenn…",
    "es": "Activo solo cuando…",
    "it": "Attivo solo quando…",
    "nl": "Alleen actief wanneer…",
    "br": "Oberiant nemet pa…",
    "oc": "Actiu solament quand…"
  },
  "fieldConditionalModeOptional": {
    "fr": "Optionnel uniquement quand…",
    "en": "Optional only when…",
    "de": "Optional nur, wenn…",
    "es": "Opcional solo cuando…",
    "it": "Opzionale solo quando…",
    "nl": "Alleen optioneel wanneer…",
    "br": "Diret pa…",
    "oc": "Opcional solament quand…"
  },
  "fieldConditionalLinkedFieldLabel": {
    "fr": "Champ lié",
    "en": "Linked field",
    "de": "Verknüpftes Feld",
    "es": "Campo vinculado",
    "it": "Campo collegato",
    "nl": "Gekoppeld veld",
    "br": "Maezienn liammet",
    "oc": "Camp ligat"
  },
  "fieldConditionalLinkedFieldPlaceholder": {
    "fr": "Choisir un champ…",
    "en": "Choose a field…",
    "de": "Feld auswählen…",
    "es": "Elegir un campo…",
    "it": "Scegli un campo…",
    "nl": "Kies een veld…",
    "br": "Dibab ur vaezienn…",
    "oc": "Causir un camp…"
  },
  "fieldConditionalLinkedFieldMissing": {
    "fr": "Le champ lié n’existe plus",
    "en": "Linked field no longer exists",
    "de": "Das verknüpfte Feld existiert nicht mehr",
    "es": "El campo vinculado ya no existe",
    "it": "Il campo collegato non esiste più",
    "nl": "Het gekoppelde veld bestaat niet meer",
    "br": "N’eus mui eus ar vaezienn liammet",
    "oc": "Lo camp ligat existís pas mai"
  },
  "fieldConditionalClearLink": {
    "fr": "Supprimer le lien",
    "en": "Clear link",
    "de": "Verknüpfung entfernen",
    "es": "Eliminar el vínculo",
    "it": "Rimuovi il collegamento",
    "nl": "Koppeling wissen",
    "br": "Dilemel al liamm",
    "oc": "Suprimir lo ligam"
  },
  "fieldConditionalTriggerAnyValue": {
    "fr": "Lorsque le champ est renseigné",
    "en": "When the field has any value",
    "de": "Wenn das Feld einen Wert hat",
    "es": "Cuando el campo tiene cualquier valor",
    "it": "Quando il campo ha un valore qualsiasi",
    "nl": "Wanneer het veld een waarde heeft",
    "br": "Pa vez leuniet ar vaezienn",
    "oc": "Quand lo camp es entresenhat"
  },
  "fieldConditionalTriggerSpecificValue": {
    "fr": "Lorsque le champ prend une valeur spécifique",
    "en": "When the field has a specific value",
    "de": "Wenn das Feld einen bestimmten Wert hat",
    "es": "Cuando el campo tiene un valor específico",
    "it": "Quando il campo ha un valore specifico",
    "nl": "Wanneer het veld een specifieke waarde heeft",
    "br": "Pa vez lakaet ar vaezienn da ur werzh dibar",
    "oc": "Quand lo camp pren una valor especifica"
  },
  "fieldConditionalTriggerSpecificValueDisabled": {
    "fr": "Disponible uniquement pour les champs avec options",
    "en": "Only available for fields with options",
    "de": "Nur für Felder mit Optionen verfügbar",
    "es": "Solo disponible para campos con opciones",
    "it": "Disponibile solo per i campi con opzioni",
    "nl": "Alleen beschikbaar voor velden met opties",
    "br": "Hegerz nemet evit ar maeziennoù gant dibaboù",
    "oc": "Disponible solament pels camps amb opcions"
  },
  "fieldConditionalValueLabel": {
    "fr": "Valeur(s)",
    "en": "Value(s)",
    "de": "Wert(e)",
    "es": "Valor(es)",
    "it": "Valore(i)",
    "nl": "Waarde(n)",
    "br": "Gwerzh(ioù)",
    "oc": "Valor(s)"
  },
  "fieldConditionalSelfReferenceError": {
    "fr": "Un champ ne peut pas dépendre de lui-même",
    "en": "A field cannot depend on itself",
    "de": "Ein Feld kann nicht von sich selbst abhängen",
    "es": "Un campo no puede depender de sí mismo",
    "it": "Un campo non può dipendere da sé stesso",
    "nl": "Een veld kan niet van zichzelf afhangen",
    "br": "Ne c’hell ket ur vaezienn bezañ liammet outi he-unan",
    "oc": "Un camp pòt pas dependre d’el meteis"
  },
  "fieldConditionalCycleError": {
    "fr": "Ce lien créerait une dépendance circulaire",
    "en": "This link would create a circular dependency",
    "de": "Diese Verknüpfung würde eine zirkuläre Abhängigkeit erzeugen",
    "es": "Este vínculo crearía una dependencia circular",
    "it": "Questo collegamento creerebbe una dipendenza circolare",
    "nl": "Deze koppeling zou een cirkelvormige afhankelijkheid veroorzaken",
    "br": "Krouiñ a rafe al liamm-mañ un dalc’h kelc’hiek",
    "oc": "Aqueste ligam crearià una dependéncia circulara"
  },
  "fieldConditionalMissingFieldError": {
    "fr": "Veuillez choisir un champ lié",
    "en": "Please choose a linked field",
    "de": "Bitte ein verknüpftes Feld auswählen",
    "es": "Por favor, elija un campo vinculado",
    "it": "Si prega di scegliere un campo collegato",
    "nl": "Kies een gekoppeld veld",
    "br": "Dibabit ur vaezienn liammet, mar plij",
    "oc": "Causissètz un camp ligat, se vos plai"
  },
  "fieldConditionalMissingValueError": {
    "fr": "Veuillez choisir au moins une valeur",
    "en": "Please choose at least one value",
    "de": "Bitte mindestens einen Wert auswählen",
    "es": "Por favor, elija al menos un valor",
    "it": "Si prega di scegliere almeno un valore",
    "nl": "Kies ten minste één waarde",
    "br": "Dibabit ul lamm da nebeutañ, mar plij",
    "oc": "Causissètz al mens una valor, se vos plai"
  },
  "fieldConditionalBooleanTrue": {
    "fr": "Coché",
    "en": "Checked",
    "de": "Aktiviert",
    "es": "Marcado",
    "it": "Selezionato",
    "nl": "Aangevinkt",
    "br": "Kevreet",
    "oc": "Marcat"
  },
  "fieldConditionalBooleanFalse": {
    "fr": "Non coché",
    "en": "Unchecked",
    "de": "Nicht aktiviert",
    "es": "No marcado",
    "it": "Non selezionato",
    "nl": "Niet aangevinkt",
    "br": "Diget kevreet",
    "oc": "Pas marcat"
  },
  "readAccess": {
    "fr": "Lecture",
    "en": "Read",
    "de": "Lesen",
    "es": "Lectura",
    "it": "Lettura",
    "io": "crwdns33227:0crwdne33227:0",
    "nl": "Lezen",
    "br": "Lenn"
  },
  "writeAccess": {
    "fr": "Écriture",
    "en": "Write",
    "de": "Schreiben",
    "es": "Escritura",
    "it": "Scrittura",
    "io": "crwdns33229:0crwdne33229:0",
    "nl": "Schrijven",
    "br": "Skrivañ"
  },
  "adminAccess": {
    "fr": "administrateur",
    "en": "adminitrator",
    "de": "administrator",
    "es": "administrador",
    "it": "administratore",
    "io": "crwdns33231:0crwdne33231:0",
    "nl": "beheerder",
    "br": "merour"
  },
  "moderatorAccess": {
    "fr": "moderateur",
    "en": "moderator",
    "de": "moderator",
    "es": "moderador",
    "it": "moderatore",
    "io": "crwdns33233:0crwdne33233:0",
    "oc": "moderator·a",
    "nl": "moderator",
    "br": "habaskour"
  },
  "contributorAccess": {
    "fr": "contributeur",
    "en": "contributor",
    "de": "mitwirkender",
    "es": "contribuyente",
    "it": "contributore",
    "io": "crwdns33235:0crwdne33235:0",
    "oc": "contributor·a",
    "nl": "bijdrager",
    "br": "kenlabourer"
  }
}
