"use strict";

const TYPES = {
  SET_APP_SETTINGS: 'SET_APP_SETTINGS',
  SET_LOADING: 'SET_LOADING',

  GET_ME: 'GET_ME',
  UPDATE_USER: 'UPDATE_USER',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  GENERATE_APIKEY: 'GENERATE_APIKEY',
  DISPLAY_DELETE_ACCOUNT_CONFIRMATION: 'DISPLAY_DELETE_ACCOUNT_CONFIRMATION',
  DISPLAY_MODAL: 'DISPLAY_MODAL',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
};

module.exports = TYPES;
