module.exports = ({ labels }) => [{
  field: 'id',
  fieldType: 'integer',
  optional: false,
  read: ['internal'],
  write: ['internal']
}, {
  field: 'uid',
  fieldType: 'integer',
  optional: false,
  write: ['internal']
}, {
  field: 'slug',
  fieldType: 'text',
  optional: false,
  write: ['internal']
}, {
  field: 'private',
  fieldType: 'boolean',
  default: false,
  write: ['internal']
}, {
  field: 'timezone',
  fieldType: 'text',
  write: ['internal']
}, {
  field: 'draft',
  fieldType: 'boolean',
  default: false,
  write: ['internal']
}, {
  field: 'createdAt',
  fieldType: 'date',
  write: ['internal']
}, {
  field: 'creatorUid',
  fieldType: 'integer',
  write: ['internal']
}, {
  field: 'ownerUid',
  fieldType: 'integer',
  write: ['internal']
}, {
  field: 'updatedAt',
  fieldType: 'date',
  write: ['internal']
}, {
  field: 'agendaUid',
  fieldType: 'integer',
  optional: false,
  write: ['internal']
}, {
  field: 'fileKey',
  fieldType: 'text',
  write: ['internal']
}, {
  field: 'locationUid',
  fieldType: 'integer',
  optional: false,
  write: ['internal']
}, {
  field: 'image',
  fieldType: 'image',
  optional: true,
  label: labels?.image,
  info: labels?.imageInfo,
  allowURL: true,
  allowPath: true,
  imageWithSizeAndVariants: true,
  extensions: ['jpg', 'bmp', 'png', 'jpeg', 'webp']
}, {
  field: 'imageCredits',
  fieldType: 'text',
  optional: true,
  label: labels?.imageCredits,
  enableWith: 'image',
  max: 255
}, {
  field: 'languages',
  fieldType: 'languages',
  label: labels?.languages
}, {
  languages: [],
  field: 'title',
  fieldType: 'text',
  optional: false,
  max: 140,
  label: labels?.title,
  placeholder: labels?.titlePlaceholder,
  purpose: labels?.titlePurpose,
  sub: labels?.titleSub
}, {
  languages: [],
  field: 'description',
  fieldType: 'text',
  optional: false,
  max: 200,
  label: labels?.description,
  purpose: labels?.descriptionPurpose,
  placeholder: labels?.descriptionPlaceholder,
  sub: labels?.descriptionSub
}, {
  languages: [],
  field: 'keywords',
  fieldType: 'keywords',
  optional: true,
  max: 255,
  label: labels?.keywords,
  placeholder: labels?.keywordsPlaceholder,
  sub: labels?.keywordsSub
}, {
  languages: [],
  field: 'longDescription',
  fieldType: 'longDescription',
  label: labels?.longDescription,
  max: 10000,
  sub: labels?.longDescriptionSub,
  placeholder: labels?.longDescriptionPlaceholder
}, {
  languages: [],
  field: 'conditions',
  fieldType: 'text',
  label: labels?.conditions,
  max: 255,
  placeholder: labels?.conditionsPlaceholder,
  sub: labels?.conditionsSub
}, {
  field: 'age',
  fieldType: 'age',
  optional: true,
  label: labels?.age
}, {
  field: 'registration',
  fieldType: 'registration',
  optional: true,
  label: labels?.registration,
  info: labels?.registrationInfo,
  placeholder: labels?.registrationPlaceholder,
  sub: labels?.registrationSub
}, {
  field: 'accessibility',
  fieldType: 'accessibility',
  optional: true,
  label: labels?.accessibility
}, {
  display: false,
  field: 'attendanceMode',
  fieldType: 'radio',
  label: labels?.attendanceMode,
  optional: false,
  default: 1,
  options: [{
    id: 1,
    value: 'offline',
    label: labels?.offlineAttendanceMode,
    info: labels?.offlineAttendanceModeInfo
  }, {
    id: 2,
    value: 'online',
    label: labels?.onlineAttendanceMode,
    info: labels?.onlineAttendanceModeInfo
  }, {
    id: 3,
    value: 'mixed',
    label: labels?.mixedAttendanceMode,
    info: labels?.mixedAttendanceModeInfo
  }]
}, {
  field: 'location',
  fieldType: 'location',
  label: labels?.location,
  sub: labels?.locationSub,
  optionalWith: {
    field: 'attendanceMode',
    value: 2
  },
  disableChange: false
}, {
  display: false,
  field: 'onlineAccessLink',
  fieldType: 'link',
  label: labels?.onlineAccessLink,
  optional: false,
  enableWith: {
    field: 'attendanceMode',
    value: [2, 3]
  }
}, {
  field: 'status',
  fieldType: 'select',
  default: 1,
  display: false,
  label: labels?.status,
  options: [{
    id: 1,
    value: 'scheduled',
    label: labels?.scheduled
  }, {
    id: 2,
    value: 'rescheduled',
    label: labels?.rescheduled
  }, {
    id: 3,
    value: 'movedOnline',
    label: labels?.movedOnline
  }, {
    id: 4,
    value: 'postponed',
    label: labels?.postponed
  }, {
    id: 5,
    value: 'full',
    label: labels?.full
  }, {
    id: 6,
    value: 'cancelled',
    label: labels?.cancelled
  }]
}, {
  field: 'references',
  fieldType: 'integer',
  list: true,
  optional: true,
  write: ['internal']
}, {
  field: 'timings',
  fieldType: 'timings',
  max: 800,
  optional: false,
  label: labels?.timings,
  info: labels?.timingsInfo,
  helpLink: 'https://doc.openagenda.com/saisir-les-horaires-de-votre-evenement/'
}, {
  field: 'links',
  fieldType: 'integer',
  optional: false,
  write: ['internal']
}];
