"use strict";

const TYPES = {
  SET_APP_SETTINGS: 'SET_APP_SETTINGS',
  LOADING: 'LOADING',
  
  GET_ME: 'GET_ME',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'
};

module.exports = TYPES;