# Docker DNS
resolver 127.0.0.11 valid=10s ipv6=off;

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

map $http_x_forwarded_proto $real_scheme {
  default $http_x_forwarded_proto;
  '' $scheme;
}
