server {
  listen 443;
  server_name ${ELASTICHQ_DOMAIN};

  ssl_certificate /ssl/elastichq.cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/elastichq.key.pem; # managed by Certbot

  ${CLIENT_SSL_NGINX_CONF}

  location / {
    proxy_pass http://elastichq:5000;
    proxy_set_header  X-Forwarded-Proto $scheme;
  }
}
