server {
  server_name ${ES1_DOMAIN};

  listen 443 ssl; # managed by Certbot
  ssl_certificate /ssl/es1.cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/es1.key.pem; # managed by Certbot

  ssl_client_certificate /ssl/client.crt;
  ssl_verify_client on;

  location / {
    proxy_pass http://${ES1_HOST}:9200;
  }
}

server {
  server_name ${ES7_DOMAIN};

  listen 443 ssl; # managed by Certbot
  ssl_certificate /ssl/es7.cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/es7.key.pem; # managed by Certbot

  ssl_client_certificate /ssl/client.crt;
  ssl_verify_client on;

  location / {
    proxy_pass http://${ES7_HOST}:9200;
  }
}
