server {
  server_name ${ES_DOMAIN};

  listen 443 ssl; # managed by Certbot
  ssl_certificate /ssl/es7.cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/es7.key.pem; # managed by Certbot

  ssl_client_certificate /ssl/client.crt;
  ssl_verify_client on;

  location / {
    proxy_pass http://${ES_HOST}:9200;
  }
}
