server {
  listen 443 ssl; # managed by Certbot

  server_name ${MAILCATCHER_DOMAIN};

  ssl_certificate /ssl/mailcatcher.cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/mailcatcher.key.pem; # managed by Certbot

  ${CLIENT_SSL_NGINX_CONF}

  location / {
    proxy_pass http://mailcatcher:1080;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
  }
}
