server {
  listen 80;
  server_name ${SITE_DOMAIN};
  include conf.d/server_params;
}

server {
  listen [::]:443 ssl ipv6only=on; # managed by Certbot
  listen 443 ssl; # managed by Certbot

  server_name ${SITE_DOMAIN};

  ssl_certificate /ssl/cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/key.pem; # managed by Certbot

  ssl_client_certificate /ssl/client.crt;
  ssl_verify_client on;

  include conf.d/server_params;
}
