server {
  listen 80;

  server_name ${SITE_DOMAIN};

  if ($real_scheme != "https") {
    return 301 https://$server_name$request_uri;
  }

  include conf.d/server_params_dev;
  include conf.d/server_params;
}

server {
  listen [::]:443 ssl ipv6only=on; # managed by Certbot
  listen 443 ssl default_server; # managed by Certbot

  server_name ${SITE_DOMAIN};

  ssl_certificate /ssl/cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/key.pem; # managed by Certbot

  ${CLIENT_SSL_NGINX_CONF}

  include conf.d/server_params_dev;
  include conf.d/server_params;
}
