server {
  listen 443;
  server_name ${PMA_HOST};

  ssl_certificate /ssl/pma.cert.pem; # managed by Certbot
  ssl_certificate_key /ssl/pma.key.pem; # managed by Certbot

  ${CLIENT_SSL_NGINX_CONF}

  location / {
    proxy_pass http://phpmyadmin;
    proxy_set_header  X-Forwarded-Proto $scheme;
  }
}
