"use strict";

const path = require( 'path' );
const _ = require( 'lodash' );
const React = require( 'react' );
const ReactDOM = require( 'react-dom/server' );
const ReactIs = require( 'react-is' );
const { createMemoryHistory } = require( 'history' );
const { stringify } = require( 'flatted/cjs' );
const he = require( 'he' );
const { ChunkExtractor } = require( '@loadable/server' );
const wrapApp = require( '@openagenda/react-utils/dist/wrapApp' );
const { matchRoutes } = require( '@openagenda/react-utils/dist/asyncMatchRoutes' );
const { Html, HeaderManager, Header } = require( '@openagenda/react-layouts' );
const createHomeApp = require( '@openagenda/home/dist/app' );
const createUserSettingsApp = require( '@openagenda/user-apps/dist/app' );
const createAgendaSettingsNewApp = require( '@openagenda/agenda-settings/dist/client/createApp' );
const createActivitiesApp = require( '@openagenda/activity-apps/dist/client/apps/user' );

module.exports = function match( { initialState, apiRoot, lang } ) {
  return async ( req, res, next ) => {
    try {
      // We create an extractor from the statsFile (generated by webpack loadable plugin)
      const extractor = new ChunkExtractor( {
          statsFile: path.join( __dirname, '/dist/loadable-stats.json' ),
          entrypoints: [ 'webapp' ]
        }
      );

      const history = createMemoryHistory( { initialEntries: [ req.originalUrl ] } );
      const state = typeof initialState === 'function' ? initialState(req) : initialState;

      const apps = {
        home: createHomeApp( {
          req,
          // Header: () => React.createElement( HeaderSelector, { type: 'main' } ),
          history,
          initialState: state.home
        } ),
        userSettings: createUserSettingsApp( {
          req,
          history,
          initialState: state.userSettings
        } ),
        agendaSettingsNew: createAgendaSettingsNewApp( {
          req,
          history,
          initialState: state.agendaSettingsNew
        } ),
        userActivities: createActivitiesApp( {
          req,
          history,
          initialState: state.userActivities
        } )
      };

      // Not found
      const notFound = Object.values( apps )
        .every( app =>
          !(app.routes && matchRoutes( app.routes, history.location.pathname ).length)
        );

      if ( notFound ) {
        return next();
      }

      // Triggers hooks
      await Promise.all(
        Object.values( apps )
          .filter( v => v.triggerHooks )
          .map( v => v
            .triggerHooks()
            .catch( err => console.log( `Error in triggerHooks:`, err ) )
          )
      );

      // Check if redirect in hooks
      if ( redirectIfNeeded( req, res, history ) ) {
        return;
      }

      // Create store for the header
      const headerStore = HeaderManager.createStore( {
        header: {
          apiRoot,
          user: req.user
        },
        res: {
          hasInboxNews: '/latest-inbox-timestamp',
          notificationsCount: '/notifications/count'
        }
      } );

      const triggerHooks = () => Promise.all(
        Object.values( apps ).map( app => app.triggerHooks() )
      );

      const staticContext = {};
      const element = wrapApp(
        {
          Content: () => Object.values( apps )
            .map( ( { Content }, i ) =>
              ReactIs.isValidElementType( Content ) ? React.createElement( Content, { key: i } ) : Content
            ),
          history,
          triggerHooks
        },
        { req, staticContext, extractor }
      );

      const content = ReactDOM.renderToString( React.createElement(
        HeaderManager,
        { store: headerStore },
        element
      ) );

      if ( staticContext.url ) {
        return res.redirect( staticContext.status || 302, staticContext.url );
      }

      // Check if location change anywhere else
      if ( redirectIfNeeded( req, res, history ) ) {
        return;
      }

      // Get initialStateForClient
      const initialStateForClient = _.mapValues( apps, app => {
        const state = app.store.getState();

        // Avoid all settings.apiRoot
        if ( _.get( state, 'settings.apiRoot' ) ) {
          _.set( state, 'settings.apiRoot', '' );
        }

        return state;
      } );

      initialStateForClient.header = headerStore.getState();
      _.set( initialStateForClient.header, 'header.apiRoot', '' );

      const headerType = headerStore.getState().header.type;
      const headerHtml = ReactDOM.renderToString( React.createElement(
        Header,
        { store: headerStore, type: headerType }
      ) );

      const serializedInitialState = he.encode(stringify(initialStateForClient));

      // Send Html
      const html = React.createElement( Html, {
        content: headerHtml + content,
        initialState: serializedInitialState,
        lang,
        extractor
      } );
      res.status( 200 ).send( `<!doctype html>${ReactDOM.renderToString( html )}` );
    } catch ( e ) {
      next( e );
    }
  };
};

function redirectIfNeeded( req, res, history ) {
  const { pathname, search } = history.location;

  if ( decodeURIComponent( req.originalUrl ) !== decodeURIComponent( pathname + search ) ) {
    res.redirect( 302, pathname + search );
    return true;
  }
}
