import fs from 'node:fs';
import path from 'node:path';
import _ from 'lodash';
import React from 'react';
import ReactDOM from 'react-dom/server';
import { QueryClient, QueryClientProvider } from 'react-query';
import { HelmetProvider } from 'react-helmet-async';
import { matchRoutes } from 'react-router-config';
import { createMemoryHistory } from 'history';
import flatted from 'flatted/cjs/index.js';
import he from 'he';
import { ErrorBoundary } from '@sentry/react';
import { ChunkExtractor } from '@loadable/server';
import { wrapApp } from '@openagenda/react-shared';
import {
  Html,
  LayoutManager,
  createLayoutStore,
} from '@openagenda/react-layouts';

import {
  AgendaAdminDataLayout,
  AgendaDataLayout,
  AgendaAdminFiltersLayout,
  AgendaAdminLayout,
  AgendaLayout,
  InboxUserLayout,
  InboxAgendaAdminLayout,
  MainLayout,
  RequiredSuperAdmin,
  RequiredUser,
} from '@openagenda/react-layouts/layouts';

import createHomeApp from '@openagenda/home/dist/app.js';
import createUserSettingsApp from '@openagenda/user-apps';
import createAgendaSettingsNewApp from '@openagenda/agenda-settings/createApp';
import createAgendaSettingsEditApp from '@openagenda/agenda-settings/editApp';
import createUserActivitiesApp from '@openagenda/activity-apps/dist/client/apps/user/index.js';
import createAgendaActivitiesApp from '@openagenda/activity-apps/dist/client/apps/agenda/index.js';
import createAggregatorSourcesApp from '@openagenda/aggregator-sources/dist/app.js';
import createAgendaStatsApp from '@openagenda/agenda-stats';
import createInboxApp from '@openagenda/inbox-apps/dist/app.js';
import createMembersApp from '@openagenda/member-apps/dist/app.js';
import createLegacyEmbedsApp from '@openagenda/legacy/embeds/app/dist/index.js';
import createAgendaContributeApp from '@openagenda/agenda-contribute';
import createEventAdminApp from '@openagenda/event-admin-apps';
import createAgendaLocationAdminApp from '@openagenda/agenda-locations-app/dist/app.js';
import createAgendaSchemaAdminApp from '@openagenda/agenda-schemas-app';
import createSupervisorApp from '@openagenda/supervisor';
import RootHelmet from './RootHelmet.js';
import createReduxMiddleware from './reduxMiddleware.js';

const { createElement: el } = React;
const { stringify } = flatted;

const statsPath = path.join(import.meta.dirname, '/dist/loadable-stats.json');
const stats = JSON.parse(fs.readFileSync(statsPath, 'utf-8'));

async function getStats() {
  if (process.env.NODE_ENV === 'development') {
    // can change with hot reload
    return JSON.parse(await fs.promises.readFile(statsPath, 'utf-8'));
  }

  return stats;
}

function redirectIfNeeded(req, res, history) {
  const { pathname } = history.location;

  if (
    decodeURIComponent(req.baseUrl + req.path) !== decodeURIComponent(pathname)
  ) {
    res.redirect(302, pathname);
    return true;
  }
}

export default function match({ initialState, publicPath, apiRoot }) {
  return async (req, res, next) => {
    try {
      const state = typeof initialState === 'function'
        ? await initialState(req)
        : initialState;

      const lang = state.layout?.main?.lang ?? 'fr';
      const translateMode = state.layout?.main?.translateMode ?? false;
      const outdatedBrowser = state.layout?.main?.outdatedBrowser ?? false;
      const matomoCloudId = state.layout?.main?.matomoCloudId ?? false;

      // We create an extractor from the statsFile (generated by webpack loadable plugin)
      const extractor = new ChunkExtractor({
        stats: await getStats(),
        entrypoints: outdatedBrowser ? ['outdated', 'webapp'] : ['webapp'],
        publicPath,
      });

      const history = createMemoryHistory({
        initialEntries: [req.originalUrl],
      });

      // Create store for the layout
      const layoutStore = createLayoutStore(state.layout, history);

      const reduxMiddleware = createReduxMiddleware(layoutStore);

      const apps = [
        ['home', createHomeApp, [MainLayout, RequiredUser]],
        ['userSettings', createUserSettingsApp, [MainLayout, RequiredUser]],
        [
          'agendaSettingsNew',
          createAgendaSettingsNewApp,
          [MainLayout, RequiredUser],
        ],
        ['userActivities', createUserActivitiesApp, [MainLayout, RequiredUser]],
        [
          'inboxUser',
          createInboxApp,
          [MainLayout, RequiredUser, InboxUserLayout],
        ],
        [
          'support',
          createInboxApp,
          [MainLayout, RequiredUser, InboxUserLayout],
        ],
        // agenda admin
        [
          'aggregatorSources',
          createAggregatorSourcesApp,
          [MainLayout, RequiredUser, AgendaAdminDataLayout, AgendaAdminLayout],
        ],
        [
          'agendaAdminInbox',
          createInboxApp,
          [
            MainLayout,
            RequiredUser,
            AgendaAdminDataLayout,
            AgendaAdminLayout,
            InboxAgendaAdminLayout,
          ],
        ],
        [
          'members',
          createMembersApp,
          [MainLayout, RequiredUser, AgendaAdminDataLayout, AgendaAdminLayout],
        ],
        [
          'agendaActivities',
          createAgendaActivitiesApp,
          [MainLayout, RequiredUser, AgendaAdminDataLayout, AgendaAdminLayout],
        ],
        [
          'agendaStats',
          createAgendaStatsApp,
          [MainLayout, RequiredUser, AgendaAdminDataLayout, AgendaAdminLayout],
        ],
        [
          'legacyEmbeds',
          createLegacyEmbedsApp,
          [
            MainLayout,
            RequiredUser,
            AgendaAdminDataLayout,
            AgendaAdminFiltersLayout,
          ],
        ],
        [
          'agendaContribute',
          createAgendaContributeApp,
          [MainLayout, RequiredUser.agenda, AgendaDataLayout, AgendaLayout],
        ],
        [
          'eventAdmin',
          createEventAdminApp,
          [
            MainLayout,
            RequiredUser,
            AgendaAdminDataLayout,
            AgendaAdminFiltersLayout,
          ],
        ],
        [
          'agendaLocationAdmin',
          createAgendaLocationAdminApp,
          [MainLayout, RequiredUser, AgendaAdminDataLayout, AgendaAdminLayout],
        ],
        [
          'agendaSchemaAdmin',
          createAgendaSchemaAdminApp,
          [MainLayout, RequiredUser, AgendaAdminDataLayout, AgendaAdminLayout],
        ],
        [
          'agendaSettingsEdit',
          createAgendaSettingsEditApp,
          [
            MainLayout,
            RequiredUser,
            AgendaAdminDataLayout,
            AgendaAdminFiltersLayout,
          ],
        ],
        // superadmin
        [
          'adminSupport',
          createInboxApp,
          [MainLayout, RequiredUser, RequiredSuperAdmin, InboxUserLayout],
        ],
        [
          'supervisor',
          createSupervisorApp,
          [MainLayout, RequiredUser, RequiredSuperAdmin],
        ],
      ].reduce(
        (accu, [key, createApp, layout]) => ({
          ...accu,
          [key]: createApp({
            req,
            history,
            initialState: state[key],
            layout,
            reduxMiddleware,
            apiRoot,
          }),
        }),
        {},
      );

      // Not found
      const notFound = Object.values(apps).every(
        (app) =>
          !(
            app.routes
            && matchRoutes(app.routes, history.location.pathname).some(
              (v) => v.route.component && !v.route.routes,
            )
          ),
      );

      if (notFound) {
        return next();
      }

      const triggerHooks = () =>
        Promise.all(
          Object.values(apps)
            .filter((app) => app.triggerHooks)
            .map((app) => app.triggerHooks()),
        );

      // Triggers hooks
      await triggerHooks();

      // Check if redirect in hooks
      if (redirectIfNeeded(req, res, history)) {
        return;
      }

      const staticContext = {};
      const helmetContext = {};

      const queryClient = new QueryClient({
        defaultOptions: {
          queries: {
            refetchOnWindowFocus: false,
          },
        },
      });

      const outdatedScript = outdatedBrowser
        ? el(
          'script',
          { type: 'text/javascript', nonce: res.locals.cspNonce },
          `window.outdatedBrowserOptions = { language: "${lang}" };`,
        )
        : null;

      const matomoScript = matomoCloudId
        ? el(
          'script',
          { type: 'text/javascript', nonce: res.locals.cspNonce },
          `var _paq = window._paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['disableCookies']);
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
  var u="https://${matomoCloudId}/";
  _paq.push(['setTrackerUrl', u+'matomo.php']);
  _paq.push(['setSiteId', '1']);
  var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
  g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();`,
        )
        : null;

      const rootHelmet = el(RootHelmet, null, outdatedScript, matomoScript);

      const content = ReactDOM.renderToString(
        el(
          ErrorBoundary,
          null,
          el(
            HelmetProvider,
            { context: helmetContext },
            rootHelmet,
            wrapApp(
              {
                Content: () =>
                  el(
                    QueryClientProvider,
                    { client: queryClient },
                    el(LayoutManager, {
                      store: layoutStore,
                      history,
                      apps,
                    }),
                  ),
                history,
                triggerHooks,
              },
              { req, staticContext, extractor },
            ),
          ),
        ),
      );

      if (staticContext.url) {
        return res.redirect(staticContext.status || 302, staticContext.url);
      }

      // Check if location change anywhere else
      if (redirectIfNeeded(req, res, history)) {
        return;
      }

      // Get initialStateForClient
      const initialStateForClient = _.mapValues(apps, (app) => {
        const appState = app.store.getState();

        // Avoid all settings.apiRoot
        if (_.get(appState, 'settings.apiRoot')) {
          _.set(appState, 'settings.apiRoot', '');
        }

        return appState;
      });

      // Add layout state to initialStateForClient
      initialStateForClient.layout = layoutStore.getState();
      _.set(initialStateForClient.layout, 'main.apiRoot', '');

      const serializedInitialState = he.encode(
        stringify(initialStateForClient),
      );

      // Send Html
      const html = el(Html, {
        helmet: helmetContext.helmet,
        content,
        initialState: serializedInitialState,
        extractor,
        lang,
        translateMode,
        cspNonce: res.locals.cspNonce,
      });
      res.status(200).send(`<!doctype html>${ReactDOM.renderToString(html)}`);
    } catch (e) {
      next(e);
    }
  };
}
