'use strict';

const path = require('path');
const _ = require('lodash');
const React = require('react');
const ReactDOM = require('react-dom/server');
const { HelmetProvider } = require('react-helmet-async');
const { createMemoryHistory } = require('history');
const { stringify } = require('flatted/cjs');
const he = require('he');
const { ChunkExtractor } = require('@loadable/server');
const wrapApp = require('@openagenda/react-utils/dist/wrapApp');
const {
  matchRoutes
} = require('@openagenda/react-utils/dist/asyncMatchRoutes');
const { Html, LayoutManager } = require('@openagenda/react-layouts');
const {
  AgendaAdminLayout,
  InboxUserLayout,
  InboxAgendaAdminLayout,
  MainLayout
} = require('@openagenda/react-layouts/dist/layouts');
const createHomeApp = require('@openagenda/home/dist/app');
const createUserSettingsApp = require('@openagenda/user-apps/dist/app');
const createAgendaSettingsNewApp = require('@openagenda/agenda-settings/dist/client/createApp');
const createAgendaSettingsEditApp = require('@openagenda/agenda-settings/dist/client/editApp');
const createUserActivitiesApp = require('@openagenda/activity-apps/dist/client/apps/user');
const createAgendaActivitiesApp = require('@openagenda/activity-apps/dist/client/apps/agenda');
const createAggregatorSourcesApp = require('@openagenda/aggregator-sources/dist/app');
const createInboxApp = require('@openagenda/inbox-apps/dist/apps/inbox');
const createMembersApp = require('@openagenda/member-apps/dist/app');
const RootHelmet = require('./RootHelmet');
const createReduxMiddleware = require('./reduxMiddleware');

function redirectIfNeeded(req, res, history) {
  const { pathname } = history.location;

  if (
    decodeURIComponent(req.baseUrl + req.path) !== decodeURIComponent(pathname)
  ) {
    res.redirect(302, pathname);
    return true;
  }
}

module.exports = function match({
  initialState, apiRoot, lang, publicPath
}) {
  return async (req, res, next) => {
    try {
      // We create an extractor from the statsFile (generated by webpack loadable plugin)
      const extractor = new ChunkExtractor({
        statsFile: path.join(__dirname, '/dist/loadable-stats.json'),
        entrypoints: ['webapp'],
        publicPath
      });

      const history = createMemoryHistory({
        initialEntries: [req.originalUrl]
      });
      const state = typeof initialState === 'function' ? initialState(req) : initialState;

      // Create store for the layout
      const layoutStore = LayoutManager.createStore(
        {
          main: {
            apiRoot,
            lang
          },
          res: {
            main: {
              getUser: '/users/me',
              hasInboxNews: '/latest-inbox-timestamp'
            },
            agendaAdmin: {
              loadAgenda: '/:slug/admin/layout',
              verifyLocationCount: '/:slug/admin/locations/verifycount'
            }
          }
        },
        history
      );

      const reduxMiddleware = createReduxMiddleware(layoutStore);

      const apps = {
        home: createHomeApp({
          req,
          history,
          initialState: state.home,
          layout: MainLayout,
          reduxMiddleware
        }),
        userSettings: createUserSettingsApp({
          req,
          history,
          initialState: state.userSettings,
          layout: MainLayout,
          reduxMiddleware
        }),
        agendaSettingsNew: createAgendaSettingsNewApp({
          req,
          history,
          initialState: state.agendaSettingsNew,
          layout: MainLayout,
          reduxMiddleware
        }),
        userActivities: createUserActivitiesApp({
          req,
          history,
          initialState: state.userActivities,
          layout: MainLayout,
          reduxMiddleware
        }),
        aggregatorSources: createAggregatorSourcesApp({
          req,
          history,
          initialState: state.aggregatorSources,
          layout: [MainLayout, AgendaAdminLayout],
          reduxMiddleware
        }),
        agendaSettingsEdit: createAgendaSettingsEditApp({
          req,
          history,
          initialState: state.agendaSettingsEdit,
          layout: [MainLayout, AgendaAdminLayout],
          reduxMiddleware
        }),
        inboxUser: createInboxApp({
          req,
          history,
          initialState: state.inboxUser,
          layout: [MainLayout, InboxUserLayout],
          reduxMiddleware
        }),
        support: createInboxApp({
          req,
          history,
          initialState: state.support,
          layout: [MainLayout, InboxUserLayout],
          reduxMiddleware
        }),
        agendaAdminInbox: createInboxApp({
          req,
          history,
          initialState: state.agendaAdminInbox,
          layout: [MainLayout, AgendaAdminLayout, InboxAgendaAdminLayout],
          reduxMiddleware
        }),
        members: createMembersApp({
          req,
          history,
          initialState: state.members,
          layout: [MainLayout, AgendaAdminLayout],
          reduxMiddleware
        }),
        agendaActivities: createAgendaActivitiesApp({
          req,
          history,
          initialState: state.agendaActivities,
          layout: [MainLayout, AgendaAdminLayout],
          reduxMiddleware
        })
      };

      // Not found
      const notFound = Object.values(apps).every(
        app => !(
          app.routes
            && matchRoutes(app.routes, history.location.pathname).length
        )
      );

      if (notFound) {
        return next();
      }

      // Triggers hooks
      await Promise.all(
        Object.values(apps)
          .filter(v => v.triggerHooks)
          .map(v => v.triggerHooks())
      );

      // Check if redirect in hooks
      if (redirectIfNeeded(req, res, history)) {
        return;
      }

      const triggerHooks = () => Promise.all(Object.values(apps).map(app => app.triggerHooks()));

      const staticContext = {};
      const helmetContext = {};

      const content = ReactDOM.renderToString(
        React.createElement(
          HelmetProvider,
          { context: helmetContext },
          React.createElement(RootHelmet),
          wrapApp(
            {
              Content: () => React.createElement(LayoutManager, {
                store: layoutStore,
                history,
                apps
              }),
              history,
              triggerHooks
            },
            { req, staticContext, extractor }
          )
        )
      );

      if (staticContext.url) {
        return res.redirect(staticContext.status || 302, staticContext.url);
      }

      // Check if location change anywhere else
      if (redirectIfNeeded(req, res, history)) {
        return;
      }

      // Get initialStateForClient
      const initialStateForClient = _.mapValues(apps, app => {
        const appState = app.store.getState();

        // Avoid all settings.apiRoot
        if (_.get(appState, 'settings.apiRoot')) {
          _.set(appState, 'settings.apiRoot', '');
        }

        return appState;
      });

      // Add layout state to initialStateForClient
      initialStateForClient.layout = layoutStore.getState();
      _.set(initialStateForClient.layout, 'main.apiRoot', '');

      const serializedInitialState = he.encode(
        stringify(initialStateForClient)
      );

      // Send Html
      const html = React.createElement(Html, {
        helmet: helmetContext.helmet,
        content,
        initialState: serializedInitialState,
        lang,
        extractor
      });
      res.status(200).send(`<!doctype html>${ReactDOM.renderToString(html)}`);
    } catch (e) {
      next(e);
    }
  };
};
