server {
  server_name _;
  listen       443 http2 ssl;
  listen       [::]:443 http2 ssl;

  ssl_certificate      /var/lib/jelastic/SSL/jelastic.chain;
  ssl_certificate_key  /var/lib/jelastic/SSL/jelastic.key;

  location = /maintenance.html {
    internal;
    root /var/lib/nginx/html/;

    # if direct access this location, return 503
    error_page 404 =503 /maintenance.html;
  }

  location / {
    error_page 503 /maintenance.html;
    return 503;
  }
}