create table if not exists location (
  id bigint(20) not null auto_increment,
  slug varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
  placename varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
  address varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  city varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  country varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  latitude decimal(10,6) not null,
  longitude decimal(10,6) not null,
  owner_id bigint(20) default null,
  created_at datetime not null,
  updated_at datetime not null,
  uid bigint(20) default null unique,
  store longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  processed_at datetime default null,
  department varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  region varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  city_district varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  postal_code varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  admin_level_3 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  admin_level_5 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  eve_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  agenda_id bigint(20) default null,
  set_uid bigint(20) default null,
  insee varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  deleted tinyint(1) not null default 0,
  duplicate_candidates varchar(1000) default null,
  duplicate_disqualified varchar(1000) default null,
  merged_in bigint(20) default null,
  ext_ids JSON,
  unique index slug_idx (slug),
  index latlng_idx (latitude, longitude),
  index lng_idx (longitude),
  index owner_id_idx (owner_id),
  index agenda_id_idx (agenda_id),
  index set_uid_idx (set_uid),
  index deleted_idx (deleted),
  index duplicate_candidates_idx (duplicate_candidates),
  index created_at_idx (created_at),
  index updated_at_idx (updated_at),
  index ext_ids_idx ((CAST(ext_ids->'$.identifiers' AS CHAR(255) ARRAY))),
  primary key(id)
) engine=InnoDB default character set utf8 collate utf8_general_ci;

create table if not exists location_set (
  id bigint(20) not null auto_increment,
  created_at datetime not null,
  updated_at datetime not null,
  uid bigint(20) default null unique,
  title varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci default null,
  unique index uid_idx (uid),
  settings TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  primary key(id)
) engine=InnoDB default character set utf8 collate utf8_general_ci;
