create table if not exists location (
  id bigint(20) not null auto_increment,
  slug varchar(100) not null,
  placename varchar(100) not null,
  address varchar(255) default null,
  city varchar(100) default null,
  country varchar(2) default null,
  latitude decimal(10,6) not null,
  longitude decimal(10,6) not null,
  owner_id bigint(20) default null,
  created_at datetime not null,
  updated_at datetime not null,
  uid bigint(20) default null unique,
  main tinyint(1) not null default 0,
  store longtext,
  processed_at datetime default null,
  department varchar(255) default null,
  region varchar(255) default null,
  city_district varchar(255) default null,
  postal_code varchar(20) default null,
  eve_id varchar(100) default null,
  ext_id varchar(100) default null,
  agenda_id bigint(20) default null,
  set_uid bigint(20) default null,
  insee varchar(10) default null,
  deleted tinyint(1) not null default 0,
  duplicates varchar(2000) default null,
  merged_in bigint(20) default null,
  unique index slug_idx (slug),
  index latlng_idx (latitude, longitude),
  index owner_id_idx (owner_id),
  index agenda_id_idx (agenda_id),
  index set_uid_idx (set_uid),
  index ext_id_idx (ext_id),
  index deleted_idx (deleted),
  primary key(id)
) engine=InnoDB default character set utf8 collate utf8_general_ci;

create table if not exists location_set (
  id bigint(20) not null auto_increment,
  created_at datetime not null,
  updated_at datetime not null,
  uid bigint(20) default null unique,
  title varchar(255) default null,
  unique index uid_idx (uid),
  settings TEXT,
  primary key(id)
) engine=InnoDB default character set utf8 collate utf8_general_ci;