name: Install
description: Sets up Node.js and runs install

inputs:
  npm-token:
    description: 'NPM authentication token'
    required: false
  font-awesome-npm-token:
    description: 'NPM authentication token for Font Awesome'
    required: false

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: yarn
        scope: '@openagenda'
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "kevin.bertho@gmail.com"
        git config --global user.name "Kévin Berthommier"

    - name: Install dependencies
      shell: bash
      run: yarn install --no-immutable
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
        OA_PUBLIC_LOCKFILE: yarn.lock
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ inputs.font-awesome-npm-token }}
