FROM docker.elastic.co/elasticsearch/elasticsearch:7.7.0

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://github.com/opendatasoft/elasticsearch-aggregation-geoclustering/releases/download/v7.7.0.0/geopoint-clustering-aggregation-7.7.0.0.zip
