"use strict";

module.exports = {
  addField: { fr: 'Ajouter un champ', en: 'Add a field' },
  draggableField: { fr: 'Glisser-déposer pour trier', en: 'Drag and drop to sort' },
  editField: { fr: 'Editer les labels', en: 'Edit labels' },
  editFieldSave: { fr: 'Enregistrer', en: 'Save' },
  editFieldCancel: { fr : 'Annuler', en: 'Cancel' },
  fieldLabel: { fr: 'Titre du champ', en: 'Field title' },
  fieldInfo: { fr: 'Information complémentaire', en: 'Additional information' },
  fieldInfoInfo: { fr: 'S\'affiche sous le titre (comme ceci)', en: 'Displayed below the title (like this)' },
  fieldPlaceholder: { fr: 'Substitut de champ', en: 'Placeholder' },
  fieldPlaceholderPlaceholder: { fr: 'S\'affiche à l\'intérieur (comme ceci)', en: 'Is displayed inside the field (like this)' },
  fieldSub: { fr: 'Label de sous-champ', en: 'Sub info label' },
  fieldSubSub: { fr: 'S\'affiche sous le champ (comme ceci)', en: 'Is displayed below the field (like this)' },
  monolingualLabels: { fr: 'Les labels de ce champ sont monolingues', en: 'Labels of this field are monolingual' },
  addLanguages: { fr: 'Ajouter des langues', en: 'Add languages' },
  fieldLabelLanguages: { fr: 'Langues des labels', en: 'Label languages' },
  textFieldType: { fr : 'texte', en : 'Text' },
  textMultilingualFieldType: { fr: 'Text multilingue', en: 'Multilingual text' },
  imageFieldType: { fr: 'Image', en : 'Image' },
  unknownFieldType: { fr: 'Type inconnu', en: 'Unknown type' },
  languagesFieldType: { fr: 'Langues de saisie', en: 'Input languages' },
  markdownFieldType: { fr: 'Texte enrichi', en: 'Rich text' },
  markdownMultilingualFieldType: { fr: 'Texte enrichi multilingue', en: 'Multilingual rich text' },
  registrationFieldType: { fr: 'Liens, téléphone, email', en: 'Link, phone, email' },
  locationFieldType: { fr: 'Choix du lieu', en: 'Location selection' },
  accessibilityFieldType: { fr: 'Choix accessibilité', en: 'Accessibility selection' },
  timingsFieldType: { fr: 'Sélection des horaires', en: 'Timings selection' }
}
