'use strict';

const path = require( 'path' );
const _ = require( 'lodash' );
const React = require( 'react' );
const ReactDOM = require( 'react-dom/server' );
const { createMemoryHistory } = require( 'history' );
const { ChunkExtractor } = require( '@loadable/server' );
const asyncMatchRoutes = require( '@openagenda/react-utils/dist/asyncMatchRoutes' );
const homeMw = require( '@openagenda/home/dist/middleware' );
const createHomeApp = require( '@openagenda/home/dist/client/app' );
const createUserSettingsApp = require( '@openagenda/user-apps/dist/app' );
const { Html, HeaderManager, Header } = require( '@openagenda/react-layouts' );
const activitiesSvc = require( '@openagenda/activities' );
const { Inbox } = require( '@openagenda/inboxes' );
const config = require( '../config' );
const cmn = require( '../lib/commons-app' );

const apiRoot = `http://localhost:${config.port}`;
const phpPrefix = __DEVELOPMENT__ ? '/frontend_dev.php' : '';

// This is the stats file generated by webpack loadable plugin
const statsFile = path.resolve( '../../../cibul-symfony/web/js/loadable-stats.json' );

module.exports = app => {

  app.get(
    [ '/home', '/home/events', '/settings/?*?' ],
    cmn.loadLogger( 'webapp' ),
    cmn.loadBaseData( 'oasfmain.css' ),
    matchApp
  );

};

function redirectIfNeeded( req, res, history ) {
  const { pathname, search } = history.location;

  if ( decodeURIComponent( req.originalUrl ) !== decodeURIComponent( pathname + search ) ) {
    res.redirect( 302, pathname + search );
    return true;
  }
}

async function matchApp( req, res, next ) {
  try {
    // We create an extractor from the statsFile
    const extractor = new ChunkExtractor( { statsFile, entrypoints: [ 'webapp' ] } );

    const lang = req.lang || 'fr';
    const history = createMemoryHistory( { initialEntries: [ req.originalUrl ] } );

    const apps = {
      home: createHomeApp( {
        req,
        // Header: () => React.createElement( HeaderSelector, { type: 'main' } ),
        extractor,
        history,
        initialState: {
          settings: {
            prefix: '/home',
            apiRoot,
            lang,
            perPageLimit: homeMw.getConfig().mw.limit,
            isNew: _.get( req, 'user.isNew' ),
            displayLegacyMessageTab: false,
            userId: _.get( req, 'user.id' ),
            userUid: _.get( req, 'user.uid' )
          },
          res: {
            agendas: {
              contribute: '/:slug/contribute',
              create: '/new',
              list: '/home/agendas',
              show: '/:slug',
              showPrivate: '/:slug.prv',
              addEvent: `${phpPrefix}/:slug/addevent`,
              moderate: `${phpPrefix}/:slug/admin`,
              contact: '/:slug/contact'
            },
            events: {
              list: '/home/events.json',
              show: '/:slug/events/:eventSlug',
              showPrivate: '/:slug.prv/events/:eventSlug',
              showWithoutAgenda: '/events/:eventSlug',
              edit: '/:slug/event/:eventSlug/edit'
            },
            messages: '/home/messages',
            notifs: '/home/notifications',
            search: '/agendas'
          }
        }
      } ),
      userSettings: createUserSettingsApp( {
        req,
        extractor,
        history,
        initialState: {
          settings: {
            prefix: '/settings',
            apiRoot,
            lang
          },
          res: {
            getMe: '/users/me',
            updateProfile: '/users/me',
            deleteAccount: '/users/me',
            changeEmail: '/users/me/requestChangeEmail',
            changePassword: '/users/me/changePassword',
            generateApiKey: '/users/me/generateApiKey',
            uploadProfileImage: '/users/me/setImageProfile',
            removeProfileImage: '/users/me/clearImageProfile'
          }
        }
      } )
    };

    history.apps = apps;

    // Preload routes and filter visible/notFound apps
    const matchPerApps = await Promise.all(
      Object.values( apps )
        .map( app => app.routes && asyncMatchRoutes( app.routes, req.originalUrl ) )
    );

    const { visibleApps /* , notFoundApps */ } = Object.values( apps )
      .reduce( ( result, app, key ) => {
        const { components } = matchPerApps[ key ];

        if ( components.some( v => (v && v.isNotFound) ) ) {
          result.notFoundApps.push( app );
        } else {
          result.visibleApps.push( app );
        }

        return result;
      }, { visibleApps: [], notFoundApps: [] } );

    // Hide apps that should not be visible
    // history.replace( {
    //   state: {
    //     notFound: notFoundApps.map( v => v.notFoundKey )
    //   }
    // } );

    // Triggers hooks
    await Promise.all(
      visibleApps
        .filter( v => v.triggerHooks )
        .map( v => v
          .triggerHooks()
          .catch( err => console.log( `Error in triggerHooks of ${v.notFoundKey} app:`, err ) )
        )
    );

    // Check if redirect in hooks
    if ( redirectIfNeeded( req, res, history ) ) {
      return;
    }

    // Create store for the header
    const headerStore = HeaderManager.createStore( {
      header: {
        apiRoot,
        user: req.user,
        notifications: {
          // counter: req.user ? await notificationsCounter( req ) : null
        },
        inbox: {
          hasNew: req.user ? await hasInboxNews( req ) : null
        }
      }
    } );

    // Not found
    if ( !Object.keys( visibleApps ).length ) {
      return next();
    }

    // Render all visible apps
    const content = ReactDOM.renderToString( React.createElement(
      HeaderManager,
      { store: headerStore },
      Object.values( visibleApps ).map( ( { element } ) => element )
    ) );

    // Check if <Redirect /> is used
    for ( const app of visibleApps ) {
      if (
        app.staticContext
        && app.staticContext.url
        && !_.get( app, `staticContext.location.state.${app.notFoundKey}` )
      ) {
        return res.redirect( app.staticContext.status || 302, app.staticContext.url );
      }
    }

    // Check if location change anywhere else
    if ( redirectIfNeeded( req, res, history ) ) {
      return;
    }

    // Get initialState
    const initialState = _.mapValues( apps, app => {
      const state = app.store.getState();

      // Avoid all settings.apiRoot
      if ( _.get( state, 'settings.apiRoot' ) ) {
        _.set( state, 'settings.apiRoot', '' );
      }

      return state;
    } );

    initialState.header = headerStore.getState();
    _.set( initialState.header, 'header.apiRoot', '' );

    const headerType = headerStore.getState().header.type;
    const headerHtml = ReactDOM.renderToString( React.createElement(
      Header,
      { store: headerStore, type: headerType }
    ) );

    // Send Html
    const html = React.createElement( Html, { content: headerHtml + content, lang, initialState, extractor } );
    res.status( 200 ).send( `<!doctype html>${ReactDOM.renderToString( html )}` );
  } catch ( e ) {
    next( e );
  }
}

function notificationsCounter( req ) {
  return activitiesSvc.feed( {
    entityType: 'user',
    entityUid: req.user.uid
  } ).notifications.count( { state: 0 } );
}

async function hasInboxNews( req ) {
  const { data } = await Inbox.user( req.user.uid ).conversations.list( 0, 1 );
  const timestamp = _.get( data, '[0].latestMessage.createdAt' );

  if ( !timestamp ) {
    return false;
  } else if ( !req.user.lastInboxCheck ) {
    return true;
  } else if ( timestamp > req.user.lastInboxCheck ) {
    return true;
  }

  return false;
}
