dev: #values to set are tagged. Do a search on '#config'

  node_redirects: true

  main_host: openagenda.com
  full_main_host: d.openagenda.com

  facebook_appid: '223239984'
  facebook_secret: 'fdsqfdsqfdsq'
  facebook_timeout: 60

  secure_activate: false

  twitter_consumer_key: fdqfsdq
  twitter_consumer_secret: fdsqfsdqfdsq

  mapquest_key: Fmjtd%dqfsdqfdssq%2Ca0%3Do5-9urn06
  geocodefarm_key: c90247db-fdqfdsq-8517d6450e7b

  active_storage: aws

  aws_bucket: cibuldev
  aws_tmp_bucket: cibuldevtmp
  aws_archive_bucket: cibuldevarc
  aws_path: //cibuldev.s3.amazonaws.com/
  aws_tmp_path: //cibuldevtmp.s3.amazonaws.com/
  aws_archive_path: //cibultestarc.s3.amazonaws.com/

  event_search_max_results: 4000

  send_mail: true

  tmp_dir: /var/tmp/cibul-tmp/

  client_ip: 92.137.14.19

  .arrays:

    embed_template_types:
      eventitem:
        default_path: %SF_ROOT_DIR%/../cibul-node/services/embed/templates/eventItem.tblr
      event:
        default_path: %SF_ROOT_DIR%/../cibul-node/services/embed/templates/event.tblr
      header:
        default_path: %SF_ROOT_DIR%/../cibul-node/services/embed/templates/header.tblr

    facebook_tab_app_program: { 'id': '374503086004223', 'secret': '30ff8838514b89989975b20dbf31dade' }
    facebook_tab_app_programme: { 'id': '461071847317598', 'secret': '16724b6a4ee503edb7682a78643bde06' }
    facebook_tab_app_agenda: { 'id': '514129535303033', 'secret': '7922882b3a43cc312c999d63372aaab0' }

  use_redis_cache: true

  redis_host: 'localhost'
  redis_port: 6379
  redis_background_main_channel: 'maindev'

  redis_background_wait: 10

  maxmind_db_path: %SF_ROOT_DIR%/../maxmind/GeoLite2-City.mmdb

  static_pages_path: %SF_ROOT_DIR%/../cibul-static/

  tmp_dir: /var/tmp/cibul-tmp/

prod:
  node_redirects: true

  main_host: openagenda.com #config
  full_main_host: openagenda.com #config

  secure_activate: false

  facebook_appid: 'fbappidstring' #config
  facebook_secret: 'fbappidtoken' #config
  facebook_timeout: 600

  twitter_consumer_key: fdsqfssqfqs #config
  twitter_consumer_secret: rezareza #config

  mapquest_key: unused
  geocodefarm_key: fdsqfsdqfsdsq #config

  active_storage: aws

  aws_bucket: cibul #mainbucket #config
  aws_tmp_bucket: cibultmp #temporarybucket #config
  aws_archive_bucket: cibularc #not used
  aws_path: //cibul.s3.amazonaws.com/ #main bucket path #config
  aws_tmp_path: //cibultmp.s3.amazonaws.com/ #temporary bucket path #config
  aws_archive_path: //cibularc.s3.amazonaws.com/ # not used

  event_search_max_results: 4000

  send_mail: true

  .arrays: #unused
    facebook_tab_app_program: { 'id': '590486500986118', 'secret': '3811d913149d6143d3b7f267721a45f9' }
    facebook_tab_app_programme: { 'id': '384165391703888', 'secret': '7d25739636fa2ff5cf77130a5a40df72' }
    facebook_tab_app_agenda: { 'id': '457775380971561', 'secret': '323653ad7702e6c9f75076d8d05e90bf' }

  static_pages_path: /home/ubuntu/lib/cibul-static/ #unused


  use_redis_cache: true

  redis_host: 'fredishosturl' #config
  redis_port: 6379 #config

all:

  node_port: 8901

  host: d.openagenda.com
  is_secure: false

  new_form: true

  event_title_max_length: 140
  event_description_max_length: 200
  event_free_text_max_length: 10000
  event_tags_max_length: 255

  #persistent cookie life (in seconds)
  # 30 days - 2592000
  # 7 days - 604800
  # 1 day - 86400
  cookie_life: 604800 #unused

  cibul_secret: '!' #unused

  key_refresh_rate: 86400

  #remember me life
  remember_life: 604800 #unused

  #amazon parameters

  aws_key: fdq #aws key #config
  aws_secret_key: fdsqfdsq #config
  aws_account_id: 123 #config

  aws_static_path: //cibulstatic.s3.amazonaws.com/ #config

  #email dot replacement

  email_dot: '[dot]'
  admin_email: 'admin@gopenagenda.com' #config

  #general image parameters

  upload_dir: /uploads/
  static_path: /images/
  tmp_dir: /home/ubuntu/tmp/cibul-tmp/

  #event image parameters

  event_width: 700
  event_height: 2000
  event_image_max_size: 6000000
  event_full_image_max_width: 1600
  event_full_image_max_height: 6000
  event_full_image_prefix: evf
  event_thumb_prefix: evtb
  event_thumb_height: 160
  event_thumb_width: 120

  event_image_default: event-no-image.png

  #review image parameters

  review_width: 300
  review_height: 300
  review_image_max_size: 6000000
  review_thumb_prefix: rwtb
  review_thumb_width: 75
  review_thumb_height: 75

  review_image_default: review-no-image.png

  #user image parameters

  user_width: 300
  user_height: 300
  user_thumb_prefix: rwtb
  user_thumb_width: 75
  user_thumb_height: 75

  user_image_default: review-no-image.png

  #event page parameters

  event_free_text_threshold: 450
  event_tags_threshold: 250

  #max string lengths in forms
  max_review_description: 160
  max_review_description_small: 40
  max_review_title: 140
  max_review_title_small: 60

  # delay in seconds - 10,000,000 is 115 days approx
  # delay underwhich human check must be made
  human_check_delay: 180

  pagination: 10
  pagination_small: 24

  solr_max_results: 2000

  solr_event_host: localhost
  solr_event_port: 8983

  solr_review_host: localhost
  solr_review_port: 8984

  use_redis_cache: true

  redis_background_event_stack: 'bgestack'
  redis_background_event_stack_admin: 'bgestacka'
  redis_background_event_failstack: 'bgefailstack'
  redis_background_main_channel: 'main'
  redis_background_wait: 600

  version: 101

  # currently unused. member serves as use case with version helper
  versions: '{"members":[{"version":2,"createdAt":"2016-05-22T00:00:00.000Z","agendaUids":[47863189,48959239,93961830,5897476,96165479,11072140,41715612,28447894,27744304,56907207,26127587,73087674,63338236,47483234,19187305,33332852,66274790,72177774,67130267,68263389,2445326,19678829,49562322,61327284,77097167,27437914, 30456419, 71115381, 20168566, 22946799, 9343334, 11919999, 85229066, 30453876]},{"version":1}]}'


  # lifespan of a trial cred: 1 week
  cred_trial_lifespan: 604800

  # time within expiry notification must be made: 2 days
  cred_expiry_notification_delay: 172800

  js_color_picker: 'colorpicker.min.js'
  js_location_counter: 'verifiedLocationsCounter.js'

  js_global: 'layoutMain.js'

  js_message: 'message.min.js'

  js_visitor: 'home/visitor.js'

  js_list: 'list.min.js'

  js_home_reviews: 'home/agendas.js'

  js_review: 'review/program.min.js'
  js_review_form: 'review/form.min.js'
  js_review_theme: 'review/theme.min.js'
  js_review_menu: 'review/menu.min.js'
  js_review_admin_list: 'review/adminList.min.js'
  js_review_admin_dataviz: 'review/adminDataviz.min.js'

  js_review_search: 'review/search.min.js'

  js_review_embed_list: 'review/embedList.min.js'
  js_review_embed_list_fb: 'review/embedListFb.min.js'
  js_review_embed_map: 'review/embedMap.min.js'
  js_review_embed_menu: 'review/embedMenu.js'
  js_review_widget_embed: 'review/cibulEmbed.min.js'

  js_review_map_config: 'review/widgetMapConfig.js'
  js_review_map_config_frame: 'review/widgetMapConfigFrame.js'

  js_event: 'event/event.min.js'
  js_event_publish: 'eventFormIndex.js'
  js_agenda_admin_events: 'agendaAdminEventsIndex.js'
  js_tiny_mce: 'tinymce/tinymce.min.js'
  #js_tiny_mce: 'tinymce/tinymce.js'
  js_event_list: 'event/list.min.js'
  js_event_embed: 'event/embedEvent.min.js'

  js_embed_form: 'review/embedForm.js'
  js_embed_form_sandbox: 'review/embedFormSandbox.js'

  css_review_embed_list: 'embed/list.css'
  css_review_embed_map: 'embed/map.css'

  css_form: 'form.css'
  css_agenda_admin_events: 'agendaAdminEvents.css'

  css_event_embed: 'embed/event.css'
  css_form_embed: 'embed/form.css'

  .arrays:

    embed_template_types:
      eventitem:
        default_path: '/home/ubuntu/www/cibul-node/services/embed/templates/eventItem.tblr'
      event:
        default_path: '/home/ubuntu/www/cibul-node/services/embed/templates/event.tblr'
      header:
        default_path: '/home/ubuntu/www/cibul-node/services/embed/templates/header.tblr'

    session:
      name: 'oas'
      sf_name: 'symfony'
      store_prefix: 'session:'
      php: 'phpsession:'

    conversation_admin_ids: [ 1, 2 ]
    authorized_redirects:  #authorized module/action pairs for redirecting
      - general/index
      - settings/apiShow
      - event/share
      - event/show
      - event/showInReview
      - event/new
      - eventForm/new
      - eventForm/edit
      - eventFormReview/edit
      - eventFormReview/signup
      - settings/show
      - settings/showTab
      - user/newFull
      - review/new
      - review/show
      - review/follow
      - home/show
      - home/showNotifications
      - home/showMessages
      - conversation/index
      - reviewAdmin/show
      - conversation/new
      - conversation/show
      - conversation/action
      - eventUserCreate/take
      - user/acceptInvitation
      - reviewEditor/index
      - reviewAdministrator/index

    language_list:
      fr: français
      en: english 
      es: español 
      de: deutsch 
      it: italiano
      ne: nederlands
      pt: português
      ar: العربية 
      is: íslenska
      tr: türkçe 
      br: breton 
      bz: gallo

    language_labels:
      aa: Afar
      ab: Аҧсуа
      af: Afrikaans
      ak: Akana
      am: አማርኛ
      an: Aragonés
      ar: العربية
      as: অসমীয়া
      av: Авар
      ay: Aymar
      az: Azərbaycanca / آذربايجان
      ba: Башҡорт
      be: Беларуская
      bg: Български
      bh: भोजपुरी
      bi: Bislama
      bm: Bamanankan
      bn: বাংলা
      bo: བོད་ཡིག / Bod skad
      br: Brezhoneg
      bs: Bosanski
      ca: Català
      ce: Нохчийн
      ch: Chamoru
      co: Corsu
      cr: Nehiyaw
      cs: Česky
      cu: словѣньскъ / slověnĭskŭ
      cv: Чăваш
      cy: Cymraeg
      da: Dansk
      de: Deutsch
      dv: ދިވެހިބަސް
      dz: ཇོང་ཁ
      ee: Ɛʋɛ
      el: Ελληνικά
      en: English
      eo: Esperanto
      es: Español
      et: Eesti
      eu: Euskara
      fa: فارسی
      ff: Fulfulde
      fi: Suomi
      fj: Na Vosa Vakaviti
      fo: Føroyskt
      fr: Français
      fy: Frysk
      ga: Gaeilge
      gd: Gàidhlig
      gl: Galego
      gn: Avañe'ẽ
      gu: ગુજરાતી
      gv: Gaelg
      ha: هَوُسَ
      he: עברית
      hi: हिन्दी
      ho: Hiri Motu
      hr: Hrvatski
      ht: Krèyol ayisyen
      hu: Magyar
      hy: Հայերեն
      hz: Otsiherero
      ia: Interlingua
      id: Bahasa Indonesia
      ie: Interlingue
      ig: Igbo
      ii: ꆇꉙ / 四川彝语
      ik: Iñupiak
      io: Ido
      is: Íslenska
      it: Italiano
      iu: ᐃᓄᒃᑎᑐᑦ
      ja: 日本語
      jv: Basa Jawa
      ka: ქართული
      kg: KiKongo
      ki: Gĩkũyũ
      kj: Kuanyama
      kk: Қазақша
      kl: Kalaallisut
      km: ភាសាខ្មែរ
      kn: ಕನ್ನಡ
      ko: 한국어
      kr: Kanuri
      ks: कश्मीरी / كشميري
      ku: Kurdî / كوردی
      kv: Коми
      kw: Kernewek
      ky: Kırgızca / Кыргызча
      la: Latina
      lb: Lëtzebuergesch
      lg: Luganda
      li: Limburgs
      ln: Lingála
      lo: ລາວ / Pha xa lao
      lt: Lietuvių
      lv: Latviešu
      mg: Malagasy
      mh: Kajin Majel / Ebon
      mi: Māori
      mk: Македонски
      ml: മലയാളം
      mn: Монгол
      mo: Moldovenească
      mr: मराठी
      ms: Bahasa Melayu
      mt: bil-Malti
      my: Myanmasa
      na: Dorerin Naoero
      nd: Sindebele
      ne: नेपाली
      ng: Oshiwambo
      nl: Nederlands
      nn: Norsk (nynorsk)
      no: Norsk (bokmål / riksmål)
      nr: isiNdebele
      nv: Diné bizaad
      ny: Chi-Chewa
      oc: Occitan
      oj: ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin
      om: Oromoo
      or: ଓଡ଼ିଆ
      os: Иронау
      pa: ਪੰਜਾਬੀ / पंजाबी / پنجابي
      pi: Pāli / पाऴि
      pl: Polski
      ps: پښتو
      pt: Português
      qu: Runa Simi
      rm: Rumantsch
      rn: Kirundi
      ro: Română
      ru: Русский
      rw: Kinyarwandi
      sa: संस्कृतम्
      sc: Sardu
      sd: सिनधि
      se: Sámegiella
      sg: Sängö
      sh: Srpskohrvatski / Српскохрватски
      si: සිංහල
      sk: Slovenčina
      sl: Slovenščina
      sm: Gagana Samoa
      sn: chiShona
      so: Soomaaliga
      sq: Shqip
      sr: Српски
      ss: SiSwati
      st: Sesotho
      su: Basa Sunda
      sv: Svenska
      sw: Kiswahili
      ta: தமிழ்
      te: తెలుగు
      tg: Тоҷикӣ
      th: ไทย / Phasa Thai
      ti: ትግርኛ
      tk: Туркмен / تركمن
      tl: Tagalog
      tn: Setswana
      to: Lea Faka-Tonga
      tr: Türkçe
      ts: Xitsonga
      tt: Tatarça
      tw: Twi
      ty: Reo Mā`ohi
      ug: Uyƣurqə / ئۇيغۇرچە
      uk: Українська
      ur: اردو
      uz: Ўзбек
      ve: Tshivenḓa
      vi: Tiếng Việt
      vo: Volapük
      wa: Walon
      wo: Wollof
      xh: isiXhosa
      yi: ייִדיש
      yo: Yorùbá
      za: Cuengh / Tôô / 壮语
      zh: 中文
      zu: isiZulu
      
    facebook_tab_labels_en: { program: Program, agenda: Agenda }
    facebook_tab_labels_fr: { programme: Programme, agenda: Agenda }
    facebook_tab_labels_es: { programme: Programa, agenda: Agenda }
    facebook_tab_labels_ar: { program: Program, agenda: Agenda }
    facebook_tab_labels_de: { program: Program, agenda: Agenda }
    country_labels: { FR: France, US: United States }
    review_orders: [publication, chronological, relative],
    review_theme: { max_size: 8000000, min_offset: 60, max_offset: 200, defaults: { repeat: norepeat, anchorage: center, canvasposition: center, bgcolor: '', offset:60 } }
    review_sections: { date: date, month: month, year: year, country: country, region: region, department: department, city: city, city_district: city_district, postal_code: postal_code, location: place, category: category, tag: tag }
    review_sections_plurals: { date: dates, month: months, year: years, country: countries, region: regions, department: departments, city: cities, city_district: city_districts, postal_code: postal_codes, location: places, category: categories, tag: tags }
    review_xml_tags: { title: title, description: description, free_text: freeText, tags: tags }
    interface_languages: [en, fr]
    embed_languages: [en, fr, es, de, ar]
    default_language: 'fr'
    default_search_list:
      ce-weekend-a-paris: fr
      this-weekend-in-paris: en
      cette-semaine-a-paris: fr
      this-week-in-paris: en
      ce-weekend-en-ile-de-france: fr
      this-weekend-in-ile-de-france: en
      cette-semaine-en-ile-de-france: fr
      this-week-in-ile-de-france: en
    help_visitor: [connect] #, searchCalendar, searchMap]
    help_logged:  [connect]

    # fdb 2118
    # jdc 2237
    # greenpeace france 2252
    # enlarge your paris 2092
    # collectif bar bars 2440

    review_moderated: [30, 64, 289, 2038, 2236, 2118, 2237, 2433, 2440, 2092, 2392, 2592]

    review_facebook: [30, 64, 90, 1788, 1676, 1170, 1391, 75, 2167, 1913, 729, 2118, 2237, 2433, 2440, 2092, 2392, 2592]

    review_newsletter: [30, 64, 90, 75, 285, 311, 1746, 1913, 2006, 2038, 2109, 659, 2592]

    review_aggregator: [322, 323, 1786, 301, 241, 2440, 2092, 2592]

    review_indesign: [2118, 2592]

    review_dataviz: [64, 2237]

    review_embedded_form: [289, 2118, 2237, 2433, 2440, 2092]

    review_extended_rights: [2118, 2237, 2433, 2440, 2092, 2592]

    review_editors: [30, 2038, 2237, 2118, 2433, 2440, 2092]

    review_admins: [30, 64, 1913, 2038, 2237, 2118, 2433, 2440, 2092, 2592]

    review_integrated: [64, 75, 96, 181, 230, 285, 289, 1391, 1720, 1740, 1746, 1913, 1924, 1925, 1931, 2064, 2237, 2118, 2433, 2440, 2239, 2006, 2007, 1934, 2092, 2392, 1740, 2592, 2443]

    event_editors: [1,2, 2252]


    # quick hack. burn it with fire.
    fetedelamusique_review_ids: [ 171, 833, 3639, 3640, 3641, 3642, 3643, 3644, 3645, 3646, 3647, 3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3667, 3668, 3669 ]
    fetedelamusique_dates: [ '2015-06-21' ]


  default_radius: 5000 #value used for the search menu

  facebook_page: https://www.facebook.com/oagenda
  twitter_page: https://www.twitter.com/oagenda


  conversation_list_item_length: 60

  maxmind_db_path: /home/ubuntu/lib/geolite/GeoLite2-City.mmdb


  license_label: ODC-ODbl license
  license_url: http://opendatacommons.org/licenses/odbl/summary/


  map_icon_active: //cibulstatic.s3.amazonaws.com/markerIcon.png
  map_icon_inactive: //cibulstatic.s3.amazonaws.com/markerIconGray.png
  map_icon_max_width: 50

  sf_captchagd:
    image_width:                100 # image width in pixels
    image_height:               30 # image height in pixels
    chars:                      "123456789" # possible chars in captcha
    length:                     4 # length of captcha
    font_size:                  18 # font size
    force_new_captcha:          false # if true - captcha regenerated EVERY request, even if user input true value before

    # possible chars colors
    font_color:                 ["252525", "8b8787", "550707", "3526E6", "88531E"]

    # chars fonts
    fonts:                      ["akbar/akbar.ttf", "brushcut/BRUSHCUT.TTF", "molten/molten.ttf", "planet_benson/Planetbe.ttf", "whoobub/WHOOBUB_.TTF"]
    background_color:           FFFFFF # image background color
    border_color:               BBBBBB # image border color
