#values to set are tagged. Do a search on '#config'
dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=oadev'
      username: root
      password: 'grut'
      attributes: { default_table_collate: utf8_general_ci, default_table_charset: utf8 }

prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host={hosturl};dbname={dbname};port=3306' #config
      username: dbuser #config
      password: "dbpassword" #config
      attributes: { default_table_collate: utf8_general_ci, default_table_charset: utf8 }

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=oatest'
      username: root
      password: 'grut'
      attributes: { default_table_collate: utf8_general_ci, default_table_charset: utf8 }

zombie:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=oatest'
      username: root
      password: 'grut'
      attributes: { default_table_collate: utf8_general_ci, default_table_charset: utf8 }