#!/bin/sh
. "$(dirname $0)/_/husky.sh"

set -e

[ -n "$DISABLE_AUTO_COMMIT" ] && exit 0

#
# Update a superproject when a commit is made to a submodule.
# Intended for .git/**modules/{THE_SUBMODULE}/hooks/post-commit
# where the double-star indicates variadic path elements.
#
# Depends on Git >= 2.13.

# Clean the Git environment before crossing repository boundaries.
# From https://stackoverflow.com/questions/36196548/cannot-trigger-post-commit-git-hook-on-git-submodule

unset $(env | grep "^GIT_" | cut -d '=' -f 1)

SUPERPROJECT=$(git rev-parse --show-superproject-working-tree)
SUPERPROJECT_NAME=$(basename "$SUPERPROJECT")

# It's not a submodule
[ -z "$SUPERPROJECT" ] && exit 0

GIT="git"
SUBMODULE=$(git rev-parse --show-toplevel)
SUBMODULE_NAME=$(basename "$SUBMODULE")
COMMIT_MSG="chore: update submodule $SUBMODULE_NAME"

SUPERPROJECT_BRANCH=$(git -C "$SUPERPROJECT" rev-parse --abbrev-ref HEAD)
SUBMODULE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
MAIN_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

if [ "$SUBMODULE_BRANCH" != "$MAIN_BRANCH" ]; then
    echo "Skip committing to $SUPERPROJECT_NAME, the submodule $SUBMODULE_NAME is not on the branch $MAIN_BRANCH"
    exit 0
fi

echo "Committing to $SUPERPROJECT_NAME"

$GIT -C "$SUPERPROJECT" add "$SUBMODULE"
$GIT -C "$SUPERPROJECT" commit --no-verify -m "$COMMIT_MSG" -- "$SUBMODULE"
