CREATE TABLE `${schema}` (
  id bigint(20) AUTO_INCREMENT,
  uid BIGINT UNIQUE,
  owner_uid bigint(20),
  creator_uid bigint(20),
  agenda_uid bigint(20),
  attendance_mode TINYINT(1) DEFAULT 1,
  online_access_link VARCHAR(255),
  location_uid bigint(20),
  slug VARCHAR(255) NOT NULL UNIQUE,
  title VARCHAR(2000),
  description VARCHAR(2000),
  long_description TEXT,
  keywords VARCHAR(2000),
  conditions VARCHAR(2000),
  image VARCHAR(1500),
  draft TINYINT(1) DEFAULT 0,
  private TINYINT(1) DEFAULT 0,
  status TINYINT(1) DEFAULT 1,
  timezone VARCHAR(255),
  timings TEXT,
  accessibility VARCHAR( 100 ),
  age VARCHAR( 50 ),
  registration VARCHAR(2000),
  `references` VARCHAR(2000),
  links TEXT character set utf8mb4,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME,
  file_key varchar(32),
  UNIQUE INDEX id_idx (id),
  UNIQUE INDEX uid_idx (uid),
  UNIQUE INDEX slug_idx (slug),
  INDEX agenda_uid_idx (agenda_uid),
  INDEX owner_uid_idx (owner_uid),
  INDEX location_uid_idx (location_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
