'use strict';

const c = require('../contributionTypes');
const s = require('../eventStates');
const statuses = require('../eventStatuses');

module.exports = [
  {
    field: 'id',
    type: 'integer',
    optional: true, // Auto-generated by database, not required in validation
    read: ['internal'],
    write: ['internal'],
  },
  {
    field: 'uid',
    type: 'integer',
    optional: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'title',
    type: 'text',
    min: 2,
    max: 255,
    optional: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
  },
  {
    field: 'description',
    type: 'text',
    max: 400,
    optional: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
  },
  {
    field: 'slug',
    type: 'slug',
    min: 2,
    max: 255,
    optional: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'url',
    type: 'link',
    read: ['internal', 'public', 'administrator', 'moderator'],
    max: 2000,
  },
  {
    field: 'official',
    type: 'boolean',
    default: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'networkUid',
    type: 'integer',
    optional: true,
    default: null,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'locationSetUid',
    type: 'integer',
    optional: true,
    default: null,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'ownerId',
    type: 'integer',
    optional: false,
    read: ['internal'],
    write: ['internal'],
  },
  {
    field: 'updatedAt',
    type: 'date',
    optional: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'createdAt',
    type: 'date',
    optional: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'formSchemaId',
    type: 'integer',
    optional: true,
    default: null,
    read: ['internal'],
    write: ['internal'],
  },
  {
    field: 'memberSchemaId',
    type: 'integer',
    optional: true,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
    default: null,
  },
  {
    field: 'officializedAt',
    type: 'date',
    default: null,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'image',
    read: ['internal', 'public', 'administrator', 'moderator'],
    type: 'pass',
    default: null,
  },
  {
    field: 'private',
    type: 'boolean',
    default: false,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'indexed',
    type: 'boolean',
    default: true,
    read: ['internal', 'public', 'administrator', 'moderator'],
    write: ['internal'],
  },
  {
    field: 'settings',
    type: 'schema',
    read: ['public'],
    fields: [
      {
        field: 'tracking',
        type: 'schema',
        read: ['administrator', 'moderator', 'internal', 'public'],
        write: ['administrator', 'internal'],
        fields: [
          {
            field: 'googleAnalytics',
            type: 'text',
            max: 255,
            read: ['administrator', 'moderator', 'internal', 'public'],
            write: ['administrator', 'internal'],
          },
          {
            field: 'googleAnalyticsSecret',
            type: 'text',
            read: ['administrator', 'internal'],
            write: ['administrator', 'internal'],
            max: 255,
          },
          {
            field: 'matomoUrl',
            type: 'text',
            read: ['administrator', 'moderator', 'internal', 'public'],
            write: ['administrator', 'internal'],
            max: 255,
          },
          {
            field: 'matomoSiteId',
            type: 'text',
            read: ['administrator', 'moderator', 'internal', 'public'],
            write: ['administrator', 'internal'],
            max: 255,
          },
          {
            field: 'matomoAskForConsent',
            type: 'boolean',
            read: ['administrator', 'moderator', 'internal', 'public'],
            write: ['administrator', 'internal'],
            max: 255,
          },
          {
            field: 'matomoCustom',
            type: 'pass',
            list: true,
            read: ['administrator', 'moderator', 'internal', 'public'],
            write: ['internal'],
          },
        ],
      },
      {
        field: 'public',
        type: 'schema',
        read: ['administrator', 'moderator', 'internal', 'public'],
        write: ['internal'],
        fields: [
          {
            field: 'filters',
            type: 'schema',
            fields: [
              {
                field: 'displayed',
                list: { default: null },
                type: 'text',
              },
            ],
          },
        ],
      },
      {
        field: 'admin',
        type: 'schema',
        read: ['administrator', 'moderator', 'internal'],
        write: ['internal'],
        fields: [
          {
            field: 'filters',
            type: 'schema',
            fields: [
              {
                field: 'displayed',
                list: { default: null },
                type: 'text',
              },
            ],
          },
        ],
      },
      {
        field: 'lab',
        type: 'schema',
        read: ['administrator', 'moderator', 'internal', 'public'],
        write: ['administrator', 'internal'],
        fields: [
          {
            field: 'status',
            type: 'boolean',
            default: true,
          },
        ],
      },
      {
        field: 'locations',
        type: 'schema',
        read: ['administrator', 'moderator', 'internal', 'public'],
        write: ['internal'],
        fields: [
          {
            field: 'extIds',
            type: 'pass',
          },
        ],
      },
      {
        field: 'inbox',
        type: 'schema',
        read: ['administrator', 'moderator', 'public', 'internal'],
        write: ['administrator', 'internal'],
        fields: [
          {
            field: 'mailto',
            type: 'schema',
            fields: [
              {
                field: 'enabled',
                type: 'boolean',
                default: false,
              },
              {
                field: 'email',
                type: 'email',
                default: null,
              },
              {
                field: 'subject',
                type: 'text',
                default: null,
              },
              {
                field: 'body',
                type: 'text',
                default: null,
              },
            ],
          },
        ],
      },
      {
        field: 'contribution',
        type: 'schema',
        read: ['administrator', 'moderator', 'internal', 'public'],
        fields: [
          {
            field: 'type',
            default: c.OPEN,
            type: 'choice',
            optional: false,
            unique: true,
            options: [c.MEMBERS_ONLY, c.CLOSED, c.OPEN],
          },
          {
            field: 'defaultState',
            default: s.PUBLISHED,
            type: 'choice',
            optional: false,
            unique: true,
            options: [s.NOT_VALIDATED, s.VALIDATED, s.PUBLISHED],
          },
          {
            field: 'canPublish',
            type: 'choice',
            default: ['administrators', 'moderators'],
            options: ['administrators', 'moderators'],
          },
          {
            field: 'moderateOnChangeBy',
            type: 'choice',
            default: [],
            options: ['administrator', 'moderator', 'contributor'],
          },
          {
            field: 'modoCanInviteModo',
            type: 'boolean',
            read: ['administrator', 'moderator', 'internal', 'public'],
            write: ['administrator', 'internal'],
            max: 255,
          },
          {
            field: 'defaultLang',
            default: null,
            type: 'choice',
            optional: true,
            unique: true,
            options: ['en', 'fr', 'it', 'es', 'de', 'ar', null],
          },
          {
            field: 'allowLocationCreate',
            type: 'boolean',
            default: true,
          },
          {
            field: 'messages',
            type: 'schema',
            fields: [
              {
                field: 'instructions',
                type: 'text',
              },
              {
                field: 'complete',
                type: 'text',
              },
              {
                field: 'publication',
                type: 'text',
              },
              {
                field: 'GDPRInformation',
                type: 'text',
              },
            ],
          },
          {
            field: 'useFields',
            description: 'require members to fill in a member form',
            type: 'boolean',
            default: false,
          },
          {
            field: 'authorizedIPAddresses',
            read: ['internal', 'administrator', 'moderator'],
            type: 'ip',
            list: true,
            default: [],
          },
          {
            field: 'status',
            type: 'schema',
            read: ['administrator', 'moderator', 'internal', 'public'],
            fields: [
              {
                field: 'enabled',
                type: 'choice',
                default: [
                  statuses.RESCHEDULED,
                  statuses.FULL,
                  statuses.CANCELLED,
                ],
                options: Object.values(statuses),
              },
            ],
          },
        ],
      },
      {
        field: 'registration',
        type: 'schema',
        read: ['internal', 'public'],
        write: ['internal'],
        fields: [
          {
            field: 'passCulture',
            type: 'schema',
            optional: true,
            fields: [
              {
                field: 'siren',
                list: { default: null },
                type: 'text',
                optional: false,
              },
              {
                field: 'bookingEmail',
                type: 'email',
                default: null,
                optional: true,
              },
              {
                field: 'defaultVenueId',
                type: 'integer',
                default: null,
                optional: true,
              },
              {
                field: 'access',
                list: { default: null },
                type: 'text',
                optional: true,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    field: 'credentials',
    type: 'schema',
    read: ['internal'],
    write: ['internal'],
    fields: [
      {
        field: 'premiumCustomFields',
        description: 'Allow adding multiple custom fields to agenda form',
        type: 'boolean',
        default: false,
      },
      {
        field: 'moderators',
        description: 'Add Moderator to member roles',
        type: 'boolean',
        default: false,
      },
      {
        field: 'activatingInvitations',
        description:
          'When the user with no account is invited to the agenda, no activation mail is required to complete signup',
        type: 'boolean',
        default: false,
      },
      {
        field: 'aggregator',
        description:
          'Agenda aggregation. Do not forget to initialize the tab on the agenda admin menu',
        type: 'boolean',
        default: false,
      },
      {
        field: 'invitationMessage',
        description:
          'Customizable members invitation message, contribution instruction, completion and publication, members grouped messaging',
        type: 'boolean',
        default: false,
      },
      {
        field: 'docxExport',
        description: 'Word export feature',
        type: 'boolean',
        default: false,
      },
      {
        field: 'eventOwnershipTransfer',
        description:
          'Transfer ownership of event from one member to another within an agenda',
        type: 'boolean',
        default: false,
      },
      {
        field: 'memberCustom',
        description: 'Allow customisation of member fields',
        type: 'boolean',
        default: false,
      },
      {
        field: 'keepActivities',
        description: 'Keeps activities for an indefinite period',
        type: 'boolean',
        default: false,
      },
      {
        field: 'showTotals',
        description: 'Show totals on statistics page',
        type: 'boolean',
        default: false,
      },
    ],
  },
];
