import users from './services/users/index.js';
import agendaBack from './agenda/back.js';
import agendaEvents from './services/agendaEvents/index.js';
import networkApps from './services/networkApps.js';
import abilities from './services/abilities/index.js';
import homeBack from './home/back.js';
import generalFront from './general/front.js';
import sessionBack from './general/session.back.js';
import generalBack from './general/back.js';
import eventBack from './event/back.js';
import eventFront from './event/front.js';
import actionsFront from './event/actions.front.js';
import facebookFront from './auth/facebook.front.js';
import googleFront from './auth/google.front.js';
import localFront from './auth/local.front.js';
import resetFront from './auth/reset.front.js';
import settingsBack from './agenda/settings.back.js';
import members from './services/members/index.js';
import activitiesBack from './agenda/activities.back.js';
import stats from './services/stats/index.js';
import supervisor from './services/supervisor/index.js';
import webapp from './webapp/index.js';
import agendas from './services/agendas/index.js';
import activities from './services/activities/index.js';
import sentry from './services/sentry.js';
import sharesFront from './agenda/shares.front.js';
import agendaFront from './agenda/front.js';
import exportsBack from './agenda/exports.back.js';
import facebookBack from './agenda/facebook.back.js';
import exportsFront from './agenda/exports.front.js';

export default app => {
  users.plugApp(app);
  app.services.mails.plugApp(app);
  app.use('/agendas/:agendaUid/events.v2.:format', app.services.eventSearch.apps.agendas.getPublic());
  app.use('/agendas/:agendaUid/admin/events.v2.:format', app.services.eventSearch.apps.agendas.getRestricted());
  app.use('/agendas/:agendaUid/settings/exports', app.services.eventSearch.apps.agendas.getAgendaExportsSettings());
  app.use('/agendas/:agendaUid/admin/settings/exports', app.services.eventSearch.apps.agendas.getAgendaExportsSettings({ admin: true }));
  app.services.agendaLocations.apps(app, '/locations');
  app.services.agendaLocations.apps.agenda(app, '/agendas/:agendaUid/locations');
  app.services.agendaLocations.apps.agendaAdmin(app, '/:agendaSlug/admin/locations');
  agendaBack(app);
  app.use('/', app.services.inboxes.plugApp());
  app.services.agendaContribute.plugApp(app);
  agendaEvents(app);
  networkApps(app);
  abilities(app);
  app.services.agendaDocx.plugApp(app);
  homeBack(app);
  generalFront(app);
  sessionBack(app);
  generalBack(app);
  eventBack(app);
  eventFront(app);
  actionsFront(app);
  facebookFront(app);
  googleFront(app);
  localFront(app);
  resetFront(app);
  app.services.aggregators.plugApp(app);
  settingsBack(app);
  members(app);
  activitiesBack(app);
  stats.plugApp(app);
  supervisor.plugApp(app, '/supervisor');
  app.services.reports.plugApp(app);
  app.services.dynamicScripts.plugApp(app);
  webapp(app);
  agendas.plugApp(app);
  activities(app);
  sentry(app);
  sharesFront(app);
  app.services.agendaSearch.plugApp(app, '/agendas');
  agendaFront(app);
  exportsBack(app);
  facebookBack(app);
  exportsFront(app);
};
