"use strict";

module.exports = app => {

  require( './services/users' )( app );
  require( './event/search.front' )( app );
  require( './agenda/back' )( app );
  require( './inboxes/endpoints' )( app );
  require( './inboxes/pages' )( app );
  //require( './services/portals' )( app );
  require( './services/surveys' )( app );
  require( './services/agendaContribute' )( app );
  require( './services/agendaEvents' )( app );
  require( './services/agendaSchema' )( app );
  require( './services/networkApps' )( app );
  require( './services/abilities' )( app );
  require( './services/mails/unsubscription' )( app );
  require( './event/files' )( app );
  require( './services/agendaDocx' )( app );
  require( './services/agendaCalendar' )( app );
  require( './home/back' )( app );
  require( './user/settings.front' )( app );
  require( './general/front' )( app );
  require( './general/session.back' )( app );
  require( './general/back' )( app );
  require( './search/front' )( app );
  require( './event/form.back' )( app );
  require( './event/tagsForm.back' )( app );
  require( './event/back' )( app );
  require( './event/front' )( app );
  require( './event/actions.front' )( app );
  require( './auth/facebook.front' )( app );
  require( './auth/twitter.front' )( app );
  require( './auth/google.front' )( app );
  require( './auth/local.front' )( app );
  require( './auth/reset.front' )( app );
  require( './agenda/stakeholders.back' )( app );
  require( './agenda/emailstrategie.back' )( app );
  require( './agenda/embeds.back' )( app );
  require( './location/front' )( app );
  require( './location/back' )( app );
  require( './agenda/settings.back' )( app );
  require( './agenda/sources.back' )( app );
  require( './services/members' )( app );
  require( './agenda/members.back' )( app );
  require( './agenda/activities.back' )( app );
  require( './services/activities' )( app );
  require( './agenda/shares.front' )( app );
  require( './agenda/front' )( app );
  require( './agenda/exports.back' )( app );
  require( './agenda/groupActions.back' )( app );
  require( './agenda/facebook.back' )( app );
  require( './agenda/customized.back' )( app );
  require( './agenda/actions.front' )( app );
  require( './agenda/exports.front' )( app );

};
