import agendaBack from './agenda/back.mjs';
import networkApps from './services/networkApps.mjs';
import abilities from './services/abilities/index.mjs';
import homeBack from './home/back.mjs';
import generalFront from './general/front.mjs';
import sessionBack from './general/session.back.mjs';
import generalBack from './general/back.mjs';
import eventBack from './event/back.mjs';
import eventFront from './event/front.mjs';
import actionsFront from './event/actions.front.mjs';
import facebookFront from './auth/facebook.front.mjs';
import googleFront from './auth/google.front.mjs';
import localFront from './auth/local.front.mjs';
import resetFront from './auth/reset.front.mjs';
import settingsBack from './agenda/settings.back.mjs';
import members from './services/members/index.mjs';
import activitiesBack from './agenda/activities.back.mjs';
import webapp from './webapp/index.mjs';
import activities from './services/activities/index.mjs';
import sentry from './services/sentry.mjs';
import sharesFront from './agenda/shares.front.mjs';
import agendaFront from './agenda/front.mjs';
import exportsBack from './agenda/exports.back.mjs';
import facebookBack from './agenda/facebook.back.mjs';
import exportsFront from './agenda/exports.front.mjs';

export default app => {
  app.services.users.plugApp(app);
  app.services.mails.plugApp(app);
  app.use('/agendas/:agendaUid/events.v2.:format', app.services.eventSearch.apps.agendas.getPublic());
  app.use('/agendas/:agendaUid/admin/events.v2.:format', app.services.eventSearch.apps.agendas.getRestricted());
  app.use('/agendas/:agendaUid/settings/exports', app.services.eventSearch.apps.agendas.getAgendaExportsSettings());
  app.use(
    '/agendas/:agendaUid/admin/settings/exports',
    app.services.eventSearch.apps.agendas.getAgendaExportsSettings({ admin: true }),
  );
  app.services.agendaLocations.apps(app, '/locations');
  app.services.agendaLocations.apps.agenda(app, '/agendas/:agendaUid/locations');
  app.services.agendaLocations.apps.agendaAdmin(app, '/:agendaSlug/admin/locations');
  agendaBack(app);
  app.use('/', app.services.inboxes.plugApp());
  app.services.agendaContribute.plugApp(app);
  app.services.agendaEvents.plugApp(app);
  networkApps(app);
  abilities(app);
  app.services.agendaDocx.plugApp(app);
  homeBack(app);
  generalFront(app);
  sessionBack(app);
  generalBack(app);
  eventBack(app);
  eventFront(app);
  actionsFront(app);
  facebookFront(app);
  googleFront(app);
  localFront(app);
  resetFront(app);
  app.services.aggregators.plugApp(app);
  settingsBack(app);
  members(app);
  activitiesBack(app);
  app.services.stats.plugApp(app);
  app.services.supervisor.plugApp(app, '/supervisor');
  app.services.reports.plugApp(app);
  app.services.dynamicScripts.plugApp(app);
  webapp(app);
  app.services.agendas.plugApp(app);
  activities(app);
  sentry(app);
  sharesFront(app);
  app.services.agendaSearch.plugApp(app, '/agendas');
  agendaFront(app);
  exportsBack(app);
  facebookBack(app);
  exportsFront(app);
};
