'use strict';

module.exports = app => {
  require('./services/users').plugApp(app);
  app.services.mails.plugApp(app);
  app.use('/events/search', app.services.eventSearch.apps.events());
  app.use('/agendas/:agendaUid/events.v2.:format', app.services.eventSearch.apps.agendas.getPublic());
  app.use('/agendas/:agendaUid/admin/events.v2.:format', app.services.eventSearch.apps.agendas.getRestricted());
  app.use('/agendas/:agendaUid/settings/exports', app.services.eventSearch.apps.agendas.getAgendaExportsSettings());
  app.use('/agendas/:agendaUid/admin/settings/exports', app.services.eventSearch.apps.agendas.getAgendaExportsSettings({ admin: true }));
  app.services.agendaLocations.apps(app, '/locations');
  app.services.agendaLocations.apps.agenda(app, '/agendas/:agendaUid/locations');
  app.services.agendaLocations.apps.agendaAdmin(app, '/:agendaSlug/admin/locations');
  require('./agenda/back')(app);
  app.use('/', app.services.inboxes.getApp());
  app.services.agendaContribute.plugApp(app);
  require('./services/agendaEvents')(app);
  require('./services/agendaSchema')(app);
  require('./services/networkApps')(app);
  require('./services/abilities')(app);
  require('./services/mails/unsubscription')(app);
  require('./event/files')(app);
  require('./services/agendaDocx')(app);
  require('./services/agendaCalendar')(app);
  require('./home/back')(app);
  require('./general/front')(app);
  require('./general/session.back')(app);
  require('./general/back')(app);
  require('./search/front')(app);
  require('./event/back')(app);
  require('./event/front')(app);
  require('./event/actions.front')(app);
  require('./auth/facebook.front')(app);
  require('./auth/twitter.front')(app);
  require('./auth/google.front')(app);
  require('./auth/local.front')(app);
  require('./auth/reset.front')(app);
  require('./agenda/emailstrategie.back')(app);
  require('./agenda/embeds.back')(app);
  app.services.aggregators.plugApp(app);
  require('./agenda/settings.back')(app);
  require('./services/members')(app);
  require('./agenda/activities.back')(app);
  require('./services/stats').plugApp(app);
  require('./services/supervisor').plugApp(app, '/supervisor');
  require('./webapp')(app);
  require('./services/agendas').plugApp(app);
  require('./services/activities')(app);
  require('./agenda/shares.front')(app);
  app.services.agendaSearch.plugApp(app, '/agendas');
  require('./agenda/front')(app);
  require('./agenda/exports.back')(app);
  require('./agenda/facebook.back')(app);
  require('./agenda/actions.front')(app);
  require('./agenda/exports.front')(app);
};
