#!/bin/sh
. "$(dirname $0)/_/husky.sh"

set -e

REQUIRED_PKG="jq"

if ! dpkg -s jq >/dev/null 2>&1; then
  echo Missing package $REQUIRED_PKG. Installing...
  sudo apt install $REQUIRED_PKG -y
fi

WORKSPACES=$(yarn workspaces list --json)
MODIFIED_PACKAGES=""


maybe_modified_package() {
  NAME=$(echo "$1" | jq -r .name)
  LOCATION=$(echo "$1" | jq -r .location)

  if [ -n "$(git --no-pager diff --cached --name-only --diff-filter=ACDMR -- "$LOCATION")" ]; then
    if [ -z "$MODIFIED_PACKAGES" ]; then
      MODIFIED_PACKAGES="$NAME"
    else
      MODIFIED_PACKAGES="$MODIFIED_PACKAGES,$NAME"
    fi
  fi
}

for WORSPACE in $WORKSPACES; do
  maybe_modified_package "$WORSPACE"
done

if [ -z "$MODIFIED_PACKAGES" ]; then
  exit 0
fi

yarn workspaces foreach \
  -Rpv --topological-dev --from "{$MODIFIED_PACKAGES}" \
  run lint-staged
