export default {
  basic: [
    'id',
    'uid',
    'fullName',
    'username',
    'email',
    'culture',
    'image',
    'isNew',
    'createdAt',
    'updatedAt',
  ],
  detailed: [
    'facebookUid',
    'twitterId',
    'googleId',
    'isActivated',
    'isBlacklisted',
    'isRemoved',
    'lastNotified',
    'lastSignin',
    'lastInboxCheck',
    'comexposiumId',
    'transverseApiAccess',
  ],
};
