# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    environment: Nodejs test

    strategy:
      matrix:
        node-version: [18, 20]
        # See supported Node.js release schedule at https://github.com/nodejs/Release

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis
      uses: superchargejs/redis-github-action@1.2.0

    - run: mv yarn.lock-workspace yarn.lock

    - run: yarn -v

    - run: yarn config

    - run: yarn

    - run: yarn workspaces foreach -Apv --topological-dev run prepack

    - run: yarn workspaces foreach -Atv run test --colors
      env:
        AWS_DEV_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
        AWS_DEV_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
        OA_API_PUBLIC_KEY: ${{ secrets.TEST_SDK_PUBLIC_KEY }}
        OA_API_SECRET_KEY: ${{ secrets.TEST_SDK_SECRET_KEY }}
