name: Release

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
      - 'public/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_commit_sha:
        description: 'Optional: The SHA of the release commit to synchronize manually'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    # Only trigger on pushes to the main branch or manually
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.ref_name == 'main')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Add public remote
        run: |
          git remote add oa-public "https://github.com/OpenAgenda/oa-public.git" || true

      - name: Install
        uses: ./.github/composite-actions/install
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          font-awesome-npm-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build
        run: yarn turbo prepack

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          commit: 'chore: version packages'
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload NPM Debug Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: /home/runner/.npm/_logs/*.log
          retention-days: 1

      - name: Sync to public
        run: |
          git checkout main
          ./scripts/sync-releases-to-public.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
