import { resolve } from 'node:path';
import { defineConfig } from 'tsdown';

// Builds dist/sdk-bundle.js — the self-contained SDK bundle the sandbox preamble
// prepends to every program. The sandbox runs an inline ESM program via stdin
// with NO node_modules, so @openagenda/api-client (which imports ky + zod) can't
// be imported there: everything is inlined into one IIFE exposed as
// globalThis.__OA_SDK__.
//
// This is a BUILD ARTIFACT — output to a gitignored dist/ (like the other
// packages), NOT committed. It is rebuilt before start/test/smoke and on prepack
// (see package.json). Regenerate manually with:
//   yarn workspace @openagenda/mcp build
export default defineConfig({
  entry: { 'sdk-bundle': 'scripts/sandbox-bundle-entry.js' },
  outDir: 'dist',
  // dist/ is a dedicated, gitignored output dir → cleaning it is safe.
  clean: true,
  format: ['iife'],
  globalName: '__OA_SDK__',
  platform: 'neutral',
  dts: false,
  sourcemap: false,
  // Inline ky + zod (zod is a real mcp dep → externalized by default; force it in).
  deps: { alwaysBundle: ['ky', 'zod'] },
  // Bundle api-client from SOURCE (no built dist of api-client required).
  alias: {
    '@openagenda/api-client': resolve(
      import.meta.dirname,
      '../api-client/src/index.ts',
    ),
  },
  // Exact output filename (no ".iife" infix) + generated banner.
  outputOptions: {
    entryFileNames: 'sdk-bundle.js',
    banner: [
      '// @generated by `yarn build` (tsdown) — DO NOT EDIT, NOT COMMITTED.',
      '// Self-contained @openagenda/api-client (ky + zod inlined), as globalThis.__OA_SDK__.',
    ].join('\n'),
  },
});
